### ISSUE TITLE
Setup changelog and enforce semver for sealed-secrets Helm chart release process

### ISSUE THREAD

**Issue by stevo-f3** [bitnami-labs/sealed-secrets#1001]
**Which component**:
sealed-secrets Helm chart, all versions at least up to the current (v2.6.9)

**Is your feature request related to a problem? Please describe.**
Currently a breaking change can be shipped in a patch release e.g. v2.1.3 chart patch release included a breaking change https://github.com/bitnami-labs/sealed-secrets/pull/734 (`commandArgs` dropped, replaced with `args`), resulting in all sorts of misconfiguration, like key rotation config to be silently ignored; see related issue https://github.com/bitnami-labs/sealed-secrets/issues/753

**Describe the solution you'd like**
To reduce chance of breaking changes please consider:
- establishing and documenting sealed-secrets Helm chart release versioning and changelog documenting policy
- automate enforcing the policy
  - automate sealed-secrets Helm chart change commit message validation - require prefix like `fix`, `chore`, `feat` for different kind of changes, and on merge to master automate release of sealed-secrets chart changes - depending on commit message release next patch, minor, or major release of the chart and generate appropriate change log entry in Github release of the chart
  - alternatively automate requirement checking that every PR/commit to sealed-secrets Helm chart includes appropriate Chart.yaml version change and changelog entry

**Describe alternatives you've considered**
Expect chart users to dig trough commit history and details of every commit to uncover kind of changes included in a release.

Just having https://github.com/bitnami-labs/sealed-secrets/tree/main/helm/sealed-secrets#upgrading is not sufficient either, too easy to be missed to be documented without proper enforcement.

**Additional context**

**Comment by agarcia-oss** [comment]
Hi @stevo-f3  thanks so much for the feedback. It's true that the release process of Sealed Secretts Charts can be improved and we'd like to take the task of creating a changelog  for it.
