### ISSUE TITLE
cannot list resource "secrets" in API group "" at the cluster scope

### ISSUE THREAD

**Issue by mateuszdrab** [bitnami-labs/sealed-secrets#1017]
**Which component**:
controller

**Describe the bug**
It seems that the clusterrole is missing the list permission for secrets - this prevents the sealed secrets controller from working.
I think this is related to the new feature implemented in https://github.com/bitnami-labs/sealed-secrets/pull/963

**To Reproduce**
- deploy latest helm chart
- add a sealedsecret
- the error will be logged
```
W1015 18:17:35.756308       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:kube-system:sealed-secrets-controller" cannot list resource "secrets" in API group "" at the cluster scope
E1015 18:17:35.756413       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:kube-system:sealed-secrets-controller" cannot list resource "secrets" in API group "" at the cluster scope
```

**Expected behavior**
The secret should be unsealed - which happend only after manually adding the list permission to the clusterole

**Version of Kubernetes**:
1.24.4

- Output of `kubectl version`:

```
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.24.4
```

**Additional context**

**Comment by alemorcuq** [comment]
Hi, @mateuszdrab.

The latest released chart seems to be missing the `watch` rule for secrets, but `list` is already there. Did you mean you added `watch`? If not, what `list` rule did you add?

We will release a new chart adding the missing `watch` rule.

**Comment by torhagl** [comment]
I had the same issue. Fixed it by adding the `list` verb to the part of the clusterrole concerning `secrets`. I see that the helm charts in the bitnami repo's doesn't have the list verb for secrets, however it is present in the helm chart of this repository. How come they are different?

Anyway the fix is to add the list verb to the secret resource part of the clusterrole `sealed-secrets-controller-unsealer`, like so: 

```
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
  - create
  - update
  - delete
```

**Comment by torhagl** [comment]
I think what causes the confusion here is that new versions are still being pushed as patch versions to the Helm chart hosted in the bitnami repository at `https://charts.bitnami.com/bitnami` (which is the one I was using), but the Helm chart itself isn't updated to the one that is in this repository - at least there is a difference in the cluster-role, might be other places as well.

Whereas if I pull the 2.7.0 Helm chart from the sealed-secrets repo, I get the correct permissions etc. Maybe a deprecation notice should be put in place like was done for stable would be in order? See picture below.

<img width="838" alt="image" src="https://user-images.githubusercontent.com/26787631/196125368-6d1d5a9c-6285-4028-b952-66cb301413cc.png">

**Comment by mateuszdrab** [comment]
> Hi, @mateuszdrab.
> 
> 
> 
> The latest released chart seems to be missing the `watch` rule for secrets, but `list` is already there. Did you mean you added `watch`? If not, what `list` rule did you add?
> 
> 
> 
> We will release a new chart adding the missing `watch` rule.

I'm using the bitnami repo, sealed secrets chart version 1.1.6

There seems to be a difference between this repo and the labs one

**Comment by agarcia-oss** [comment]
Hi @mateuszdrab ,

[Bitnami Charts Sealed Secret](https://github.com/bitnami/charts) is an independent project and the issue you're commenting on in this ticket should be reported [there](https://github.com/bitnami/charts/issues). 

The Sealed Secrets project [maintains its own, upstream version of the Helm Chart](https://github.com/bitnami-labs/sealed-secrets/tree/main/helm/sealed-secrets). Both Charts (Bitnami and Sealed Secrets upstream) are valid options but we only provide support for the upstream one.
