### ISSUE TITLE
New name in releases. One-off or permanent?

### ISSUE THREAD

**Issue by jbouter** [bitnami-labs/sealed-secrets#1019]
**Which component**:
GitHub releases

**Describe the bug**

A variation has occurred in the naming scheme of sealed-secrets releases. Where previous releases were named "v0.18.5", the new release is named "release-v0.19.0". This currently breaks our automatic pipelines. We would like to know if we need to change our pipelines to a new release naming convention, or whether this has been a one off. In case of the latter, we'd also like to know if this change will be rectified for v0.19.0. Thanks in advance!

**To Reproduce**

1. Go to [the sealed-secrets releases page](https://github.com/bitnami-labs/sealed-secrets/releases)
2. Observe the difference between v0.18.5 and release-v0.19.0

**Expected behavior**

The release to be named v0.19.0 instead of release-v0.19.0

**Additional context**

<img width="495" alt="screenshot_2022-10-17_at_08 50 08" src="https://user-images.githubusercontent.com/6340770/196118424-2421a12f-dedd-4d35-bf11-17c13e7b753f.png">

**Comment by alemorcuq** [comment]
Hi, @jbouter.

It was a mistake. We have just released `v0.19.1` using the previous name.
