### ISSUE TITLE
AWS EKS: Unable to re-encrypt secrets

### ISSUE THREAD

**Issue by esteban1983cl** [bitnami-labs/sealed-secrets#1032]
**Which component**:
controller: v0.19.1 
kubeseal: v0.19.1

**Describe the bug**
Hi everyone, after upgrade from v0.13.1 to v0.19.1 I'm unable to re-encrypt secrets using kubeseal. I'm getting this error:
error: cannot re-encrypt secret: an error on the server ("") has prevented the request from succeeding (post services http:sealed-secrets-controller:http)

**To Reproduce**

1. Upgrade from v0.13.1 to v0.19.1 using helm chart version 2.7.0
2. Run command:
``shell
kubeseal --cert=https://sealed-secrets.example.com/v1/cert.pem --scope=cluster-wide --format=yaml --re-encrypt <metabase-database.yaml >tmp.yaml  && mv tmp.yaml metabase-database.yaml
``
4. Wait for 1 seconds
5. See error

**Expected behavior**
I need that re-encryption happens

**Version of Kubernetes**:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.15", GitCommit:"58178e7f7aab455bc8de88d3bdd314b64141e7ee", GitTreeState:"clean", BuildDate:"2021-09-15T19:23:02Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.16-eks-a05fdea", GitCommit:"a05fdea9a04815782f9c4b08eed73bb2d78b07e3", GitTreeState:"clean", BuildDate:"2022-06-09T21:50:47Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"
```

**Additional context**
I'm able to encrypt secrets, no problem there!

Thanks for your help

**Comment by alvneiayu** [comment]
hi @esteban1983cl 

I am trying to reproduce the problem from my side. I will come back with feedback as soon as possible.

Thanks a lot

Álvaro

**Comment by esteban1983cl** [comment]
Hi @alvneiayu do you have some news about this ?
Thanks for your help

**Comment by alvneiayu** [comment]
hi @esteban1983cl 

I am trying to reproduce it, but I can not. It is so strange because to do the re-encrypt (to rotate also) you need to consume an API exposed though the service. If you don't have access to this API, you don't have access to fetch certificates and then to encrypt. I am still investigating this problem.

Thanks

Álvaro

**Comment by esteban1983cl** [comment]
Hi @alvneiayu can you explain the use of this flag to pass v1.List ?

```shell
--recovery-private-key strings   Private key filename used by the --recovery-unseal command. Multiple files accepted either via comma separated list or by repetition of the flag. Either PEM encoded private keys or a backup of a json/yaml encoded k8s sealed-secret controller secret (and v1.List) are accepted.
```

currently I had download all compromised keys from mi k8s cluster and works in this way:

```shell
kubeseal -o yaml --recovery-unseal --recovery-private-key $(ls /Users/dolape/Temp/sealed-secrets/*.key | paste -sd "," -) --re-encrypt < certs-firebase-store-paris-services.sealed.yml --sealed-secret-file temp.yaml && kubeseal -o yaml --cert /tmp/ss-test-cert.pem< temp.yaml > temp.sealed.yaml
```

Thank you very much

**Comment by alvneiayu** [comment]
First of all @esteban1983cl, sorry. I thought that I answered you. Maybe you solved it but I am going to answer.

You can generate the list of the tls secrets generated by the sealed secrets storing it as a file. Then you can use it with the flag --recovery-private-key. For example:

```
$ k get secret -l=sealedsecrets.bitnami.com/sealed-secrets-key=active -o yaml > file.yaml
$ cat file.yaml
apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: LS0tLS1...
    tls.key: LS0tLS1...
  kind: Secret
  metadata:
    creationTimestamp: "2023-05-17T09:29:00Z"
    generateName: sealed-secrets-key
    labels:
      sealedsecrets.bitnami.com/sealed-secrets-key: active
    name: sealed-secrets-keysrk5h
    namespace: default
    resourceVersion: "605"
    uid: 7fd24f57-6c1b-4a7c-92a6-3c933c622f43
  type: kubernetes.io/tls
kind: List
metadata:
  resourceVersion: ""
```
Sorry again for the late answer.

Álvaro
