### ISSUE TITLE
Allow bypass error on encryption with expired certifcicates

### ISSUE THREAD

**Issue by PierreBart** [bitnami-labs/sealed-secrets#1041]
**Which component**:

`kubeseal` since [v0.18.0](https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.18.0).

**Is your feature request related to a problem? Please describe.**

In https://github.com/bitnami-labs/sealed-secrets/pull/818, you introduced a check to throw an error when the user tries to encrypt a secret using an expired certificate.

However, there is no way to bypass this check and still encrypt the secret with full knowledge of the evidence.

**Describe the solution you'd like**

Add a flag like `--no-expiry-verify` to `kubeseal` in order to bypass the certificate expiry check.

**Comment by agarcia-oss** [comment]
Thanks for the report and the proposal, @PierreBart! I see what you mean regarding the user experience point of view. 

We'd like to take a closer look at the issue and update the ticket as soon as possible.

**Comment by agarcia-oss** [comment]
Hi @PierreBart we'd like to know the use cases you have in mind for this request: Why do you need to encrypt a secret with an expired certificate? Isn't it just simpler to renew the sealing certificate? 

Unless we understand better the request, we don´t feel inclined to introduce a backdoor to allow expired certificates in the `kubeseal` implementation.

**Comment by PierreBart** [comment]
Hello @agarcia-oss ,

Thank you for getting back to me so quickly.

I will explain my current context and the issue I am facing.

Because of operational constraints in production, we decide to manage the creation and rotation of the certificates ourselves, and our certificates expired.

We see two long-term solutions for our current scenario:
1. We generate a new sealing certificate to encrypt the new secrets. We have two certificates, one of them is expired but we keep it to decrypt old secrets, and the new one decrypts new secrets.
2. We generate a new sealing certificate and take the opportunity to rotate all our secrets at once.

We prefer the second solution because:
1. It forces us to rotate our secrets
2. We avoid the burden of managing multiple certificates and secrets encrypted with multiple certificates. 

That being said, we need some time to plan such an operation in production.

As for now, we can't use the latest version of SealedSecrets for the encryption part. Having a flag with a limited lifetime to be compatible with the old way of working seems a good compromise to give the community some time to plan the migration. 

At last, this change seems to be a breaking change and we regret that it didn't appear in the release notes or that it wasn't introduced first as a warning to the users. That would have helped us anticipate the issue.

**Comment by TimDurward** [comment]
Our problem is identical to @PierreBart, specifically the time involved planning around the operation of rotating expired secrets. Introducing a flag to temporarily disable cert-expiration validation would come in hand in cases like this.
