### ISSUE TITLE
Cannot unmarshal object into Go struct .encryptedData of type string

### ISSUE THREAD

**Issue by milles9393** [bitnami-labs/sealed-secrets#1051]
**Which component**:
Sealed-secrets-controller

app.kubernetes.io/version: v0.18.0
helm.sh/chart: sealed-secrets-2.2.0

**Describe the bug**
Suddenly sealing sealedSecrets became stuck in "Waiting for Sealed Secret to be decrypted" and our controller pod starting throwing weird logs. 
 
``` 
E1111 09:43:51.521880       
1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.4/tools/cache/reflector.go:167: 
Failed to watch *v1alpha1.SealedSecret: failed to list 
*v1alpha1.SealedSecret: json: 
cannot unmarshal object into Go struct field 
SealedSecretSpec.items.spec.encryptedData of type string
```

**To Reproduce**

1. Create sealedSecret using: 
```
$ kubeseal --controller-namespace sealed-secrets <unsecure-secret.yaml >sealed-secret.yaml
```
3. Wait for secret to be created by our sealedSecret

**Expected behavior**
We're expecting a secret to be created out of our sealedSecret

**Version of Kubernetes**:

- Output of `kubectl version`:

```
Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.22.8+9e95cb9
```

**Additional context**
I've found this issue https://github.com/bitnami-labs/sealed-secrets/issues/505 which could be what happened to us. I have however deleted all sealedSecrets created in the past week. They are also getting other logs than I am. 

I've also tried to replicate this by creating a sealedSecret in another cluster with non-ecryptable data but that returns different logs.  

```
 1 controller.go:175] illegal base64 data at input byte 0
2022/11/11 10:28:36 Event(v1.ObjectReference{Kind:"SealedSecret", Namespace:"mille", Name:"example", UID:"9597fab3-916d-49fe-8e69-28e348a4daef", APIVersion:"bitnami.com/v1alpha1", ResourceVersion:"346852444", FieldPath:""}): type: 'Warning' reason: 'ErrUnsealFailed' Failed to unseal: illegal base64 data at input byte 0
```

**Comment by milles9393** [comment]
Found a sealedSecret with some weird things inside encryptedData.


`oc get sealedsecrets -A -o json | jq .items[].spec.encryptedData` to get a list of all encryptedData

**Comment by alemorcuq** [comment]
Hi, @milles9393! Happy to hear you were able to spot the issue? Do you mind sharing with us a way to reproduce this? I think the error you faced should be more user friendly.

**Comment by milles9393** [comment]
> Hi, @milles9393! Happy to hear you were able to spot the issue. Do you mind sharing with us a way to reproduce this? I think the error you faced should be more user friendly.

Well, someone messed up when they created their sealedSecret so they ended up with a  .encryptedData:  with a lot of weird stuff. 

I was really surprised that this caused so much problems tho. We could not create or re-create any sealedSecrets for any namespace. 

What I would have liked to see in the logs is at least which secret got stuck in the error loop. Took me almost one day to catch the incorrect one.

**Comment by Ninsbean** [comment]
@milles9393 can you share how this "weird" encrypted data looks like?
It seems like we're having a similar issue at the moment and we do not see any "wrong" secrets. The only one I found which was suspicious was one entry with the value "null" but I'm not sure if this is already enough to blow the operator.

For explanation why it's not so easy to filter, we run a shared cluster with many different customers on it deploying stuff whenever they want.
