### ISSUE TITLE
Would kubeseal work for env variables in yaml file

### ISSUE THREAD

**Issue by saintmalik** [bitnami-labs/sealed-secrets#1057]
new to sealed secrets and the whole devops things, doing devsecops, need to secure the secrets implemented via gitops.

but the secrets were not added in the Secret files, but as an environment variable in the kind: Deployment file.

would kubeseal work for that?

**Comment by mkmik** [comment]
Don't out secrets directly in the env var in the deployment, but reference an item from a secret using `valueFrom` with `secretKeyRef`

https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
