### ISSUE TITLE
[feat] Add Drop ALL Capabilities 

### ISSUE THREAD

**Issue by JuanPabloSGU** [bitnami-labs/sealed-secrets#1060]
**Which component**:
This would affect controller (v0.19.2).

**Is your feature request related to a problem? Please describe.**
Currently it seems that 

```YAML
capabilities:
  drop: 
    - ALL
```

is missing from the container security context. If the container does not require those capabilities, would it be possible to drop them by default.

**Describe the solution you'd like**
The solution would have drop all capabilities by default in the controller if possible.

**Describe alternatives you've considered**
NONE

**Additional context**

**Comment by agarcia-oss** [comment]
Hi @JuanPabloSGU this is an interesting proposal; we're open to accepting PRs including this change.

Thanks!
