### ISSUE TITLE
Error in offline secret encryption

### ISSUE THREAD

**Issue by angelo291196** [bitnami-labs/sealed-secrets#1080]
**Which component**:
kubeseal version: v0.19.3

**Describe the bug**
When trying to do offline encryption of a secret by using the sealed-secrets controller certificate, I get the following error: 
"error: data does not contain any valid RSA or ECDSA certificates"

**To Reproduce**

1. Run the command 'kubeseal --fetch-cert > mycert.pem'
2. Run the command 'echo -n foo | kubeseal --cert mycert.pem --raw --namespace bar --name mysecret'
3. See error

**Expected behavior**
The encryption should be successfull. Executing online encryption with the same controller is working.

**Version of Kubernetes**:

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12", GitCommit:"c6939792865ef0f70f92006081690d77411c8ed5", GitTreeState:"clean", BuildDate:"2022-09-21T12:20:29Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12", GitCommit:"f941a31f4515c5ac03f5fc7ccf9a330e3510b80d", GitTreeState:"clean", BuildDate:"2022-11-09T17:12:33Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
The sealed secret controller is installed in a v1.23.12 AKS cluster. The steps have been executed on a Powershell terminal.

**Comment by agarcia-oss** [comment]
Hi @angelo291196 we've tried to reproduce your steps with the latest `kubeseal` binary:

```bash
$ kubeseal --fetch-cert > mycert.pem
$ echo -n foo | kubeseal --cert mycert.pem --raw --namespace bar --name mysecret
AgAkYk1X2gXVnlOjnYPGtY0TIJAMSvW5FCD8Myz9QC5GQs9Vmo2TMl6WUDuv33e/StTVFdOHWYVcaCL68QWCSjKEOQT3O/u1CEfKJaY0LCzWZ454/yy8t6gD2OhryB/ltJIe27Xt5ls1tEhgFm2yY5Px5bfGinaiZWektSVCs/x5tEWsfzYpjd8ip3/VAwSWQ2EUZdtL9V0=%
```
The error you're including might be related with a certificate file manipulation

**Comment by angelo291196** [comment]
Hi @agarcia-oss,
I tried to execute the steps in a bash shell on a Linux machine and I don't have the validation problem when I try to use the generated certificate. Maybe some characters are added when redirecting the output in Powershell, that cause errors in the certificate validation.

Thank you for the support!

**Comment by agarcia-oss** [comment]
Clossing the issue then, but we'll keep an eye on possible kubeseal windows issues.
