### ISSUE TITLE
Add ability to change name of secrets-unsealer clusterrole in the Helm chart

### ISSUE THREAD

**Issue by sarg3nt** [bitnami-labs/sealed-secrets#1082]
**Which component**:
Helm Chart 2.7.2

**Is your feature request related to a problem? Please describe.**
We currently have Kamus deployed to all of our clusters and want to replace it with Sealed Secrets. We need to run both while our users transition however both share the clusterrole secrets-unsealer
We could fork the repo and fix it ourselves but don't want to have to maintain that fork.
Would it be practical to make secrets-unsealer the default but make it configurable in the helm chart values file?

**Describe the solution you'd like**
Make the clusterrole secrets-unsealer name configurable via Helm but maintain the default name of secrets-unsealer for backwards comparability.
BTW, in the future, might be a good idea to namespace ClusterRoles, i.e. `bitnami-secrets-unsealer`

**Describe alternatives you've considered**
Forking the repo and doing it ourselves

**Additional context**
Kamus has been around for a while.  Don't know how popular it is but we've been using it for several years.  It looks to have been abandoned since the last release was in 2019.

**Comment by agarcia-oss** [comment]
Thanks for the feedback, @sarg3nt ! We'd like to take a look at the suggestion during our next [release cycle ](https://github.com/bitnami-labs/sealed-secrets/blob/main/CONTRIBUTING.md#release-process)

**Comment by sarg3nt** [comment]
Remove stale

**Comment by sarg3nt** [comment]
Remove stale

**Comment by sarg3nt** [comment]
Remove stale

**Comment by alemorcuq** [comment]
Hi, @sarg3nt. That is a very good point. I've created a PR to add a new value to the chart. It will be included in next week's release.

**Comment by alemorcuq** [comment]
Hi, @sarg3nt. A new version was released including this change. Thanks!
