### ISSUE TITLE
Controller Behavior with Existing Secrets

### ISSUE THREAD

**Issue by irrandon** [bitnami-labs/sealed-secrets#1090]
**Which component**:

Controller version 0.19.4

**Describe the bug**

If a secret with the same name as the sealed secret already exists, the controller will not create a new secret and will set the sync status of the Custom Resource to `false` which is fine.

However, if the existing secret is deleted, the controller will not automatically recreate it.

If the controller is restarted, it will create the secret again, but the sync status of the Custom Resource will not be updated to `true`.

**To Reproduce**

1. Create a secret
2. Create a sealed secret with the same name
3. Delete the first secret
4. Restart the controller

**Expected behavior**

The controller will automatically create the secret and update the Custom Resource after the existing one is deleted.

**Version of Kubernetes**:

Openshift 4.11.18 / Kubernetes v1.24.6

**Comment by agarcia-oss** [comment]
Hi @irrandon just to confirm, did you apply the `sealedsecrets.bitnami.com/managed: "true"` [annotation](https://github.com/bitnami-labs/sealed-secrets#managing-existing-secrets) to the existing secret in your cluster? 

If not, the Sealed Secrets controller will not be able to take control of the existing secrets and that will explain the behavior you're observing.

Regards

**Comment by irrandon** [comment]
Hello @agarcia-oss
This only works before the custom resource is created, which is not practical with tools like argocd.
