### ISSUE TITLE
PR #963 unintentional backwards compatibility break

### ISSUE THREAD

**Issue by josvazg** [bitnami-labs/sealed-secrets#1091]
**Which component**:
Controller

**Describe the bug**
PR #963 introduced recreation of deleted secrets managed by the controller. To do that, it needed permissions to watch for secret changes. That new permission breaks in low-privilege / multi-tenant environments, such as the one described in #1064

This issue proposes to recover backward compatibility by gracefully falling back to pre PR #963 behavior when watch secrets permissions are not possible.

**To Reproduce**

See #1064

**Expected behavior**

Fail install if lacking permissions, instructing to use a new flag to explicitly skip watching.

**Comment by abdennour** [comment]
@josvazg  Do you mean drift management ?

**Comment by josvazg** [comment]
@abdennour can you elaborate what do you mean by dirft management in this context?

Here we are just proposing to restore compatibility after we added some extra permission requirement that was not there before. The proposed solution is to fail if the missing permission is not allowed, but give the user a way to install by passing a explicit flag so that such permission is not required because secrets will not be watched, as happened in previous versions.

**Comment by josvazg** [comment]
BTW, I am picking this one up now.
