### ISSUE TITLE
503 Service Unavailable when using kubeseal

### ISSUE THREAD

**Issue by Ziktorin** [bitnami-labs/sealed-secrets#1117]
**Which component**:
kubeseal

**Describe the bug**
Any command in kubeseal causes a proxy error with "503 Service Unavailable"

**To Reproduce**

1. Use any kubeseal command that dials kubeseal pod(i.e. `kubeseal --fetch-cert --controller-namespace=flux-system > pub-sealed-secrets.pem`)
2. Get `error: cannot fetch certificate: error trying to reach service: proxy error from 127.0.0.1:6443 while dialing <kube-sealed-secrets-pod-ip>:8080, code 503: 503 Service Unavailable`

**Expected behavior**
Successful command execution

**Version of Kubernetes**:
`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6+k3s1", GitCommit:"9176e03c5788e467420376d10a1da2b6de6ff31f", GitTreeState:"clean", BuildDate:"2023-01-26T00:47:47Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6+k3s1", GitCommit:"9176e03c5788e467420376d10a1da2b6de6ff31f", GitTreeState:"clean", BuildDate:"2023-01-26T00:47:47Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
We are using a k3s deployment with fluxcd.
If we create a port-forwarding, then we can access api:
`curl 10.244.2.62:8080/v1/cert.pem`
```
-----BEGIN CERTIFICATE-----
MIIEzDCCArSgAwIBAgIQBI7GWy+SYlEskLpQahlGAzANBgkqhkiG9w0BAQsFADAA
...
-----END CERTIFICATE-----
```

**Comment by Ziktorin** [comment]
It seems that it only occurs when sealed-secrets is deployed with flux-system namespace. Changing it to kube-system resolved the issue.

**Comment by lilHermit** [comment]
I got caught out by this in the latest release. Is this likely to get fixed because deploying to `kube-system` isn't always desirable especially when fluxcd is in `flux-system` ?

**Comment by mxtw** [comment]
I was able to solve the problem by setting the helm value `networkPolicy.enabled` to `true`. The network policies deployed by flux seem to block the access.

**Comment by awfulwoman** [comment]
> I was able to solve the problem by setting the helm value `networkPolicy.enabled` to `true`. The network policies deployed by flux seem to block the access.

Thank you friend for solving this problem for me when using Flux!
