### ISSUE TITLE
newline at the end

### ISSUE THREAD

**Issue by jas01** [bitnami-labs/sealed-secrets#1122]
**Which component**:
Honnestly I've no idea where the problem are, but without sealedsecret it's working so...

**Describe the bug**

When using a secret keep in sealedsecret a newline are insert after the string. 

In detail : 

I'm trying to use my OKD with my keycloak, if I got through the configuration with the webui it's working straight away. But the client secret are store inside a classic secret. 
So I want to use a sealedsecret to keep the client secret, if I do that the authentification doesn't work, in the log of the authentification pod I can see they are a “%0A” in the url request just before the “&”. 
I check, recheck, recheck the file before using the kubeseal no newline at the end of the output of ```base64 -d```
I also check inside the webui of OKD with the «Reveal» buttom, don't see any newline either.
So I've no idea where the newline come from, but the URL definitely got a newline.
It's the only place (currently) I got a problem with sealedsecret

**Version of Kubernetes**:

```
4.12.0-0.okd-2023-02-18-033438
```

**Comment by agarcia-oss** [comment]
Hi @jas01 ,
Can you provide your version of sealed-secrets controller and `kubeseal`?

**Comment by jas01** [comment]
Sorry for the delay. 

So first I check the version of kubeseal and it was a old version (0.18.0) so I installed the last version I just download 
```
[linux]$ kubeseal --version
kubeseal version: 0.19.5
[linux]$ 
```
Recreate the secret etc.. But I still end up with same problem, here the log I get from the pod 
```
I0313 15:08:33.156688       1 handler.g:174] Error getting access token from an external OIDC provider (https://cerbere.XXXX.org/realms/XXXX/protocol/openid-connect/token?client_id=okd&client_secret=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX06%0A&code=36150cf4-9b98-43b7-b44c-389b113b33c3.8c6cd11d-bb77-4b08-839a-94f7b1a1f253.bacbf225-a129-4901-ba0e-dc710002d6d0&grant_type=authorization_code&redirect_uri=https%3A%2F%2Foauth-openshift.apps.paas.XXXX.org%2Foauth2callback%2FXXXX): Invalid client or Invalid client credentials   
E0313 15:08:33.156732       1 errorpage.go:28] AuthenticationError: Invalid client or Invalid client credentials
```

I redacted the secret until last two characters, as you can see he add a %0A at the end.

Regards.

**Comment by alemorcuq** [comment]
How are you creating the Sealed Secret? Could you give me an example command?

**Comment by jas01** [comment]
Here the command I use. 
Inside the file keycloak-token.txt I just paste the token (without newline)
```
oc create secret generic keycloak-clientsecret --from-file=clientSecret=keycloak-token.txt --dry-run=client -o yaml > tmp-secret.yaml
kubeseal -o yaml -n NAMESPACE < tmp-secret.yaml > keycloak-clientsecret.yaml
```
Just need to say it's the only problem I got so I'm not 100% sure the problem is with  sealedsecret because all my certificat are also use sealedsecret and all work without any problem. 

I also check inside OKD webui with the «reveal» bottom and the secret seem not have any newline (but for that I'm not 100% sure because maybe the webui drop the newline

**Comment by agarcia-oss** [comment]
Hi @jas01 
We're not sure if the `oc` command is creating some kind of artifact in the `tmp-secret.yaml` file. Can you create the secret file directly and try to seal it after that? You can follow [this tutorial](https://www.arthurkoziel.com/encrypting-k8s-secrets-with-sealed-secrets/) for instructions.

**Comment by code-R** [comment]
@jas01 is the above issue resolved for you? we are also seeing newline for the secrets that get created in the cluster.

**Comment by code-R** [comment]
Anyone whose facing similar issue, it's most likely issue with base64 encoding rather than sealed secrets..we used ```echo "some-secret" | base64``` to create secret, it adds a new line at the end, use ```echo -n "some-secret" | base64```.

**Comment by jas01** [comment]
> @jas01 is the above issue resolved for you? we are also seeing newline for the secrets that get created in the cluster.
Well, as I say sometime ago, each time I have the do the test I loose the user (because It's seem the user created are link to the object «secret» use in the OKD), so because of that and currently my OKD are under second phase test where user ... use it, I'm unable to do a new test.

In sometime (few months) I would re-install the OKD inside a openstack. I will keep you inform at that time.

**Comment by jas01** [comment]
> Anyone whose facing similar issue, it's most likely issue with base64 encoding rather than sealed secrets..we used `echo "some-secret" | base64` to create secret, it adds a new line at the end, use `echo -n "some-secret" | base64`.
Thanks for the tips....but...no...I already try this, multiple time. And just remember *every* other secret in my OKD are create the same way using sealed-secret and all work well. Just this one with the oauth don´t work.
