### ISSUE TITLE
Wrong behavior of automountServiceAccountToken

### ISSUE THREAD

**Issue by gnd** [bitnami-labs/sealed-secrets#1125]
**Which component**:

Controller, v2.7.5

**Describe the bug**

The behavior of automountServiceAccountToken introduced by https://github.com/bitnami-labs/sealed-secrets/pull/885 is like this: 

```
{{- if .Values.automountServiceAccountToken }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
{{- end }}
```
See: https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/templates/deployment.yaml#L50

Very similar, its also in the service account: 

```
{{- if .Values.serviceAccount.automountServiceAccountToken }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
```
See: https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/templates/service-account.yaml

I believe this is wrong. In restricted environments we need to *specifically disable* SA automounting and thus the deployment yaml as well as the SA yaml must containt the following: 

```
automountServiceAccountToken: false
```

It unfortunately doesnt work just by ommiting the automountServiceAccountToken altogether. I believe the logic surrounding `automountServiceAccountToken` should be changed in both cases to allow for a explicit `false`. 

**To Reproduce**

Just add this to your Values: 

```
# This changes the deployment
automountServiceAccountToken: false
serviceAccount:
  # This changes the Service Account
  automountServiceAccountToken: false
```

**Expected behavior**

We expect to find `automountServiceAccountToken: false` in both Deployment as well as in the Service Account.

**Comment by alemorcuq** [comment]
Thanks for reporting this. You are absolutely right.

**Comment by alemorcuq** [comment]
#1125 was merged. This will be fixed in the next release that will happen next week. Thanks again for reporting it.

**Comment by gnd** [comment]
thank you !

**Comment by alemorcuq** [comment]
A new version was released, @gnd. Thanks again!
