### ISSUE TITLE
Documentation for bring your own certs is invalid with new certificate expiry checks

### ISSUE THREAD

**Issue by jflowgh** [bitnami-labs/sealed-secrets#1126]
**Which component**:
The name (and version) of the affected component (controller or kubeseal)
'kubeseal' version 0.18.0+

**Describe the bug**
The docs for ["bring your own certs"](https://github.com/bitnami-labs/sealed-secrets/blob/main/docs/bring-your-own-certificates.md) are invalid. After generating, if you try to seal with `kubeseal` using the newly made certs, you get this error:

`error: failed to encrypt using an expired certificate on March 3, 2023`

You just need to add the `-days <DAYS>` option to the `openssl -x509` command to make it expire in the future.

**To Reproduce**

1. Generate certs [as per the docs over here](https://github.com/bitnami-labs/sealed-secrets/blob/main/docs/bring-your-own-certificates.md)
2. Try to seal with `kubeseal` i.e.:
` kubeseal --format yaml --cert ./mytls.crt < "secret.yaml" > "sealed-secret.yaml"`
3. You get an error from `kubeseal`:
`error: failed to encrypt using an expired certificate on March 3, 2023`
4. If you add `-days` to the SSL generation like `openssl req -x509 -days 356...` (for a 1 year expiry) then it works.

**Expected behavior**

You should be able to use the [bring your own certs docs](https://github.com/bitnami-labs/sealed-secrets/blob/main/docs/bring-your-own-certificates.md) without any errors from `kubeseal`.

**Version of Kubernetes**:

- Output of `kubectl version`:

N/A

```
(paste your output here)
```

**Additional context**

Should be a quick docs update. If you add `-days` to the SSL generation like `openssl req -x509 -days 356...` (for a 1 year expiry) then it works.

**Comment by alemorcuq** [comment]
Thanks for noticing this, @jflowgh. Would you be interested in contributing with this change?

**Comment by jflowgh** [comment]
Sure. How should I go about submitting?
