### ISSUE TITLE
Add option to replace Cluster Roles by namespaced Roles

### ISSUE THREAD

**Issue by josvazg** [bitnami-labs/sealed-secrets#1142]
**Which component**:
Controller Helm Chart

**Is your feature request related to a problem? Please describe.**

Right now the following [capabilities are defined by default as Cluster wide Roles](https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/templates/cluster-role.yaml):
- Monitor (get/list/watch) sealed secrets.
- Update sealed secrets' status.
- Fully manage (get/list/create/update/delete/watch) secrets.
- Emit (create/patch) events.

Cluster wide roles are problematic, as not all environments allow end users to rely on them.

For instance, multi-tenant environments do not allow for Cluster Roles or impose important restrictions to include custom permissions as one off special requests.

**Describe the solution you'd like**

For such environments we want instead the controller to have regular Roles on each of the managed namespaces.

**Additional context**

This was brought up by https://github.com/bitnami-labs/sealed-secrets/issues/1064 and replaces https://github.com/bitnami-labs/sealed-secrets/issues/1092

**Comment by alvneiayu** [comment]
solved with #1240
