### ISSUE TITLE
feature request: brew package for macOS

### ISSUE THREAD

**Issue by glerchundi** [bitnami-labs/sealed-secrets#116]
Any chance to deploy this to homebrew?

Loving it!

**Comment by anguslees** [comment]
I'm not a macOS user, so can't test this directly.  If someone closer to the mac/brew world could take this, that would be much appreciated.

**Comment by mellena1** [comment]
https://github.com/Homebrew/homebrew-core/pull/34556

😄 Thanks for a great tool!

**Comment by hpurmann** [comment]
@anguslees I think you forgot to close the issue :)

**Comment by anguslees** [comment]
Indeed! closing.
