### ISSUE TITLE
automountServiceAccountToken set to false breaks the deployment

### ISSUE THREAD

**Issue by gnd** [bitnami-labs/sealed-secrets#1161]
**Which component**:
Controller, v2.8.1

**Describe the bug**
This is a follow-up bug to https://github.com/bitnami-labs/sealed-secrets/issues/1125

Once setting the Service Account automount  for a sealed-secrets deployment and SA to `false`, sealed-secrets wont start up correctly. This is the error message: 

```
2023/03/21 15:47:00 Starting sealed-secrets controller version: 0.20.2
controller version: 0.20.2
panic: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

goroutine 1 [running]:
main.mainE({0x1bbade0, 0xc000012018}, 0x406719?, 0x60?, {0xc00003e0c0, 0x4, 0x4})
	/home/runner/work/sealed-secrets/sealed-secrets/cmd/controller/main.go:93 +0x226
main.main()
	/home/runner/work/sealed-secrets/sealed-secrets/cmd/controller/main.go:99 +0x4e
```

**To Reproduce**
Add this to your values and deploy using a Helm chart: 

```
# This changes the deployment
automountServiceAccountToken: false
serviceAccount:
  # This changes the Service Account
  automountServiceAccountToken: false
```

**Expected behavior**
Expectation would be for sealed-secrets to work without a SA automount OR no option to disable SA automount, in case its not possible.

**Comment by alemorcuq** [comment]
You are right, @gnd. The controller [needs the token mounted](https://github.com/kubernetes/client-go/blob/1517ffb8d37c99e6a3a2842bcdee0aa271f0332b/rest/config.go#L521). We will remove this property from the chart. Thanks.

**Comment by alemorcuq** [comment]
Will be removed in next release. Thanks again.
