### ISSUE TITLE
Add a --version flag to the CLI interface

### ISSUE THREAD

**Issue by smoyer64** [bitnami-labs/sealed-secrets#117]
It's currently difficult to determine which version of kubeseal is installed.

**Comment by anguslees** [comment]
Good call.

**Comment by c-knowles** [comment]
Duplicate of https://github.com/bitnami-labs/sealed-secrets/issues/55

**Comment by gtseres** [comment]
#55 is closed, where the issue does not seem fixed for me. To be more specific, I downloaded the `v0.7.0` version of `kubseal` for MacOS (https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.7.0/kubeseal-darwin-amd64), and the `version` flags does neither show up in the help message or is accepted by `kubeseal`. @c-knowles @arapulido can you verify?

**Comment by c-knowles** [comment]
@gtseres 0.7.0 predates those changes, it’s awaiting a new release from someone at Bitnami.

**Comment by gtseres** [comment]
@c-knowles thanks for the feedback! Is the next release planned soon?

**Comment by c-knowles** [comment]
@gtseres sorry I don’t know it’s up to the Bitnami team, @anguslees was running this project last time my team were pushing code here.

**Comment by mkmik** [comment]
I'll make a new release soon

**Comment by smoyer64** [comment]
Excellent news ... there are quite a few other changes we're waiting for!
