### ISSUE TITLE
Controller stops unsealing when an invalid SealedSecret object is deployed

### ISSUE THREAD

**Issue by FSchumacher** [bitnami-labs/sealed-secrets#1171]
**Which component**:
controller version 0.20.2

**Describe the bug**
The controller stops processing unsealing SealedSecrets, when an invalid SealedSecret is deployed.

In our case, the `template.metadata.labels` has invalid value type (`bool`) instead of expected type (`str`).

**To Reproduce**

1. Deploy the following invalid object definition:
```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: broken-template-secret
spec:
  encryptedData: {}
  template:
    metadata:
      labels:
        "not.a.string": true
```

2. Go to the controller and watch the logs.

    The controller stops processing and produces the following log lines (of which the last two lines get repeated about every 30s). 
```
W0405 09:08:25.440944 1 reflector.go:347] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: watch of *v1alpha1.SealedSecret ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: json: cannot unmarshal bool into Go struct field ObjectMeta.spec.template.metadata.labels of type string") has prevented the request from succeeding
W0405 09:08:26.596910 1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: failed to list *v1alpha1.SealedSecret: json: cannot unmarshal bool into Go struct field ObjectMeta.items.spec.template.metadata.labels of type string
E0405 09:08:26.596944 1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: Failed to watch *v1alpha1.SealedSecret: failed to list *v1alpha1.SealedSecret: json: cannot unmarshal bool into Go struct field ObjectMeta.items.spec.template.metadata.labels of type string
```

**Expected behavior**

Log a message about the broken object and *continue* to process the valid sealed secrets.

**Version of Kubernetes**:

- Output of `kubectl version`:

```
Kubernetes Version: v1.24
```

**Comment by cloud-pushers** [comment]
We are facing the same issue.
One faulty sealed-secret blocks the whole controller.

**Comment by agarcia-oss** [comment]
Thanks for the report, @FSchumacher . There is an issue with the controller while dealing with broken Sealed Secrets definition. We'll start working on a fix asap.
