### ISSUE TITLE
sealed-secrets API ValidateSealedSecret missing certURL Option

### ISSUE THREAD

**Issue by rowi1de** [bitnami-labs/sealed-secrets#1208]
**Which component**:
kubeseal

**Describe the bug**
Using the validate function will result in an error when the service to fetch the certificate is not reachable 

**To Reproduce**
Use AWS EKS with calico

**Expected behavior**
- The ValidateSealedSecret API should work, when the service is not reachable inside the cluster.
- Other APIs allow fetching the certificate from provided certURL

**Additional context**

https://github.com/bitnami-labs/sealed-secrets/blob/67c2699797425dff2d39f550b42b1782d2ba406e/pkg/kubeseal/kubeseal.go#L245

Similar to https://github.com/bitnami-labs/sealed-secrets/issues/1206

**Comment by alvneiayu** [comment]
hi @rowi1de

For security reason, the only way to validate the secret is to consume the endpoint exposed by the controller. If we want to do it offline, we need the private key to validate the secret. It is not a good idea to provide a feature like this, because it is not a good practice to export or to consume the private keys outside the controller.

We are accepting to use the private keys outside the cluster only in disaster situations. For example, you need to do a backup of your keys decrypting the secrets. But to validate the sealed secrets, we don't think that it is a good idea thinking in security reasons.

Thanks

Álvaro

**Comment by rowi1de** [comment]
> hi @rowi1de
> 
> For security reason, the only way to validate the secret is to consume the endpoint exposed by the controller. If we want to do it offline, we need the private key to validate the secret. It is not a good idea to provide a feature like this, because it is not a good practice to export or to consume the private keys outside the controller.
> 
> We are accepting to use the private keys outside the cluster only in disaster situations. For example, you need to do a backup of your keys decrypting the secrets. But to validate the sealed secrets, we don't think that it is a good idea thinking in security reasons.
> 
> Thanks
> 
> Álvaro

Hey @alvneiayu,

Thanks for the answer 👌🏻 the explanation makes totally sense from a security point of view.

However now I wonder why the validation fails if the secret can’t be fetched internally? I was under the assumption fetching the secret is always about the Public Key for encryption reasons and the private key is purely internal and only accessible by that controller itself?

Kind Regards
Robert

**Comment by rowi1de** [comment]
> hi @rowi1de
> 
> What is the error that you are reproducing trying to validate the sealed secrets? Could you show me logs, please?

 `kubeseal --validate --cert $SEALED_SECRETS_CERT --controller-namespace infrastructure --controller-name sealed-secrets `
 or   `kubeseal --fetch-cert  --controller-namespace infrastructure --controller-name  sealed-secrets ` both fail with:
 
```shell
2023/06/01 11:22:56 Connection to sealed secrets with (Namespace: infrastructure / ServiceName: sealed-secrets)
2023/06/01 11:22:56 Setup sealer: cannot fetch certificate: error trying to reach service: Address is not allowed
```

The problem is not a core problem of sealed-secrets probably, but the issue can happen on AWS EKS with different network interface providers .e.g. calico 
It currently requires a lot of custom code (Proxy via Ambassador Pattern), similar to described here: https://medium.com/@denisstortisilva/kubernetes-eks-calico-and-custom-admission-webhooks-a2956b49bd0d
