### ISSUE TITLE
Getting the latest version

### ISSUE THREAD

**Issue by igal-harel-sage** [bitnami-labs/sealed-secrets#1214]
Hi

I used https://api.github.com/repos/bitnami-labs/sealed-secrets/releases/latest in my workflow to retrieve the most recent version of all the components, specifically for obtaining the latest kubeseal. However, approximately two hours ago, it ceased to provide this information. I'm uncertain if this change was intentional or if it's a bug that will be addressed

Regards
Igal

**Comment by alemorcuq** [comment]
It was an oversight. It's fixed now. Thanks.
