### ISSUE TITLE
Replicas field is not defined in the deployment manifest

### ISSUE THREAD

**Issue by alita1991** [bitnami-labs/sealed-secrets#1218]
**Which component**:
controller:v0.20.2 (image version)
sealed-secrets:2.8.1 (chart version)

**Describe the bug**
I work on a project where I need to ensure that the charts I use follow the kubernetes best practices. I recently scanned the sealed-secrets helm chart with kube-score and I got an issue related to PDB. The solution for this issue is to declare in the deployment file `replicas: 1` or to expose replicas via the values file.

**To Reproduce**
Install the latest version of kube-score and scan the helm chart

**Expected behavior**
No critical issues should be reported

**Version of Kubernetes**:
v1.26

- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0+k3s1", GitCommit:"fae8817655a8ad1250d40e5b4f9a938cbb9c960a", GitTreeState:"clean", BuildDate:"2022-12-21T00:22:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
```
  [CRITICAL] Deployment has PodDisruptionBudget
      · No matching PodDisruptionBudget was found
          It's recommended to define a PodDisruptionBudget to avoid
          unexpected downtime during Kubernetes maintenance operations, such
          as when draining a node.
```

**Comment by agarcia-oss** [comment]
Closed as solved
