### ISSUE TITLE
Kubeseal complains about azure auth plugin

### ISSUE THREAD

**Issue by cheuk209** [bitnami-labs/sealed-secrets#1230]
**Which component**: Kubeseal v0.20.5

**Describe the bug**
When I use kubeseal to encrypt secrets such as 
`echo "blahblahblah" | kubeseal --raw -n {namespace} --scope namespace-wide --controller-name sealed-secrets` 

this was working the past 2 months, but right now it is returning the error:
`error: The azure auth plugin has been removed.
Please use the https://github.com/Azure/kubelogin kubectl/client-go credential plugin instead.
See https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins for further details`

Which seems to indicate it's a kubectl issue, but when I use kubectl at the commandline, it is completely fine.

**To Reproduce**
see above section

**Expected behavior**
When I run the command, I am expecting it to return an encrypted string at the command line.

**Version of Kubernetes**:

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12", GitCommit:"ee1f23b02a3368c47828ddfefce5777ff726862a", GitTreeState:"clean", BuildDate:"2023-02-08T17:22:02Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}```

**Additional context**
Add any other context about the problem here.

**Comment by alvneiayu** [comment]
hi @cheuk209 

I can not reproduce your problem with the latest version released (v0.22.0). I followed the usual steps [to connect with the cluster](https://azure.github.io/kubelogin/quick-start.html) and everything is working fine:

```
$ echo "blahblahblah" | kubeseal --raw --scope namespace-wide
AgBZfSgJZ7dqkbuMocr/4/KyQyn6PLGDkAbLj1Cc4DH0qsM6fbgykdV+YSEOCSy+GPk8AhZfxCcIr2pRAdPZcq7pp66BuOmGWm0iX0YrXnz3VzdCYSXuv5qz2ejUmvVTGmZcPNm44IskuIs/YYsJ0drnzTyXhhrTjFSprt3lUdm2SlM7kM4ogM4/UpvzbODrxzjYsUZg6TonhMEZd9hltrR0gkdeqGJjgxHIeCdtIClcXCsl310myPWsTe2dKfm3mJCnlM0w38n9eIMIMU0jaIt9hN+ArO0fV+GRms1EGSGdYsblJn0dUdDvFeYs+lUhHSEr+8c0B3GxcgISB7jH+cTNYZX+bsI+rPtiD3sdvk4ymHOVka4B0QszdJWOWbLgRzIZG7qzQTdv3SsGfpWn2AC6JTupy8T7S6KWRClgbA8U2dBMzGgkZ4KbV/GNdd2EykBXOGWWUl/Hd+TQGFA0ZFD1lDcs5F2CDfJkCbG80ixMNtgHGwqtYeMOTq8v8f/Tqz6A1L21m/PzQnIISHClCXCaw5Urh15LsFhK7UtRoVduv4WT3S1d+4ntgTJyVTmZs4zzpyFxJy5l9k2NpxPOjsX0zYCwzxv+uuKkcrDCBhGMRrNVGx4ausmhGbEhGkYk12TYTfrcwYys6Ppco3K/jMI1dWKI5oSB6+5BhJTeoa+4R8jpt1Jmtc70T0tF1oTbMsQAG3QX++k0CrLtAMUn
```
I can communicate without problems with the sealed secrets controller using kubeseal. Could you provide more information, please? (kubernetes version, more helpful information to reproduce the problem, etc).

Thanks a lot

Álvaro
