### ISSUE TITLE
Support Policy for Sealed Secrets

### ISSUE THREAD

**Issue by shazib-summar** [bitnami-labs/sealed-secrets#1233]
Hello.

I'm interested in the support policy followed by Sealed Secrets. I looked at the readme, but couldn't find anything regarding said topic. 

What versions are currently supported for production environments?

Thanks...

**Comment by agarcia-oss** [comment]
Hi @shazib-summar we currentlly support only the product [latest](https://github.com/bitnami-labs/sealed-secrets/releases) version.

**Comment by shazib-summar** [comment]
Thanks a lot @agarcia-oss, could you also clarify about the version compatibility with Kubernetes. What I mean is which version of sealed-secret should I deploy with my K8s version. 

Or is it supported versions only? i.e. the currently supported version of sealed-secrets is compatible with the currently supported version of kubernetes.

**Comment by agarcia-oss** [comment]
Hi @ shazib-summar the sealed secrets controller uses a stable Kubernetes API. Kubernetes versions > 1.16 are usually OK installing any version of Sealed Secrets. 
We support Kubernetes [latest](https://kubernetes.io/releases/) releases. Than teams, versions >1.24 are verified with our CI process with every release.

Regards!

**Comment by shazib-summar** [comment]
Hello @agarcia-oss do you think we should add this information in the [README](https://github.com/bitnami-labs/sealed-secrets#readme)? Supported version policy and compatibility with Kubernetes versions is something that would interest a lot of people using Sealed Secrets.

I would be more than happy to make a PR.

**Comment by agarcia-oss** [comment]
Absolutely! Happy to review the PR if you want to contribute! 👏
