### ISSUE TITLE
How to verify Release or use included .sig files

### ISSUE THREAD

**Issue by zatricky** [bitnami-labs/sealed-secrets#1236]
**Which component**:
kubeseal / Readme

**Is your feature request related to a problem? Please describe.**
When following the instructions to download kubeseal .tar.gz binary files, it is not explained how to use the .sig files to verify the binary downloads, assuming there is any way to verify the files.

**Describe the solution you'd like**
A clear and concise description in the readme of how to verify the download.

**Describe alternatives you've considered**
cosign/gpg with no instructions

**Additional context**
See:
.sig files here: https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.21.0
existing Download instructions here: https://github.com/bitnami-labs/sealed-secrets#linux

**Comment by agarcia-oss** [comment]
Hi @zatricky that sounds like a good suggestion. We're open to contributions if you want to add the additional documentation, thanks!

**Comment by zatricky** [comment]
@agarcia-oss  I totally would ... except this is also me asking how to do so since I couldn't figure it out. :-)

**Comment by alvneiayu** [comment]
hi @zatricky 

You need to use verify-[blob](https://docs.sigstore.dev/cosign/verify/):
```
cosign verify-blob --signature <path-to-the-signature-file> --key <sealed-secrets-folder-path>/.github/workflows/cosign.pub <path-to-the-file-to-verify>
```
Thanks a lot

Álvaro
