### ISSUE TITLE
kubeseal v0.21.x service mismatch when using helm chart

### ISSUE THREAD

**Issue by devonhk** [bitnami-labs/sealed-secrets#1252]
**Which component**:
Latest version of the sealed-secrets helm chart: currently `version: 2.10.0`

**Describe the bug**
`kubeseal` is not compatible with the sealed-secrets helm chart since it doesn't use the same service name as the regular manifests.

**To Reproduce**
1. Install latest helm-chart (it's currently pointing to app version 0.21)
2. Install the matching `kubeseal` binary
3. Run `kubeseal`

**Expected behavior**
Kubeseal doesn't return an error saying it can't find the sealedsecrets service.

**Actual behavior**
```shell
kubeseal
(tty detected: expecting json/yaml k8s resource in stdin)
error: cannot get sealed secret service: services "sealed-secrets-controller" not found
```
**Additional context**

Actual service name
```shell
k get svc | ag sealed-secrets
sealed-secrets   ClusterIP      10.43.98.173   <none>         8080/TCP                       14m
```

The CLI is expecting to find a service called `sealed-secrets-controller` because that's what it's called in the manifests that gets published in the Github releases. But for some reason, the helm chart uses a different name: `sealed-secrets https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/templates/_helpers.tpl#L19`

**Version of kubeseal**

```shell
kubeseal --version
kubeseal version: v0.21.1-0.20230526160912-30222944b0da
```

**Version of Kubernetes**:

- Output of `kubectl version`:

```shell
k version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.4+k3s1", GitCommit:"8d0255af07e95b841952563253d27b0d10bd72f0", GitTreeState:"clean", BuildDate:"2023-04-20T00:33:18Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by devonhk** [comment]
Found this section in the readme.
> NOTE: The helm chart by default installs the controller with the name sealed-secrets, while the kubeseal command line interface (CLI) tries to access the controller with the name sealed-secrets-controller. You can explicitly pass --controller-name to the CLI:

Seems like this is expected behavior. I guess this happened because the original maintainers of the community version of the helm chart decided to use a different name then regular manifests?

**Comment by devonhk** [comment]
For a UX improvement on the CLI, it could print out a short helm message if it can't find the `sealed-secrets-service`, telling the user how to manually specific the controller name.

**Comment by agarcia-oss** [comment]
Hi @devonhk , As you already commented on the issue, `kubeseal` and the helm chart have different configuration values by default. We cannot change this behavior without breaking backward compatibility, so your suggestion of improving the CLI UX makes a lot of sense.

**Comment by alemorcuq** [comment]
Hi, @devonhk.

I just want to add that there's no actual default name for the helm chart, it depends on the name you give your installation. If you install the chart as `sealed-secrets` the service will be called `sealed-secrets`. You can install the chart like this:

```
helm install sealed-secrets-controller sealed-secrets/sealed-secrets
```

And the service will be named `sealed-secrets-controller`. It all depends on the name you choose for your deployment.

On another note, thank you for suggesting a UX improvement.
