### ISSUE TITLE
Sealedsecrets controller unseal namespace-scope secrets with a list of namespaces

### ISSUE THREAD

**Issue by suxiaoxiaomm** [bitnami-labs/sealed-secrets#1258]
**Which component**:
controller

**Is your feature request related to a problem? Please describe.**
I have mixed sealed values inside on sealedsecrets resource. Those values are sealed with different namespaces.
This will cause controller to unseal fail.

**Describe the solution you'd like**
We can specify a list of namespaces as an annotation of the sealedsecrets resource, just like the "sealedsecrets.bitnami.com/extra-namespaces: "ns1,ns2"".
Then when controller want to do unseal, it can loop this namespace list, and also loop the encrytedData items,  do unsealing.

**Comment by alemorcuq** [comment]
This defeats the purpose of sealing scopes altogether, as it would allow users to deploy `SealedSecrets` they should not have access to in their namespaces and see the contents. If you require your secrets to be read in different namespaces, you can use the `cluster-wide` sealing scope.

**Comment by suxiaoxiaomm** [comment]
We do want the namespace scoped sealing strategy, but we have some shared secret values(of course also have namespace specific secret values.). For those shared secret values, it is just don't make sense to seal them repeatedly for all the namespaces.
For example, I modified the shared secrets' values, I have to change sealed values for all namespaces.
