### ISSUE TITLE
Allow to add annotations to grafana dashboard in helm chart.

### ISSUE THREAD

**Issue by devopstales** [bitnami-labs/sealed-secrets#1290]
**Which component**:
helm chart 2.11.0

**Is your feature request related to a problem? Please describe.**
I can not configure grafana dashboard to a folder.

**Describe the solution you'd like**
Add option to create annotation for grafana dashboard configmap like label. The path can be `metrics.dashboards.annotations`

**Comment by alemorcuq** [comment]
Hey, @devopstales. Next release will include this.
