### ISSUE TITLE
Component release should be the latest GH release

### ISSUE THREAD

**Issue by erikgb** [bitnami-labs/sealed-secrets#1301]
**Which component**:

N/A; this is GitHub/CI issue.

**Describe the bug**

The release marked as the latest GitHub should be the component release, and not the helm release, ref. https://github.com/bitnami-labs/sealed-secrets/releases:

![image](https://github.com/bitnami-labs/sealed-secrets/assets/1142578/d792ad17-caab-43d2-920c-559d4dc3a50b)

**To Reproduce**

N/A

**Expected behavior**

The component release should be the latest:

![image](https://github.com/bitnami-labs/sealed-secrets/assets/1142578/b5a9ffd5-9621-466b-acc9-d9218c430d0b)

**Comment by alemorcuq** [comment]
Fixed, thanks!
