### ISSUE TITLE
Re-encrypting secret created with old .pub file from old controller --> with new encryption key from new controller

### ISSUE THREAD

**Issue by uceimmp** [bitnami-labs/sealed-secrets#1305]
Hello 
I am raising a request to ask whether it would be possible to re-encrypt a secret that has been encrypted from a previous controller with a new encryption key

**_Scenario_** 
Old sealed-secrets controller went down and had to be re-deployed. Existing secrets encrypted by old controller are no longer able to be unsealed by new secrets controller. 

I am wanting to know whether an existing SealedSecret secret (sealed by old controller) can be:

- Unsealed 
- Re-encrypted with new .pub cert present in new controller (I am getting errors relating to 'ErrUnsealFailed')

**Comment by cccsss01** [comment]
If you have the old key, you're supposed to be able to do something like the link below.

How it's supposed to work is this https://github.com/bitnami-labs/sealed-secrets/issues/842

however, it's busted for me.
error: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }

**Comment by alvneiayu** [comment]
as @cccsss01, if you have the old keys you can use the feature defined in #842. If you don't have the old keys, it is impossible to decrypt them. When you redeploy in the same cluster without deleting all the resources, the controller will detect the old keys generated by other Sealed Secrets Controller. If you don't have any old resource, it is impossible.
