### ISSUE TITLE
Secrets clusterwide setup

### ISSUE THREAD

**Issue by linuxbsdfreak** [bitnami-labs/sealed-secrets#132]
Hi,

I am following the Managing Kubernetes secrets section under https://github.com/stefanprodan/gitops-helm .

I am would like to have my docker-registry-secrets creds globally and doing the following steps:
kubseal v0.5.1
controller v.0.7.0

I am performing the following steps
----------------------------------------

```
- kubeseal --fetch-cert --controller-namespace=adm --controller-name=sealed-secrets > pub-cert.pem

- kubectl create secret docker-registry docker-registry-secret --docker-server=xxxxx --docker-username=xxxx --docker-password=xxxx --docker-email="xxxx" --dry-run -o json > docker-registry-secret.json

added the lines in the json file

        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }

- kubeseal --format=yaml --cert=pub-cert.pem < docker-registry-secret.json > docker-registry-secret.yaml
```

Following is my directory structure in the git repo
-------------------------------------------------
```
├── adm

│   ├── docker-registry-secret.yaml

│   └── sealed-secrets.yaml

├── dev

│   ├── podinfo.yaml

│   └── pub-cert.pem

├── prod

│   ├── podinfo.yaml

│   └── pub-cert.pem

├── prod-customer1

│   ├── podinfo.yaml

│   └── pub-cert.pem

└── stg

   ├── podinfo.yaml

   └── pub-cert.pem
```

I keep getting the below error
2018/12/07 12:48:33 Updating adm/docker-registry-secret
2018/12/07 12:48:33 Error updating adm/docker-registry-secret, will retry: crypto/rsa: decryption error

I am clueless what am i doing wrong. Could you help me?

Regards,
Kevin

**Comment by linuxbsdfreak** [comment]
I tried the following

```
kubectl -n dev create secret generic basic-auth \
--from-literal=user=admin \
--from-literal=password=admin \
--dry-run \
-o json > basic-auth.json

kubeseal --format=yaml --cert=pub-cert.pem < basic-auth.json > basic-auth.yaml
```
and after commiting to the repo i see the basic-auth secret in the namespace. What is the issue with the docker registry type?

Regards,
Kevin

**Comment by linuxbsdfreak** [comment]
@anguslees . Could you check at your end if this is an issue? I even tried adding the secrets in the different namespaces as mentioned in the above link.

**Comment by caskolkm** [comment]
@linuxbsdfreak i thing this issue: https://github.com/bitnami-labs/sealed-secrets/issues/86 related to your problem?

**Comment by anguslees** [comment]
@linuxbsdfreak You need `kubeseal` >=0.6.0 for cluster-wide annotation to be supported.
Issue #86 means you _also_ have to use `kubeseal` <0.7.0 for docker-registry secrets.

So to get both cluster-wide=true _and_ docker-registry secrets, **you have to use `kubeseal` v0.6.0**.  I know that's a bit silly, and it will be fixed in the next release (ie: >=0.8.0 will also be fine, once it exists).

Please reopen if kubeseal 0.6.0 doesn't work for you.

**Comment by tckb** [comment]
this is very unsettling. does it mean that the "cluster-wide" docker registry secrets is not available in the newer versions of Kubeseal? I tried w/ v0.9.2 it doesn't work.  looks to me like a regression ?

**Comment by mkmik** [comment]
uh, it should work in v0.9.x; could you please create a new bug report? If it's a regression I'd like to fix it ASAP.

**Comment by tckb** [comment]
thanks will create it 👍 @mkmik
