### ISSUE TITLE
Question: Is it possible to reencrypt a secret using a  newer cert?

### ISSUE THREAD

**Issue by weiyentan** [bitnami-labs/sealed-secrets#1356]
This is not to highlight a problem. We are using sealed secrets on many different clusters. We have a common app that has a sealed secret that we need to apply to all clusters. In this case we have a common sealed secret certificate that goes across to all clusters and is set to active on the annotations.

Encrypting with this certificate is fine and we are able to generate the sealed secret certificate for all clusters using kubeseal. There is an option in kubeseal to reencrypt the secret certificate using a new certificate from the controller. 

Can we use  the --cert flag to reencrypt the sealed secret certificate?

Many thanks for the help.

**Comment by alemorcuq** [comment]
No, you can't use the `--cert` flag with the `--re-encrypt` one. However, if your new certificate is on the cluster, using `kubeseal --re-encrypt` should re-encrypt the secret with the latest certificate.

Am I missing something here?

**Comment by weiyentan** [comment]
> Am

The question they I have is if we have multiple clusters how do we manage a common cert between them?
