### ISSUE TITLE
Rotating master key

### ISSUE THREAD

**Issue by peterbosalliandercom** [bitnami-labs/sealed-secrets#137]
For security reasons we would like to rotate the master key frequently because the private key could be copied from the cluster and reused in another cluster to decrypt sealed secrets which are in a public repo. 

Is this possible?

**Comment by mkmik** [comment]
The bulk of the feature has been implemented in #143 but there are still some rough edges:

@grossvogel wrote in #95
> I apologize if this is off topic, but I've been looking at this awesome tool and wondering specifically about updating existing secrets. Can somebody tell me whether the work planned for this feature would allow e.g. adding new data to a sealed secret whose encryption key has been rotated out?

> My impression is that (a) each sealed secret currently has a single applicable encryption key and (b) older secrets aren't automatically re-encrypted upon key rotation and (c) only the latest key is currently accessible to the client... but maybe / hopefully I'm missing something?

@grossvogel, the new `--rotate` flag allows users to update their local checked-in copy of the sealed secret by decrypting an existing secret.

This feature is still underdocumented and probably there are many rough edges. I'll work on this as soon as I cut a release with the rest of the long overdue but more stable features.

**Comment by mkmik** [comment]
Status update: the bulk of this feature is going to be released in v0.8.0 but not turned on by default.
Full rollout blocked on #185 and possibly other issues; I still didn't have enough time to fully appreciate the implications of this.
