### ISSUE TITLE
Able to access pulbic key when using own key pair

### ISSUE THREAD

**Issue by BlueCog** [bitnami-labs/sealed-secrets#1379]
Hi All,

We're using own key pairs on our sealed-secrets implementations. We are hosting the pulbic keys seperately. But is seems from the docs that there is also an internal API of the sealed-secrets controller that could be used to retrieve the pulbic keys. Is this correct? 

I've tried accessing te service provided with sealed-secrets (Service: sealed-secrets-controller on 8080) but i'm not getting an answer...

Greets!

**Comment by agarcia-oss** [comment]
Hi @BlueCog the public key certificate can be obtained using the `kubeseal` command as explained [here](https://github.com/bitnami-labs/sealed-secrets#public-key--certificate)

**Comment by BlueCog** [comment]
> Hi @BlueCog the public key certificate can be obtained using the `kubeseal` command as explained [here](https://github.com/bitnami-labs/sealed-secrets#public-key--certificate)
> 
> ```
> $kubeseal --fetch-cert
> -----BEGIN CERTIFICATE-----
> ...
> ```
> 
> That will retrieve the public key from the controller [internal endpoint](https://github.com/bitnami-labs/sealed-secrets/blob/main/pkg/controller/server.go#L92) :`/v1/cert.pem`

Hi @agarcia-oss thanks for the reply. What i'm understanding is that `--fetch-cert` will use the public key provided via the SealedSecrets Controller. 

We are using multiple private keys with multiple public keys. So it seems we have to host those public keys ourself. Like the docs say: "You can set up your internal automation to publish certificates somewhere you trust." "store the certificate somewhere (e.g. local disk)" 

I was hoping that via `$kubeseal --fetch-cert` we also could define other (custom) public keys.
