### ISSUE TITLE
Recreation of secret object after sync in ArgoCD

### ISSUE THREAD

**Issue by supertwister** [bitnami-labs/sealed-secrets#1391]
I have a question regarding the secret object:
Is a Sealed Secret object expected to be recreated after synchronizing changes in ArgoCD? (The change in the manifest involves an update to the secret itself)

I am asking because I did this in the past, and I recall that the secret object was recreated (its age reset to 0). Now, I have done it again (with another secret), and I don’t see that the object has been recreated. Should I be concerned?

Please be aware that I manually updated the secret value for testing purposes before pushing it to the repository and syncing it in ArgoCD. Could this be the reason the secret object was not recreated?

**Comment by alemorcuq** [comment]
Let me know if this is your scenario:

- You have a SealedSecret in ArgoCD
- You update the secret in your SealedSecret in ArgoCD and synchronize the changes
- The Secret managed by the SealedSecret is not changed

Is this what you are seeing? If that's it this shouldn't be the behavior, the Secret should be updated.

**Comment by supertwister** [comment]
Yeah, basically it is the scenario, but there is one missing step: Manually updating the secret value before syncing in ArgoCD, to verify the certificate in the secret (I've been wondering if perhaps the manual edit is the issue).

Anyway, what could be the issue? Is this an issue in the secret object itself or a synchronizing setting in ArgoCD?

**Comment by alemorcuq** [comment]
What version of the controller are you using?

Also, when you say you manually update the secret value, do you mean the plain Kubernetes secret value or the data field in the Sealed Secret? 

If you change the Kubernetes secret, do you change the value to a random one or to the correct value that the new Sealed Secret will have?

**Comment by supertwister** [comment]
I'm using app version 0.18.0 (chart version 2.2.0).

What i updated manually is the data field of Sealed Secret. It's the same value i pushed to the repo that ArgoCD should sync. 

The secret object behaves like it's not managed by SealedSecret, but i has the field of `sealedsecrets.bitnami.com/managed=true`.
