### ISSUE TITLE
Potential issue with helm install notes

### ISSUE THREAD

**Issue by alexellis** [bitnami-labs/sealed-secrets#141]
I was just running through the helm chart installation and saw this:

```
NOTES:
You should now be able to create sealed secrets.

1. Install client-side tool into /usr/local/bin/

GOOS=$(go env GOOS)
GOARCH=$(go env GOARCH)
wget https://github.com/bitnami-labs/sealed-secrets/releases/download/$release/kubeseal-$GOOS-$GOARCH
sudo install -m 755 kubeseal-$GOOS-$GOARCH /usr/local/bin/kubeseal
```

However, when running the command this always fails because `$release` is never defined and on Linux this generates the following invalid URL `https://github.com/bitnami-labs/sealed-secrets/releases/download//kubeseal-linux-amd64`.

I'd guess that having the release variable in the helm chart template would fix this.

What do you think?

**Comment by c-knowles** [comment]
You'll still need the `release=$(curl...` line from just above it on the [installation instructions](https://github.com/bitnami-labs/sealed-secrets#installation) but sounds like perhaps you are following some other instructions, could you point at which ones? The current readme I think it would be good to separate out instructions for the CLI and server parts.

**Comment by alexellis** [comment]
Hi thanks for getting back so soon. This is the output from helm after installing. Perhaps what you could do to fix this is something like just point to the latest URL or give the command to fetch the release variable in the helm chart output?

Alex

**Comment by anguslees** [comment]
Thanks for the report.  The helm chart is managed by different people, so I'm going to move this issue to the helm/charts repo.  Please stay on the line, your call is important to us, etc...

**Comment by anguslees** [comment]
(Moved to helm/charts#11258)
