### ISSUE TITLE
(question) sealed-secrets ingress, what use is it?

### ISSUE THREAD

**Issue by lknite** [bitnami-labs/sealed-secrets#1427]
I've deployed sealed secrets and using kubeseal I can specify controller-name & controller-namespace to use things.

I've also deployed an ingress using the helm chart.

1. How can I pass the url made available via the ingress to kubeseal ?
2. Can I use it to get the public cert?  (does the ingress make this unnecessary?)

**Comment by agarcia-oss** [comment]
Hi @lknite thanks for the report. The ingress element in Sealed Secrets chart is optional and we do not recommend its use in normal conditions. 
This feature was [introduced](https://github.com/helm/charts/pull/20251) to enable access to the sealed secrets certificate without exposing the Kubernetes API. However, it is much more advisable to expose the sealed secrets certificate using the default RBAC method.

**Comment by lknite** [comment]
Thank you!

For those who come across this later, to access the public cert append to ingress url:
/v1/cert.pem
