### ISSUE TITLE
About 0.25.0 release

### ISSUE THREAD

**Issue by chenrui333** [bitnami-labs/sealed-secrets#1435]
👋 Looks like @alvneiayu just fixed the goreleaser setup, is that going to be marked as latest release soon? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/160308

**Comment by alemorcuq** [comment]
It is now published, @chenrui333

**Comment by chenrui333** [comment]
@alemorcuq thanks a lot! 🙏
