### ISSUE TITLE
kubeseal does not respond 

### ISSUE THREAD

**Issue by druskus20** [bitnami-labs/sealed-secrets#1447]
**Which component**:

chart 2.14.2 (and others)
kubseal: 0.25 (and previous)

**Describe the bug**
Same issue as: https://github.com/bitnami-labs/sealed-secrets/issues/317 (CLOSED)
The following command does not respond:
```
kubeseal --controller-namespace kube-system --controller-name sealed-secrets --format yaml < a.yaml
```
The suggestion by this user works: 
https://github.com/bitnami-labs/sealed-secrets/issues/317#issuecomment-769200665

**Expected behavior**
Kubeseal seals my secret a.yaml and prints it to screen.

**Additional context**
* Using EKS, k8s version 1.27.
* I've tried several versions of kubeseal and the helm chart.
* I am currently using ArgoCD but using helm results in the same.
* Kubeseal is working fine on another, very similar, older cluster. (older sealed-secrets version). But even that older version does not work in my current cluster.

I believe the issue is not yet resolved, hence why I am opening a new one.

**Comment by agarcia-oss** [comment]
Hi @druskus20 

I just tried to verify the issue in an EKS cluster but I cannot reproduce it. Did you try the fetch-cert command to check the connectivity?

**Comment by druskus20** [comment]
Hi @agarcia-oss

I tried to run `kubeseal --fetch-cert` with the same result. The CLI hangs waiting for the response of kubeseal. 
The `controller-namespace` and `controller-name` flags in my cluster are correct.

Here you can see how, executing a kubeseal command with the wrong namespace or name results in an error message. 
However, when set correctly, the CLI hangs. 

![image](https://github.com/bitnami-labs/sealed-secrets/assets/43417195/a7b4c0a8-f331-40b2-9406-bbc0e0658fe3)

I also checked the `aws-auth` configmap, and copied the one from my working cluster into the cluster in which kubeseal fails to respond, with no success.

**Comment by metalwhale** [comment]
@druskus20 cc @agarcia-oss 
I believe the issue stems not from `kubeseal` or `sealed-secrets`, but from the connection between the control plane and the worker nodes on EKS.

If you use [`eks`](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest) module for creating your cluster, you can try adding this following code inside the module:
```terraform
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "20.8.3"

  # ...
  node_security_group_additional_rules = {
    ingress_from_control_plane = {
      type                          = "ingress"
      # Feel free to change these to your desired ports
      from_port                     = 0
      to_port                       = 0
      protocol                      = "-1"
      source_cluster_security_group = true
    }
  }
  # ...
```
By default `eks` module has enabled some ingresses that allow connections from control plane to worker nodes, but AFAIK port `8080` (as used by `sealed-secrets` controller) is not included.

I got the same problem and after adding the above security group `kubeseal` works like a charm.

**Comment by druskus20** [comment]
@agarcia-oss @metalwhale 
Thanks! that helped. 
All is left is for me to figure out exactly which security rules I'm missing

**Comment by druskus20** [comment]
I believe I figured out why: 

```
resource "aws_security_group_rule" "sealed-secrets-access" {
  type              = "ingress"
  from_port         = 8080
  to_port           = 8080
  protocol          = "tcp"
  security_group_id = module.eks.node_security_group_id
  #security_group_id = module.eks.node_security_group_id
  #security_group_id = module.eks.cluster_primary_security_group_id
  source_security_group_id = module.eks.cluster_security_group_id
  description = "Allow inbound traffic to sealed-secrets controller"
}
```

I had this rule configured on the cluster security group, instead of the node security group. Thanks!

**Comment by jicowan** [comment]
I have the same issue. When i try to use seal secrets, I see the following: 
```
I0309 21:03:22.109750   68957 round_trippers.go:517] HTTP Trace: Dial to tcp:127.0.0.1:58945 succeed
I0309 21:03:22.304063   68957 round_trippers.go:560] GET https://127.0.0.1:58945/3c0e76b59eaab6eb95ef2051580a90d4/api/v1/namespaces/kube-system/services/http:sealed-secrets-controller:http/proxy/v1/cert.pem 200 OK in 194 milliseconds
I0309 21:03:22.304120   68957 round_trippers.go:577] HTTP Statistics: DNSLookup 0 ms Dial 0 ms TLSHandshake 2 ms ServerProcessing 191 ms Duration 194 ms
I0309 21:03:22.304135   68957 round_trippers.go:584] Response Headers:
I0309 21:03:22.304145   68957 round_trippers.go:587]     Audit-Id: a2aea110-1807-4822-be1b-77381162437a
I0309 21:03:22.304151   68957 round_trippers.go:587]     Cache-Control: no-cache, private
I0309 21:03:22.304182   68957 round_trippers.go:587]     Content-Length: 1724
I0309 21:03:22.304202   68957 round_trippers.go:587]     Content-Type: application/x-pem-file
I0309 21:03:22.304207   68957 round_trippers.go:587]     Date: Mon, 10 Mar 2025 02:03:22 GM
```
Then it hangs. I even tried creating a port forwarding session (8080:8080) thinking that might work, but it didn't. I don't understand why you need to open port 8080 on the node security group.

**Comment by jicowan** [comment]
I already have a inbound rule for port 8080. It's associated with an application load balancer. I also have a inbound rule that allows all traffic the cluster security group to the nodes in the node group @metalwhale.
