### ISSUE TITLE
Is it time to remove TPR related code from the repo?

### ISSUE THREAD

**Issue by kskewes** [bitnami-labs/sealed-secrets#145]
TPR's were removed in k8s 1.8. Is anyone still running a cluster this old?

Removing TPR would:
- simplify jsonnet via merge of CRD code into the controller-norbac.jsonnet if desired. ~2 lines.
- slightly simplify build (travis, goreleaser)
- slightly simplify installation instructions
- reduce docs when delete migration to CRD guide.

Happy to PR if/when. :)

**Comment by anguslees** [comment]
I would approve such a PR :)

**Comment by kskewes** [comment]
Great, will send this evening and then update GoReleaser PR on this basis.
