### ISSUE TITLE
Activate the golangci-lint gosec linter in the project configuration

### ISSUE THREAD

**Issue by agarcia-oss** [bitnami-labs/sealed-secrets#1459]
**Which component**:
Controller and Kubeseal

**Is your feature request related to a problem? Please describe.**
Activate the `golangci-lint` [gosec linter](https://golangci-lint.run/usage/linters/#gosec) in the project configuration

**Describe the solution you'd like**
We'll need to activate the linter in the [golangci-lint](https://github.com/bitnami-labs/sealed-secrets/blob/main/.golangci.yaml#L232) config and review/fix the issues detected.

**Comment by alemorcuq** [comment]
We've opted to use `gosec` as a standalone binary due to discrepancies between its report and that of `golangci-lint`. In #1460, I've adjusted the default severity to low and addressed the reported issue accordingly. Therefore, I'm marking this issue as resolved.
