### ISSUE TITLE
Program managed sealed secret in GitOps environment (using ArgoCD)

### ISSUE THREAD

**Issue by lanore78** [bitnami-labs/sealed-secrets#1468]
**Which component**:
kubeseal

**Is your feature request related to a problem? Please describe.**
in my situation.

- Currently, we are operating a service that periodically generate bunch of secret manifest files and push it to a git repository.
- And, there is a ArgoCd application that sync the git repository to kubernetes clusters.
- Each secret contains access keys for a customer.
- This got security problem.

So, we just found sealed-secrets and so far we almost finished to apply sealed secret.
Problem is.

- The generated sealed-secret always changed even though the access key doens't changed.
   - We are using kubeseal raw mode to seal.
- This causes ArgoCd events (Synced -> OutOfSync -> Synced), and which make us diffult to distinguish real alert.

**Describe the solution you'd like**
- Provides a encryption options which generate same result with same input.
  - I agree that this could be lower security level, but it may be good options to someone who can take the risk.

**Describe alternatives you've considered**
- Nothing.

**Additional context**
Screen shot of kubeseal raw mode. Results are different with same input
![image](https://github.com/bitnami-labs/sealed-secrets/assets/7918621/0c675cf2-73b8-49a3-8dbc-2051a053720a)

This is our code used to run kubeseal in a java program.
```
public class SealUtils {
    private final static Logger LOGGER = LoggerFactory.getLogger(ManifestGenerationService.class);

    public static String seal(String plainText, String namespace, String secretName, String certPath) {
        String command = "kubeseal";
        String[] arguments = {"--raw", "--cert", certPath, "--namespace", namespace, "--name", secretName};

        CommandLine cmdLine = new CommandLine(command);
        cmdLine.addArguments(arguments);

        InputStream inputStream = new java.io.ByteArrayInputStream(plainText.getBytes());
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

        DefaultExecutor executor = new DefaultExecutor();

        ExecuteStreamHandler streamHandler = new PumpStreamHandler(outputStream, null, inputStream);
        executor.setStreamHandler(streamHandler);

        try {
            executor.execute(cmdLine);
            String result = outputStream.toString();

            return result;
        } catch (ExecuteException e) {
            LOGGER.error("Failed to seal plainText. Exit code: " + e.getExitValue(), e);
        } catch (IOException e) {
            LOGGER.error("Failed to seal plainText(IOException). Exit code: " + e);
        }

        return "";
    }
}
```

**Comment by alvneiayu** [comment]
hi @lanore78 

This is how Sealed Secrets works. When you are generating a Sealed Secrets, during the encryption Kubeseal is generating a random symmetric key used to encrypt (AES-GCM + RSA-OAEP encryption) the secret content generating the encryptedData.

This procedure helps us to improve the security or the strength of the encryptedData. This is why your Sealed Secrets are changing always with the same public certificate and the same secret.

What's we are doing in our clusters? Control if the secrets are changing to generate new Sealed Secrets

I hope that I have clarified your doubts and thanks for contacting us

Álvaro
