### ISSUE TITLE
RBAC rules not working in 0.7.0: Failed to list *v1alpha1.SealedSecret

### ISSUE THREAD

**Issue by jessebye** [bitnami-labs/sealed-secrets#147]
Following the installation steps, after `kubectl create -f https://github.com/bitnami-labs/sealed-secrets/releases/download/$release/controller.yaml` I see the following logged every second or so:

```
E0308 23:42:05.487103       1 reflector.go:205] github.com/bitnami-labs/sealed-secrets/cmd/controller/controller.go:120: Failed to list *v1alpha1.SealedSecret: the server could not find the requested resource (get sealedsecrets.bitnami.com)
```

Running
```
kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.7.0/sealedsecret-crd.yaml
```

resolves the issue.

**Comment by moltar** [comment]
Thanks!

I was also getting the following error, in case anyone Googles:

```
$> kubectl create -f encrypted.json
error: unable to recognize "encrypted.json": no matches for bitnami.com/, Kind=SealedSecret
```

And the above fixes this.

**Comment by anguslees** [comment]
Urgh.  We very recently removed (#146) the support for TPR (k8s <1.7) and "simplified" the installation to a single file. ... Of course that doesn't work until we actually make a release with the simplified yaml file :(

Yay for github's docs-from-master.
