### ISSUE TITLE
kubeseal -v Levels

### ISSUE THREAD

**Issue by dawilliams** [bitnami-labs/sealed-secrets#151]
Version 0.7.0
What are the allow Levels for the -v flag? I'm trying to debug a connection issue and it's not accepting Debug, debug DEBUG etc...

**Comment by mkmik** [comment]
kubeseal and some of the libraries used by it use https://godoc.org/github.com/golang/glog.
The `-v` flag takes a number, which indicates the level of verbosity (the bigger the number, the more detailed logs you'll see).

Keep in mind that by default the logs go to `${TMPDIR:-/tmp}/kubeseal.INFO`. If you want logs of all severity to go to stderr you need to pass `--logtostderr` or `--alsologtostderr`
