### ISSUE TITLE
Templating support for escaping JSON/YAML values

### ISSUE THREAD

**Issue by jfly** [bitnami-labs/sealed-secrets#1534]
**Which component**: controller

**Is your feature request related to a problem? Please describe.**

We use yaml for our application configuration files. These config files end up containing some secrets (such as db passwords), so we use `template.data` (as [documented here][ss templating example]) to inject these secrets.

The problem is that these passwords sometimes contain [indicator characters] such as `"` and `'` which have special meaning to YAML and cannot be trivially injected into a YAML string without escaping ([the documented example][ss templating example] would break too).

Here's the [relevant code in sealed secrets], it just uses go's `text/template` under the hood. Unfortunately, AFAICT, `text/template` does not have a proper way of doing this. Notably, [js/JSEscape does not work].

**Describe the solution you'd like**

Would y'all be open to making the [Sprig function library][Sprig] available here? It has a [toJson function] that would work well for generating both JSON and YAML. This is what ArgoCD provides for templating, see [ArgoCD - Go Template] for details.

I'd be happy to send in a PR adding Sprig if you're open to it.

**Describe alternatives you've considered**

- We could avoid generating passwords with YAML [indicator characters].
- Separate our application configuration from our secrets, as [recommended here][split config from secrets].

[ss templating example]: https://github.com/bitnami-labs/sealed-secrets/blob/v0.26.2/docs/examples/config-template/sealedsecret.yaml#L25
[indicator characters]: https://yaml.org/spec/1.2.2/#53-indicator-characters
[relevant code in sealed secrets]: https://github.com/bitnami-labs/sealed-secrets/blob/v0.26.2/pkg/apis/sealedsecrets/v1alpha1/sealedsecret_expansion.go#L297
[js/JSEscape does not work]: https://github.com/golang/go/issues/37634
[Sprig]: https://masterminds.github.io/sprig/
[toJson function]: https://masterminds.github.io/sprig/defaults.html#tojson-musttojson
[split config from secrets]: https://github.com/bitnami-labs/sealed-secrets/tree/v0.26.2/docs/examples/config-template
[ArgoCD - Go Template]: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/GoTemplate/

**Comment by alvneiayu** [comment]
hi @jfly 

Improve the template always is a good idea. As we answered on #1193 , we are opened to include it.  We are open to receive new contributions and I will be really happy to review it.

Thanks a lot for your time

Álvaro

**Comment by jfly** [comment]
Ah, I hadn't noticed #1193! I've put together https://github.com/bitnami-labs/sealed-secrets/pull/1542 with this change.
