### ISSUE TITLE
Asdf plugin

### ISSUE THREAD

**Issue by stefansedich** [bitnami-labs/sealed-secrets#154]
I have created a plugin (https://github.com/stefansedich/asdf-kubeseal) for [asdf](https://asdf-vm.com/#/) but thought it might be better if we can add it to the bitnami-labs org, I could then add it to the official asdf [plugin list](https://github.com/asdf-vm/asdf-plugins) for better discoverability.

Any interest in doing so?

**Comment by juan131** [comment]
Thank so much for sharing this! 

I'm afraid we don't have bandwidth to maintain this plugin given the current number of maintainers and, therefore, we are not considering adding to the repository.
