### ISSUE TITLE
kubeseal is creating an empty file

### ISSUE THREAD

**Issue by Barsonax** [bitnami-labs/sealed-secrets#1560]
**Which component**:
kubeseal 0.27.0

**Describe the bug**
kubeseal is creating an empty file with no contents

**To Reproduce**
1. Run `kubectl create secret generic mysecret --dry-run=client --from-literal=username=admin -o json > mysecret.json`
2. Run `kubeseal -f mysecret.json -w mysealedsecret.json`
3. `mysealedsecret.json` will be empty

**Expected behavior**
Content in the file

**Version of Kubernetes**:

```
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.6+k3s1
```

**Additional context**
This is on windows 11 (Version 10.0.22631 Build 22631)

kubeseal with --raw does produce output

**Comment by dekayQ** [comment]
Hi @Barsonax  I had the same issue and could resolve it with changing the encoding of the created secret to UTF-8. I had a similar issue with the fetched cert which was also not encoded with UTF-8

**Comment by Barsonax** [comment]
Yeah that seems to fix the problem. So changing step 1 to this will make it work (using powershell):
```
kubectl create secret generic mysecret --dry-run=client --from-literal=username=admin -o json | Out-File -Encoding "UTF8" "mysecret.json"
```

If its not easy to fix this in kubeseal I think it would be fine if kubeseal just gave a descriptive error telling you the encoding needs to be UTF8.

**Comment by Barsonax** [comment]
Bump

**Comment by Barsonax** [comment]
This shouldn't be closed as it's a real issue that has not been fixed yet

**Comment by tadeasbronis** [comment]
This is nor resolved. At least some error message would be helpful

**Comment by alemorcuq** [comment]
@tadeasbronis I created a PR #1580, but it needs to be merged.
