### ISSUE TITLE
Allow overriding hostport when using hostNetwork

### ISSUE THREAD

**Issue by krokofant** [bitnami-labs/sealed-secrets#1596]
**Which component**:
helm controller

**Is your feature request related to a problem? Please describe.**
To avoid port conflict I need to be able to override the container hostPort when hostNetwork is enabled.

**Describe the solution you'd like**
Expose overridable helm fields for hostport.

**Describe alternatives you've considered**
Patching these things via kustomize instead 🙃

**Additional context**

**Comment by alemorcuq** [comment]
When `hostNetwork` is enabled, `hostPort` must match `containerPort`, according to the docs:

```
$ kubectl explain po.spec.containers.ports

[...]
   hostPort	<integer>
     Number of port to expose on the host. If specified, this must be a valid
     port number, 0 < x < 65536. If HostNetwork is specified, this must match
     ContainerPort. Most containers do not need this.
[...]
```

So, for your use case I imagine it's `containerPort` what needs to be overriden? In any case, the chart does not allow to override it, either. I think both `containerPort` and `hostPort` should be configurable in the `values.yaml` file.
