### ISSUE TITLE
Got "tls: failed to verify certificate: x509: certificate signed by unknown authority" when add sealed-secrets to helm repo

### ISSUE THREAD

**Issue by suxiaoxiaomm** [bitnami-labs/sealed-secrets#1615]
**Which component**:
helm chart

**Describe the bug**
when conducting this command `helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets`, I got error 

`Error: looks like "https://bitnami-labs.github.io/sealed-secrets" is not a valid chart repository or cannot be reached: Get "https://bitnami-labs.github.io/sealed-secrets/index.yaml": tls: failed to verify certificate: x509: certificate signed by unknown authority`

**To Reproduce**
Always reproducible

**Expected behavior**
Not such error and add helm repo sealed-secrets no issues.

**Comment by agarcia-oss** [comment]
Hi @suxiaoxiaomm I'm not able to reproduce the issue. The certificate is managed by github.com directly and seems to be valid:

```
Common Name (CN)	DigiCert Global G2 TLS RSA SHA256 2020 CA1
Common Name (CN)	*.github.io
Organisation (O)	GitHub, Inc.
Expires On	Saturday 15 March 2025 at 00:59:59
```
