### ISSUE TITLE
kubeseal package not available 

### ISSUE THREAD

**Issue by bjorns163** [bitnami-labs/sealed-secrets#1658]
Your release mechanism sucks, sorry to say. If you use the example provided in your [README](https://github.com/bitnami-labs/sealed-secrets/blob/main/README.md#linux) in the last 6 months breaks our pipeline twice.

This is because there is a new tag pushed but the packages, in my case `kubeseal-${KUBESEAL_VERSION}-linux-amd64.tar.gz` doesnt exist.  making the download fail.

Hoping to fix this, i switched over to using latest tag as that seemed to be more stable. 

What im using now:
```
# Fetch the latest sealed-secrets version using GitHub API
      KUBESEAL_VERSION=$(curl -s "https://api.github.com/repos/bitnami-labs/sealed-secrets/releases/latest" | jq -r '.tag_name' | sed 's/^v//')

```
But unfortunately 5 days ago a new version was pushed to latest. [This one](https://github.com/bitnami-labs/sealed-secrets/releases/tag/helm-v2.17.0) . To the best of my knowledge, this should have been [v.0.27.3](https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.27.3) as this contains all the packages needed.

It would be greatly appreciated if there is one stable way to use this without having stuff break every time.

**Comment by agarcia-oss** [comment]
Hi @bjorns163 the project uses two types of tags, one for the kubeseal/controller release and another for the helm chart. 

We usually mark the controller as latest but this process failed in the last release. Now it's fixed and you should be able to retrieve the latest release as expected.
