### ISSUE TITLE
No auth provider found for "azure"

### ISSUE THREAD

**Issue by ptemmer** [bitnami-labs/sealed-secrets#168]
```
kubeseal
panic: No Auth Provider found for name "azure"

goroutine 1 [running]:
main.main()
	/Users/travis/gopath/src/github.com/bitnami/sealed-secrets/cmd/kubeseal/main.go:219 +0x3b9
```

Kubeseal version: 0.5.1
AKS k8s version: 1.12.7

With kubeseal version 0.7.0 I'm not seeing the error, however unusable because of https://github.com/bitnami-labs/sealed-secrets/issues/86 and https://github.com/bitnami-labs/sealed-secrets/issues/92

**Comment by mkmik** [comment]
Both blocker issues have been fixed in v0.8.0.
I assume that this issue is no longer relevant. Feel free to re-open it if it is.
