### ISSUE TITLE
Sealed secret for same namespace with same name fails

### ISSUE THREAD

**Issue by raulboquin** [bitnami-labs/sealed-secrets#171]
**Describe the bug**
I have a couple applications in the same namespace: 2 cronjobs, 2 deployments. 

1. All applications use the same secret. 
2. For Cronjob A, I sealed the secret for the first time and called it `name-database-password` with no issues
3. For Cronjob B, I did not seal the secret, I used the same key and name. `kubectl describe` showed me that `name-database-password` was successfully set to the correct password. But `kubectl log` shows the error that the password does not exist in the environment variables. 
4. The same happens for Deployment A (the third application I configured). 

The closest solution I've found has been to change the name of the password in Cronjob B and Deployment A to `pw`. So far that seems to work, but I'm not sure why this issue is happening.

**Comment by chrisharm** [comment]
I don't fully understand your question.  

> All applications use the same secret.

Is there one k8s Secret that each CronJob referenced via a secretRef or is the value of the password the same in each secret?  If they each reference the same k8s Secret, can you share the definitions of the 2 CronJobs?

Sealed secrets are by default scoped to the namespace and secret name, so you cannot use a key/encrypted-value from one secret and use it in another unless you specify either the cluster-wide or namespace-wide annotation on the secret when it's sealed.  

Checkout this issue for some examples: #169

**Comment by vikas027** [comment]
Hey @raulboquin ,

I too stumbled on this. You need to delete the secrets found in this command

```bash
$ kubectl get sealedsecrets.bitnami.com 
```

Deleting from here won't help
```bash
$ kubectl get secrets
```
