### ISSUE TITLE
Proposal: Add Prometheus Metrics

### ISSUE THREAD

**Issue by kskewes** [bitnami-labs/sealed-secrets#177]
We use Prometheus heavily for monitoring applications, clusters and servers.
It would be great if key metrics for Sealed Secrets were available and we could see secret create/update/delete success/failures and alert if need be.

I've started some instrumenting already in [my fork here](https://github.com/kskewes/sealed-secrets/tree/prometheus) after discussing prom metrics on slack a while back.
Be great to confirm if project still open to PR's of this nature and receive any suggestions on preferred metrics and/or implementation.

Assuming all acceptable, my plan is to submit PR's in chunks as follows. 

First phase - [prometheus](https://github.com/kskewes/sealed-secrets/tree/prometheus):
1. Is a bool flag to enable/disable metrics necessary? I personally don't think so.
1. Prometheus http hander
   - `/metrics`
   - `Port: 8080` is default, but shall we use something else to limit Prometheus access to /api endpoints? ([Prometheus wiki port allocation](https://github.com/prometheus/prometheus/wiki/Default-port-allocations))
1. Metrics namespace: `sealed_secrets_controller_`
1. Counters (RE of RED methodology) including tests:
   - Unsealing secrets - the main function of the app: 
`unseal_requests_total{}` and `unseal_errors_total{reason="..."}`
1. `PodMonitor` jsonnet.

Second phase - [prometheus-mixin](https://github.com/kskewes/sealed-secrets/tree/prometheus-mixin):
1. `prometheus-mixin` in similar style to the [`kubernetes-mixin`](https://github.com/kubernetes-monitoring/kubernetes-mixin) - We do this for our apps, so I'm happy to maintain this in a separate repo if preferred. We can still generate a json dashboard for easy Grafana import.
1. dashboard
1. alerts
1. recording rules (if any, not sure yet, may be exercise for user depending on any SLO's).

Third phase:
1. Rebase
1. Counters:
   - Key rotation - A significant regular event that will be happening. 
`rotate_event_count_total{??}` - Count triggered (job) events, could also count keys rotated (add to unseal above?). I haven't had a good think through the recent key rotation commit.
1. Gauges?:
   - `registry_keys_gauge{status="active|compromised|none}`? - Not sure how useful in practice.
1. Histograms (D in RED):
   - Unsealing secrets - time taken to complete task? 
`unseal_request_duration_seconds_bucket{...}`
   - Kube API response times?
1. `/v1/rotate|verify|cert` route wrapping function to generate `http_request` metrics for these endpoints?
1. Docs

**Comment by kskewes** [comment]
Have done a big pass on first and second phases and we're now using them internally.
I've linked branches in my fork that have the changes.
`make controller-servicemonitor.jsonnet` is the way to go.

**Comment by kskewes** [comment]
Given we now have a high rate of changes (great!) I have merged the prometheus-mixin in to the prometheus branch to make it simpler to rebase on master.

Secondly, have redone metrics based on the new k8s events added to Sealed Secrets (success, err unseal, err update).  Labelling not great but this does still give visibility of success/fail.
Proposed CRUD metrics now removed.

**Comment by chancez** [comment]
Any updates on getting those metrics upstreamed?

**Comment by kskewes** [comment]
Have confirmed proposal in Slack and done a quick rebase on master. Once validated in a cluster, added tests, etc will submit PR. Haven't been following project for past few months but we can iterate once initial support is there.

**Comment by riuvshyn** [comment]
@kskewes heya any update on this?

**Comment by ercpereda** [comment]
Is there some documentation of this feature?

**Comment by uhinze** [comment]
Was looking for docs as well, for the time being this is what I figured out:

To enable monitoring with Prometheus Operator, just set serviceMonitor.create=true in values.yaml.

Then the following metrics are available:
![image](https://user-images.githubusercontent.com/25585825/111279072-96227d80-863a-11eb-9705-5d0d2279dd1d.png)

There is also a README here if you don't use the Prometheus Operator, might help: https://github.com/bitnami-labs/sealed-secrets/tree/main/contrib/prometheus-mixin
