### ISSUE TITLE
Fix 0.8.1 Release notes typo

### ISSUE THREAD

**Issue by demisx** [bitnami-labs/sealed-secrets#209]
The installation instructions download link has partial version number. I was going to fix it myself and submit PR, but I can't find where this text is stored.

![Screen Shot 2019-07-31 at 2 56 45 PM](https://user-images.githubusercontent.com/4452412/62251081-868dec80-b3a3-11e9-80db-8930e6eeab4c.gif)

**Comment by mkmik** [comment]
Good catch.
Unfortunately the GitHub release text is currently edited manually in the GitHub release page.
Fixed. PTAL
