### ISSUE TITLE
[Feature Request] One should be able to encrypt using a custom key as well 

### ISSUE THREAD

**Issue by kahootali** [bitnami-labs/sealed-secrets#220]
I am using Sealed Secrets Controller which is quite awesome, only issue is that if I am deploying a new environment, i need to re-encrypt all secrets again using that clusters cert, My suggestion would be that you can give options to encrypt using either of two keys:
- Cluster's cert(Already implemented)
- Custom k8s secret
one needs to create a k8s secret in the cluster, and then can specify a flag to controller to use that secret rather than certificate(default).

It would be beneficial when one needs to create a new environment and have a lot of applications, we would need to create just one k8s secret and run sealed-secrets controller to decrypt using that secret so that the files that are in git repo can be used for any environment

**Comment by mkmik** [comment]
Sealed secrets supports multiple keys.
Just make sure there is a secret labeled sealedsecrets.bitnami.com/sealed-secrets-key=active with the private key and cert (e.g. you can copy it from another cluster) and the controller will pick it up and decrypt any sealed secret encrypted with it

**Comment by alexciouca** [comment]
@mkmik Could you please explain a little bit more how the multiple keys work? I didn't manage to find too much information on this in the documentation. If I have multiple secrets labeled sealedsecrets.bitnami.com/sealed-secrets-key=active which one will be used for decrypting? All of them or just try each of them until one works? And which one of those will kubeseal use to encrypt?

**Comment by mkmik** [comment]
All of them will be used to decrypt. I.e. multiple active keys can coexist.
The latest one (by creation timestamp) is used to encrypt.
