### ISSUE TITLE
Question: How does key rotation not break existing secrets?

### ISSUE THREAD

**Issue by mackenzie-orange** [bitnami-labs/sealed-secrets#222]
I'm currently evaluating sealed secrets for my org.

How does key rotation not break existing secrets? If the sealed secrets are signed with a public key, and that key changes, then those secrets will no longer be decryptable with the new private key. 

Thanks for helping me out. I'm sure there is a simple answer 😄

**Comment by mkmik** [comment]
Key rotation currently only automatically adds new keys, keeping the old keys around so old secrets can be decrypted.

You can reencrypt and existing secret with the latest active key with the `kubeseal --rotate` command. The re-encryption happens sever side and users never get to see the cleartext again.

You can create a bot that periodically creates git commits / PRs
