### ISSUE TITLE
React to deleted secrets by re-creating them

### ISSUE THREAD

**Issue by mkmik** [bitnami-labs/sealed-secrets#224]
Currently when a secret is deleted the controller doesn't do anything until something triggers a new run, which can happen either because there is a change in the sealed secret input or because the controller restarts.

K8s users are used to controllers recreating dependent objects, or at least the deployment->pod relationship sets a precedent.

I think it makes sense for sealed-secrets to re-create deleted secrets because it would do it eventually anyway. If we don't re-create the secret immediately, users might think they deleted the secret only to have it reappear at a random time in the future (e.g. when the controller reboots). This would be a surprising behavior.

A more practical use case is when users delete the secret because something goes wrong (e.g. they change the secret type and the sealed secret controller can perform such an update) and they want to cleanup; at least one such user has reported that the current sealed-secrets controller behavior (to not re-create the secret) is surprising.

**Comment by Crevil** [comment]
I very much agree. Kubernetes is all about declaring what you want and let controllers handle the details. In this case declaring `SealedSecret`s and getting `Secret`s.

**Comment by stevenklar** [comment]
Anyone working on this? For me it's pretty much expected that when the secret is deleted but not the SealedSecret it should recreate the secret of course.

Would give it a shot.

**Comment by mkmik** [comment]
I'm not working on this yet, feel free to take a stab

**Comment by dbyron0** [comment]
Curious if this is still on your radar @mkmik ?  Really looking for a resolution to https://github.com/bitnami-labs/sealed-secrets/issues/288.  Or maybe https://github.com/bitnami-labs/sealed-secrets/blob/master/RELEASE-NOTES.md#allow-overwriting-existing-secrets (https://github.com/bitnami-labs/sealed-secrets/pull/331) means this is already covered?

**Comment by yuha0** [comment]
+1 on this. IMHO, as an operator-like application, the sealed secrets controller should not fire-and-forget. 

As @dbyron0 mentioned, starting from 0.9.7, secret-overwriting is possible, but we are unable to use this feature in an environment where GitOps is enforced:

- The plaintext secret manifest file exists in the git before we deployed sealed secrets.
- Once the controller take over the control of the secret with an sealed-secret object, we would delete the plaintext secret manifest file from git.
- GitOps reacts on the deletion by deleting the secret object from cluster.
- The secret no longer exists until we bounce the controller.

**Comment by mkmik** [comment]
> Curious if this is still on your radar @mkmik ? Really looking for a resolution to #288. Or maybe https://github.com/bitnami-labs/sealed-secrets/blob/master/RELEASE-NOTES.md#allow-overwriting-existing-secrets (#331) means this is already covered?

This issue is a bit different than #288: this is about secrets created by the sealed secrets controller and deleted manually/accidentally ; the idea is that the controller should detect that case and recreate the secret, a bit like when you delete a pod managed by a deployment the deployment controller re-creates the pod resource.

**Comment by mkmik** [comment]
@yuha0 correct. These are two orthogonal issues that happen to be related in practice *if* your devops tooling happens to delete the managed secret when you cleanup your legacy secret after migration.

I think it's important to address this issue anyway, but perhaps a quick solution for your immediate problem would be to figure out how to trick your devops tooling to ignore the secret
 Does it use a labrl to track which objects are garbage? What tool do you use?

**Comment by yuha0** [comment]
@mkmik I am using ArgoCD (https://github.com/argoproj/argo-cd). It can ignore secrets, but we don't want to do that, since migrating all secrets will take some time and we still need it to manage secrets during the process.

It is not super annoying for me to bounce the controller as a temporary workaround.

**Comment by drewboswell** [comment]
I also use ArgoCD, but it doesn't really make a difference what GitOps tool, if any at all we use. It is still a "surprising" behaviour that you need to wait until a reboot for the controller to re-process sealedSecrets.

vs reboots of the controller, in environments like ones I work with we have anywhere between 500-2500 sealedsecrets. When you do a controller reboot it takes 10-45minutes for sealed secrets to complete unsealing. So for us this hack is awkward for production. (unsealing take roughly 0.7s ->1.2 seconds on average).

**Comment by mkmik** [comment]
We clearly need to fix this. Rebooting the controller is a hack. Sealed secrets controller needs to implement a proper controller loop that ensures the desired state matches the actual state.

**Comment by drewboswell** [comment]
The mechanism that populates the work/decrypt queue could be changed to verify the existence of a secret before generating it. This would cover a few scenarios including faster reboots (only decrypt what's needed), periodically detecting missing/missed decrypts and also not have the decrypting solely tied to sealed-secret events.

That reconciliation loop could then be configured to run every x-minutes to avoiod etcd/api-server overload.

**Comment by mkmik** [comment]
perhaps [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) could help with that.

All controllers need to do the same things.
