### ISSUE TITLE
Trouble creating docker-registry secret

### ISSUE THREAD

**Issue by solomson** [bitnami-labs/sealed-secrets#239]
I'm trying the following command

```
kubectl create secret docker-registry SECRETNAME --docker-server=REGISTRYADDRESS --docker-username=USERNAME --docker-password=PASSWORD --docker-email=XXX@yyy.com --dry-run | kubeseal --format yaml --cert secret.pem > SECRETNAME.yaml
```

Just running the first part of the block (before the pipe) works just fine for generating a working secret. However when running the entire block, and describing the generated secret the type is `Opaque`

In the SECRETNAME.yaml file there is a line
`    type: kubernetes.io/dockerconfigjson`

Am I missing something obvious here?

**Comment by mkmik** [comment]
Which version of kubeseal are you using?

**Comment by solomson** [comment]
kubeseal v0.8.1 linux-amd64 running on Win subsystem for Linux
Haven't had issues creating "regular" sealed secrets"

**Comment by mkmik** [comment]
Sorry, I should have asked: which version of the controller are you running?
If kubeseal produces the `type: kubernetes.io/dockerconfigjson` it might be that the controller
doesn't honour it.
You need at least v0.8.0.

**Comment by solomson** [comment]
Ah, the controller app version is 0.7.0.
Thanks
