### ISSUE TITLE
Omit empty status field when generating sealed secret

### ISSUE THREAD

**Issue by mkmik** [bitnami-labs/sealed-secrets#246]
When generating a sealed secret `kubeseal` outputs an empty `status` field:

```
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
....
  "status": {

  }
}
```

It's not causing any problem but it's ugly and confusing and we shouldn't do it if possible.

CC: @atomatt

**Comment by saviogl** [comment]
@mkmik You fixed this issue in this [commit](https://github.com/bitnami-labs/sealed-secrets/commit/408a9c78be33b7d81a16ef19a389939704c84c7d), or did I misunderstand the issue?

**Comment by mkmik** [comment]
I forgot to close this, you're right
