### ISSUE TITLE
YAML secert is always converted into JSON, even when using .yaml as file extension

### ISSUE THREAD

**Issue by MrDienns** [bitnami-labs/sealed-secrets#251]
**Kubeseal version:** 0.8.3 (bottled)
Installed via  Homebrew.

So, every time whenever I use the command;
`kubeseal < my_secret.yaml > my_encrypted_secret.yaml`
it creates a .yaml file with JSON contents.

Considering that the Usage section in the README uses YAML files as example, I would expect that the file contents remain a YAML structure and don't get converted into JSON.

**Comment by mkmik** [comment]
Yeah, that would be nice indeed.

(For the record, you can force the YAML output with `kubeseal --format yaml`)

**Comment by jjo** [comment]
Note that `kubeseal` has no way of knowing the filename when you redirect output (via `> filename`), thus it's a matter of defaults, unless kubeseal had a `-o|--output <filename>` flag.

**Comment by mkmik** [comment]
Would it make sense to output the same format of the input?

**Comment by mkmik** [comment]
(assuming we can reliably detect that)

**Comment by mkmik** [comment]
@MrDienns yeah that's what I meant in https://github.com/bitnami-labs/sealed-secrets/issues/251#issuecomment-530425560.

I don't know, I'm in two minds; would it be a big deal if auto-detection gets it wrong?

**Comment by mvpmvh** [comment]
KISS. Add the ‘-o‘ and scrap the auto-detection. Be explicit about what you want or rely on sane defaults (i.e. json)

**Comment by mkmik** [comment]
anybody feels strongly that the default output format should be switched to YAML?

**Comment by mkmik** [comment]
Or should we just make the `-o|--format` argument mandatory (like kubectl)?

**Comment by jjo** [comment]
> anybody feels strongly that the default output format should be switched to YAML?

Only if very well highlighted as a compat-breaking change, as it may well break
workflows assuming/validating JSON.

**Comment by jjo** [comment]
> Or should we just make the `-o|--format` argument mandatory (like kubectl)?

Unsure really ... as it'd be a must-pass flag (thus bad UX XP) just to get
the most usual use case for kubeseal to work.

**Comment by mkmik** [comment]
... and any valid json is also valid yaml (since we are guaranteed to never emit duplicate keys in json)

**Comment by mkmik** [comment]
> > anybody feels strongly that the default output format should be switched to YAML?
> 
> Only if very well highlighted as a compat-breaking change, as it may well break
> workflows assuming/validating JSON.

@jjo, yeah I would like to avoid breaking this now, but we might have a chance to pick a new behavior if we revamp the CLI UX with proper (sub)commands etc; see #95
It's still not clear to me what the best default here. (I do have my personal preferences but I'm sure everybody has their own; I don't want to force mine)

**Comment by rouke-broersma** [comment]
When I use kubeseal I need the output in a file to place in my git repo. We use YAML for our k8s manifests (doesn't almost everyone?) so I always need the output in YAML format. I also half expected kubeseal to output a file since I input the secret as a file. That it didn't was unexpected to me the first time (because I input from file).

**Comment by mkmik** [comment]
`kubectl -w outputfile.yaml` writes to a file. For backwards compat reason, if you don't provide the flag it will output to stdout.
When redirecting stdout into a file, it cannot see the file extension (since the redirection is done by the shell); please just use the `-w`  flag.

**Comment by rouke-broersma** [comment]
I know, I was just sharing my experience from when I was a new user.
