### ISSUE TITLE
Generating keypair with either OpenSSL or implementing a command

### ISSUE THREAD

**Issue by dcherman** [bitnami-labs/sealed-secrets#258]
Hi,

I'm interested in using sealed-secrets as part of our secrets management strategy, and I'd like to include it as part of our cluster setup instructions.

Since the private key is incredibly important and can't be lost without losing access to all previously included secrets, I want to ensure that by default, it is backed up.

My use case is by using Amazon KMS to encrypt the private key, it becomes safe to commit to git like any other secret, then terraform can take over from there and decrypt the secret during cluster creation which is critical for disaster recovery if the in-cluster key is lost.

To do that, I need to generate the keypair ahead of time.  My proposal is either that we provide instructions with openssl for generating a valid keypair that can be used with sealed secrets, or that we implement a command like

`controller generate-key-pair --private-key tls.key --public-key tls.crt`

Which would use the identical codepath that already exists to create a certificate, but would just output it to files rather than creating secrets in the cluster.

**Comment by dcherman** [comment]
Using KMS to seal the secrets would be fantastic and would absolutely solve my use case in a far simpler way than I was planning.

If that's in the works, then I might just defer until that's released and start using it.

**Comment by mkmik** [comment]
I'm closing this under the assumption that the original answer has been answered.
