### ISSUE TITLE
How do I retrieve a secret post Key rotation 

### ISSUE THREAD

**Issue by judewin-alef** [bitnami-labs/sealed-secrets#262]
As a user, lets say my secret is encrypted using the initial key and lets say I create another secret  post automatic key rotation after 30 days, and at this point if my cluster goes down and comes back up again, and a new key gets created. Both my secrets can't be unsealed. 
How do I retrieve both the secrets and restore the keys (both) and add it to the chain to decrypt the sealed secrets. How would backup and restore work in this case ?

**Comment by judewin-alef** [comment]
@mkmik For instance: 

Jan 1 - secretA created with KeyA
Feb 1 - secretB created with KeyB
Feb 5 - Cluster goes down and comes back up with Key C

How would I unseal Secret(A and B) and how would I restore both the keys and add it to the chain

**Comment by judewin-alef** [comment]
@mkmik - Thanks for answering that. If new keys are generated every 30 days, how would I restore all of them incase of disaster and recovery ?

**Comment by judewin-alef** [comment]
Also does kubeseal retrieve public key automatically from the cluster when its online ?

**Comment by mkmik** [comment]
> Also does kubeseal retrieve public key automatically from the cluster when its online ?

yes

**Comment by mkmik** [comment]
> @mkmik - Thanks for answering that. If new keys are generated every 30 days, how would I restore all of them incase of disaster and recovery ?

backup:
```bash
kubectl  -n kube-system get secret \
  -l sealedsecrets.bitnami.com/sealed-secrets-key=active \
  -o yaml \
  > sealed-secrets-keys-backup.yaml
```

restore:
```bash
kubectl -n kube-system apply -f sealed-secrets-keys-backup.yaml
```

**Comment by mkmik** [comment]
@judewin-alef did this answer your questions?

**Comment by judewin-alef** [comment]
Thanks @mkmik, so it would be able to unseal all the keys, if i restore from active, No matter how many renewals(rotations) it has been through ?

**Comment by mkmik** [comment]
Yes, as long as you backup all private keys used to encrypt all the sealed secrets you have, you'll be able to decrypt them.

Key renewals only **add* new keys, basically making old backups no longer sufficient to decrypt recently sealed values (** by design**). As long as you back up frequently enough you'll be able to perform disaster recovery.
