### ISSUE TITLE
Manifest not compatible with Kubernetes 1.16

### ISSUE THREAD

**Issue by olivierlemasle** [bitnami-labs/sealed-secrets#269]
The manifest used to install Sealed Secrets (https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.9.0/controller.yaml) contains a `Deployment` under API group `apps/v1beta2`, which is deprecated in Kubernetes 1.16, released this week (https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/).

Therefore, the manifest does not work with K8s 1.16:

    error: unable to recognize "https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.9.0/controller.yaml":
    no matches for kind "Deployment" in version "apps/v1beta2"

**Comment by olivierlemasle** [comment]
Cf https://github.com/bitnami-labs/kube-libsonnet/issues/22 and https://github.com/bitnami-labs/kube-libsonnet/pull/23 for the fix in `kube-libsonnet`.

**Comment by mkmik** [comment]
@olivierlemasle thanks; do you happen to know the answer to question in https://github.com/bitnami-labs/kube-libsonnet/pull/23#issuecomment-517720271 ?

**Comment by jjo** [comment]
> @olivierlemasle thanks; do you happen to know the answer to question in [bitnami-labs/kube-libsonnet#23 (comment)](https://github.com/bitnami-labs/kube-libsonnet/pull/23#issuecomment-517720271) ?

FYI I'll be tackling  bitnami-labs/kube-libsonnet#22 tomorrow, already allocated time for that.

**Comment by mkmik** [comment]
Fix released in [v0.9.1](https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.9.1)
