### ISSUE TITLE
Improve error reporting in case of missing kubeconfig when inferring namespace

### ISSUE THREAD

**Issue by mkmik** [bitnami-labs/sealed-secrets#313]
Sealed-secrets need to know the namespace of the secret it's sealing.
It can get the namespace in 3 ways (in order of precedence)

1. from the `-n`|`--namespace` flag.
2. from the input secret's metadata.
3. from the kubeconfig file.

when the kubeconfig file is missing, we currently report a low-level error message from the k8s client library that doesn't help the user know what to do (and gets mistaken for #101)

**Comment by rwhaling** [comment]
thanks for taking a look @mkmik !

**Comment by mkmik** [comment]
releases in v0.9.5
