### ISSUE TITLE
Allow overwriting secrets

### ISSUE THREAD

**Issue by mkmik** [bitnami-labs/sealed-secrets#321]
Proposal:

Check the presence of an annotation sealedsecrets.bitnami.com/managed: "true" ; if true then treat the secret as owned by sealed-secret controller even if there is no ownersReference.

Main use cases:

1. A user wants to install something via kustomize (e.g. argocd) and cannot remove a secret from the base nor re-kind the secret (because it's against kustomize philosophy) 
2. A user wants to be resilient against cascade deletes of their unsealed secrets due to the disappearance of the CRD; the user (somehow, to be defined elsewhere) removes the ownerReferences to avoid the automatic cascade, but then updates of the sealed secrets no longer work.
3. A user has a bunch of legacy secrets and wants to replace them with sealed secrets

**Comment by chiragthaker** [comment]
+ 1 - watching this

**Comment by sfitts** [comment]
We would also like something like this as it would make transition from standard secrets to those being managed by the controller a lot easier (as it is now we have to figure out how to find/remove only those secrets for which a sealed replacement will be created, which is a bit messy).

**Comment by mkmik** [comment]
@sfitts thanks, description updated to include this

**Comment by chiragthaker** [comment]
@mkmik  : Any plan to release this fix soon ?

**Comment by mkmik** [comment]
yes

**Comment by malmuzaini** [comment]
@mkmik @sfitts Can I submit a PR to fix this, or it has been taken care of?

**Comment by mkmik** [comment]
@malmuzaini please do contribute; I didn't start yet

**Comment by malmuzaini** [comment]
@mkmik ok

**Comment by malmuzaini** [comment]
@mkmik The annotation is assumed to be already added, right?
If yes, then what do you think if we make it possible to let the controller add the annotation by passing the option, let say `--add-manged-annotation`, to `kubeseal` command.

**Comment by mkmik** [comment]
this is an option too.

I'd prefer to start with a simpler model where the user has to take an explicit action on the existing objects before sealed-secrets take over ownership of an object (as opposed to providing a way for sealed secrets to "force" its way through)

**Comment by malmuzaini** [comment]
@mkmik ok agreed

**Comment by sfitts** [comment]
@mkmik while I can see the argument for that I was personally hoping for something that could be driven entirely from the sealed secrets side.  As it stands I can already take an explicit action on the existing objects to let the sealed secret take over (namely delete).

The issue there is that in our environment I don't know in advance exactly which sealed secrets might have overlaps and which ones don't.  I want any existing secret that is now covered by a sealed secret to be taken over -- but finding those dynamically, based on what sealed secrets get created is.... challenging (aka it involves more code/scripting than I'm willing to do -- easier to just nuke them all and move on).

**Comment by mkmik** [comment]
If it's easy to nuke them all, wouldn't it be equally easy to just invoke kubectl annotate on all secrets (it's not like an extra annotation will hurt)?

**Comment by sfitts** [comment]
I guess -- was just hoping to avoid the "do something to the secrets first" step in lieu of telling the shared secret controller -- this one is your now, don't worry about what's there.  Just feels cleaner.

**Comment by mkmik** [comment]
Ok. I'm sold

**Comment by mkmik** [comment]
Can we make multiple smaller PRs

**Comment by malmuzaini** [comment]
@mkmik that's the whole point `sealed-secret` controller should take over and manage the existing secret, hence the use of flag comes in to make an option for the user to toggle this behaviour.

But that's not always the case of course. The users should still have some flixibility to explecitly specify the secrets they want to be managed by the `controller`, hence the annotation `sealedsecrets.bitnami.com/managed` comes in.


I will do a PR for the annotation first, and let's have a discuss about the implementation of the flag later.

**Comment by gnunn1** [comment]
I'm running into this with ArgoCD where I have a cluster (OpenShift) that has existing secrets that can be updated to configure operators or cluster configuration. Requiring that the secret be annotated first means I have to add some pre-hook jobs in ArgoCD to annotate the secret which is a bit painful compared to just having the sealedsecret controller just manage it directly.

**Comment by mkmik** [comment]
@gnunn1 the main rationale for the current behavior is security. T secondary reason is footgun protection. Are you happy to weaken those protections? Would you like to be able to configure the controller to not check overwrites?

**Comment by gnunn1** [comment]
I can understand the security rationale particularly as the controller has the ability to overwrite secrets across all namespaces. I guess from your perspective requiring adding an annotation to the original secret provides the trust the requestor is not making the request maliciously similar to the way letsencrypt acme requires you prove you own the domain by inserting a TXT record.

Makes sense from that point of view, I'll have to ponder it some more.

**Comment by mkmik** [comment]
@gnunn1 so if I understand correctly your use case, you have some secrets that are created by some other tool (e.g. created by an operator) and as part of the configuration process of those tools you're meant to overwrite such secrets with your own contents. Is that right?

**Comment by gnunn1** [comment]
When you install an OpenShift cluster it provisions a bunch of things up front. In this particular use case it provisions a prometheus/grafana monitoring stack with the cluster along with a default alertmanager secret. In order to configure alertmanager for additional secrets you need to update that secret. Since I didn't provision the secret in the first place, I need to annotate it so sealedsecrets will override it. If I was updating alertmanager manually, no issue, but when doing GitOps with a tool like ArgoCD I have to deploy a job to annotate it in a pre-sync hook so the sealedsecret controller will overwrite it.

That's the use case I have anyway, like I said previously though I understand the security concerns. Unfortunately I haven't thought of a good way personally to handle the security concerns while still making this easy to do.

**Comment by timbrd** [comment]
> When you install an OpenShift cluster it provisions a bunch of things up front. In this particular use case it provisions a prometheus/grafana monitoring stack with the cluster along with a default alertmanager secret. In order to configure alertmanager for additional receivers you need to update that secret. Since I didn't provision the secret in the first place, I need to annotate it so sealedsecrets will override it. If I was updating alertmanager manually, no issue, but when doing GitOps with a tool like ArgoCD I have to deploy a job to annotate it in a pre-sync hook so the sealedsecret controller will overwrite it.
> 
> That's the use case I have anyway, like I said previously though I understand the security concerns. Unfortunately I haven't thought of a good way personally to handle the security concerns while still making this easy to do.

I have the same problem. I would like to override a default secret which has been provisioned by an operator, but it is not managed by sealedsecrets.

**Comment by Thakurvaibhav** [comment]
@mkmik What is the recommendation around managing secrets which are created by another operator ?

**Comment by mkmik** [comment]
> @mkmik What is the recommendation around managing secrets which are created by another operator ?

Can you please elaborate the scenario with an example?

**Comment by Thakurvaibhav** [comment]
> > @mkmik What is the recommendation around managing secrets which are created by another operator ?
> 
> Can you please elaborate the scenario with an example?

@mkmik Sure. 

When have an application controlled by an operator which creates relevant secrets for it, self signed TLS secrets being one of them.
In order to override that self signed TLS certs we would simply do a `kubectl apply -f new_cert.yaml`  and the application's operator would pick it up and roll it out to any relevant namespaces.
This approach also works when we apply the `new_cert.yaml` using ArgoCD since we would like to roll out cert changes to multiple clusters. However, keeping the `new_cert.yaml` manifest in git is not ideal. Therefore we decided to seal it using sealed secrets. However, whenever the sealed secret manifest is applied sealed secrets controller fails to unseal it and the error log suggests `failed update: Resource "application-tls" already exists and is not managed by SealedSecret`

**Comment by mashail** [comment]
@Thakurvaibhav I guess I understand your use case @mkmik it is what we were discussing in this thread early. We can make the `sealed-secrets` controller take over the exiting by restrictive mode using the annotations which is already implemented. Or permissive mode by configuring the controller to be so.

In the _*restrictive mode*_:`sealed-secrets` controller will overwrite a secret only and only if it's annotated with `sealedsecrets.bitnami.com/managed`.
While _*permissive mode *_ `sealed-secrets` controller will overwrite any secret.

_*permissive mode *_ would be useful for GitOps approach and in less sensitive cases.

**Comment by Thakurvaibhav** [comment]
> @Thakurvaibhav I guess I understand your use case @mkmik it is what we were discussing in this thread early. We can make the `sealed-secrets` controller take over the exiting by restrictive mode using the annotations which is already implemented. Or permissive mode by configuring the controller to be so.
> 
> In the __restrictive mode__:`sealed-secrets` controller will overwrite a secret only and only if it's annotated with `sealedsecrets.bitnami.com/managed`.
> While _*permissive mode *_ `sealed-secrets` controller will overwrite any secret.
> 
> _*permissive mode *_ would be useful for GitOps approach and in less sensitive cases.

@mashail Thank you for the response. 

Using _permissive mode_ is precisely our use case. Is this something which is available right now or planned for future ?

**Comment by mashail** [comment]
@Thakurvaibhav if you were following the thread, that's was a proposal, but it's up to the maintainers. If they see it a valid use case that the sealed-secrets controller should handle it. Then I can take the ownership of it and implement it.

@mkmik what do you think?

**Comment by mhaddon** [comment]
This conversation is good, is there any progress on implementing this?

**Comment by juan131** [comment]
@mkmik isn't this supported since `v0.9.7`?

- https://github.com/bitnami-labs/sealed-secrets/blob/main/RELEASE-NOTES.md#v097
- https://github.com/bitnami-labs/sealed-secrets/pull/331

**Comment by mkmik** [comment]
Yes I forgot to close the issue
