### ISSUE TITLE
Sealed secrets UI

### ISSUE THREAD

**Issue by mkmik** [bitnami-labs/sealed-secrets#326]
<raw dump from a discussion in the k8s channel>

The user opens the sealed secrets UI
and sees a large text box with a skeleton of a k8s Secret resource
and instructions to paste over it an existing unencrypted secret or an already encrypted secret.
Then:

a) if the input is an already encrypted secret skip to step (c)
b) if the input is an plain old k8s unencrypted secret, the UI will encrypt it in-browser via client side version of kubeseal
c) now the large text field contains a valid encrypted sealed secret. the UI now offers a way to further refine it, by adding more items (key/value pairs) or updating existing items. Updating an existing item will cause the UI client to encrypt that value (akin to what `--raw` does).

The UI won't ever decrypt the value, nor in other ways have a privileged channel with the controller other that possibly being a bunch of HTML/JS/WASM files served from it.

**Comment by warmfusion** [comment]
Can the client-side version of kubeseal operate without needing access to the core of the kubernetes cluster? We don't allow anyone to have kubectl or equivalent access to the kubernetes clusters, all deployments are managed via ArgoCD, so having kubeseal as a user-accessible system would be great if we just need to provide access to public keys

**Comment by Crevil** [comment]
Yes it can. We distribute the public key to our developers for offline sealing and it works great.

**Comment by Rayyis** [comment]
I'll take a stab at it.

**Comment by bndw** [comment]
Another approach could be to export [func seal](https://github.com/bitnami-labs/sealed-secrets/blob/93fbf7822abf2d3491007eae2cad997d53908f6a/cmd/kubeseal/main.go#L229) in `kubeseal`. 

My use-case is to provide secret sealing in our internal mgmt ui. If I could import the official Seal function, that would be awesome.

**Comment by revolunet** [comment]
Hi, is there any web UI for this ?

i'd be happy to contribute a static web UI if theres no current initiative.

**Comment by revolunet** [comment]
here's what i found digging this subject : 

 - great explanation of secret encryption process : https://github.com/bitnami-labs/sealed-secrets/blob/master/docs/crypto.md
 - related code : [EncryptionLabel](https://github.com/bitnami-labs/sealed-secrets/blob/946a69eb52f9874fe871d3ce08eb205726380931/pkg/apis/sealed-secrets/v1alpha1/sealedsecret_expansion.go#L77) and [HybridEncrypt](https://github.com/bitnami-labs/sealed-secrets/blob/946a69eb52f9874fe871d3ce08eb205726380931/pkg/crypto/crypto.go#L35)

Maybe one could make this work in a full client-side application with the [Web crypto API](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/encrypt).

Issue #348 may help in a different way by making it possible to create an API that seal secrets

**Comment by revolunet** [comment]
Thanks to the awesome @cberthou we now have a TypeScript implementation for the `HybridEncrypt` method so we can seal client-side in web browsers or NodeJS. 

The implementation is here : https://github.com/SocialGouv/aes-gcm-rsa-oaep

And a demo here : https://38lo8.csb.app/

**Comment by juan131** [comment]
I think we can consider this issue solved with the implementations @revolunet shared
