### ISSUE TITLE
Unable to pull image from quay.io - x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by presidenten** [bitnami-labs/sealed-secrets#332]
I am behind a corporate proxy and get `x509: certificate signed by unknown authority` when I try to pull the image.

Could you please host the sealed-secrets-controller over att hub.docker.com instead of quay.io? It seems like you have most other bitnami images there, so wouldnt it be kind of nice to have them gathered?

```
$ docker image pull quay.io/bitnami/sealed-secrets-controller:v0.9.6
v0.9.6: Pulling from bitnami/sealed-secrets-controller
155814304360: Downloading
5f5edd681dcb: Retrying in 1 second
5161258b3daa: Downloading
x509: certificate signed by unknown authority
```

**Comment by mkmik** [comment]
are you still affected by this issue? I cannot reproduce the issue.

**Comment by presidenten** [comment]
Turns out its our overly protective corporate proxy that has an issue with some root certs. 
So cant reach it from our production machines. 

If it wouldnt be too much of a hassle, it would be nice to have it on docker hub as well, otherwise we can just retag the image and pull it from our own repo.

Im closing the issue, but it would be nice to hear your thoughts wether you could consider moving to docker hub or not.

**Comment by mkmik** [comment]
would gcr.io work for you?

**Comment by blacs30** [comment]
After this quay.io outage today I would like to  ask for a second registry, gcr.io would be fine or docker.io. Which one doesn't matter for me.

**Comment by mkmik** [comment]
Yeah, I'd like to move too. Captured in #413

**Comment by blacs30** [comment]
Was just thinking to create a new issue myself, you were faster. Thanks.
