### ISSUE TITLE
kubeseal should not require a `~/.kube/config` when unsealing secrets when given a key

### ISSUE THREAD

**Issue by joakimnordling** [bitnami-labs/sealed-secrets#341]
`kubeseal --recovery-unseal --recovery-private-key master.key -o yaml < some_secret.yaml` fails with error message `error: invalid configuration: no configuration has been provided` if you don't have a `~/.kube/config` file.

I'd assume the fix would be similar to that of https://github.com/bitnami-labs/sealed-secrets/issues/101

I actually managed to circumvent the problem by just adding the `--cert` option to the command, like this:
`kubeseal --recovery-unseal --recovery-private-key master.key -o yaml --cert secrets.pem < some_secret.yaml`, which apparently triggers the fix from the issue linked above so that the command runs successfully also without the `~/.kube/config` file.

If you're wondering why I need/want to run it like this, without the `~/.kube/config`, the answer is that I've created a CLI tool that wraps this command (and the command for sealing) for ease of use and I want to have tests that verify it's able to seal and unseal the secrets correctly. The tests are of course using a dummy keypair for this purpose and the tests run in an evironment that doesn't have access to any kubernetes cluster.

Experienced with `kubeseal version: v0.9.6`

**Comment by DonMartin76** [comment]
Thank you for fixing this. I was just wondering why this happened to me as well. This otherwise prevents the recovery to actually work... will use the workaround (`--cert` flag) in the meantime. Looking forward to the next release.
