### ISSUE TITLE
Add structured logging

### ISSUE THREAD

**Issue by jnovick** [bitnami-labs/sealed-secrets#343]
Add the ability to do structured json logging via a flag. This will allow the logs in kubernetes to easily be parsed into existing logging infrastructure. This would help with developers to see if their SealedSecret was generated properly. Seeing clear logs is highly beneficial. Currently some logs are almost json, but not quite.

**Comment by mkmik** [comment]
Sounds good to me.

BTW, keep in mind that now sealed secret controller also emits events so you can easily get that info in a structured manner (e.g. kubectl get events or kubectl describe)

**Comment by scaldarola** [comment]
hi @mkmik @juan131  I see that this has been stale for a long time, but I happen to see the same opportunity as the original poster. Is this something you would consider reviewing? 

I could work in a contribution if so
