### ISSUE TITLE
Update status field from sealedsecret

### ISSUE THREAD

**Issue by benjamin-bergia** [bitnami-labs/sealed-secrets#346]
I would like the controller to populate and update the status field of the sealedSecrets that have been created.
Currently when the controller fails to decrypt a sealedSecret or push a secret, the only way to troubleshoot or even realize that something is wrong is to go through the controller logs.

Exposing the status/health of the sealedSecret would simplify troubleshooting but also allow tools that rely on this field for monitoring resources (as ArgoCD for example) to support sealedSecrets.

**Comment by mkmik** [comment]
Good idea!

 Just for the record though: not only the logs, but also the events (see `kubectl describe`)

**Comment by benjamin-bergia** [comment]
@mkmik yeah that's true, my bad.

**Comment by torstenwalter** [comment]
This would help a lot. Sealed secrets are often used in conjunction with tools like ArgoCD. There a status would help as it would allow to add a health check which provides visual feedback if a SealedSecret could not be decrypted.

**Comment by dewe** [comment]
When using Flux CD this could potentially introduce a loop: 

1. Flux applies manifests and create a sealed secret. 
2. The controller unseal the secret and update the sealed secret. 
3. Flux applies the manifests (at sync interval, typically every 5 minutes) which will restore the sealed secret
4. The controller unseal the secret and update the sealed secret again. 
5. Go to 3.

So, please make this optional and turned off by default.

**Comment by torstenwalter** [comment]
@dewe It won't introduce a loop except if you would store the status field in your got repository which you should not do.

Status fields are common in Kubernetes. They are not managed by the user, but updated by the controller which manages an object. Just look at https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#deployment-status
That does not create a loop for flux either. So from my point of view there is no need to make it optional.

**Comment by Crevil** [comment]
Yeah, to my understanding that’s what we get by `kubectl apply`. Flux obly controls the fields you specify in your source repo.

I’d love a status field on the objects. It makes it even simpler for users to understand what is happening to their resources. 🙏

**Comment by dewe** [comment]
Well, then yes, that makes perfect sense. 👍

**Comment by benjamin-bergia** [comment]
Related to @dewe comment, when running kubeseal, the generated sealedsecret contains an empty status field. I am no sure to understand why this is done. As mentioned my understanding is that the status field shouldn't be populated by users but is an internal thing updated by controllers and operators. Currently all my sealedsecrets that are commited on git contain this empty status and I might endup in this loop that @dewe mentioned.

I was expecting kubeseal to generate the same kind of output than kubectl create, so no creationTimestamp and no status.

**Comment by mkmik** [comment]
Perhaps we should bump the schema to v2?

**Comment by akhy** [comment]
+1 👍  also need this for custom resource healthcheck in ArgoCD 

@mkmik adding status won't break schema's backward compatibility, right? 🤔

**Comment by mkmik** [comment]
status update:

I'm working on it.

Our current schema btw already contains a fully working status field; but our controller doesn't make use of it.

This means I can implement it without breaking backward compatibility.

**Comment by akhy** [comment]
@mkmik thanks a lot!

Does it need significant changes in manifests? 
I'm using official Helm chart version 1.8 which still uses controller version 0.10.0, can I just override the image tag to immediately use this fix?

**Comment by mkmik** [comment]
It does need changes to the RBAC rules (update permissions to the status subresource) and thus the helm chart has to be updated

**Comment by mkmik** [comment]
(the release notes always mention when it's safe to just bump the version number or when there have been changes in the manifests)

**Comment by akhy** [comment]
Thanks, Confirmed working! There's a quite significant CPU usage increase although it's still reasonable in our case 👍 

Putting our ArgoCD custom healthcheck here just in case someone need it 

```
data:
  resource.customizations: |
    bitnami.com/SealedSecret:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              if condition.type == "Synced" and condition.status == "False" then
                hs.status = "Degraded"
                hs.message = condition.message
                return hs
              end
              if condition.type == "Synced" and condition.status == "True" then
                hs.status = "Healthy"
                hs.message = condition.message
                return hs
              end
            end
          end
        end

        hs.status = "Progressing"
        hs.message = "Waiting for sync status"
        return hs
