### ISSUE TITLE
Provide multi-arch Container image for sealed secrets controller 

### ISSUE THREAD

**Issue by onedr0p** [bitnami-labs/sealed-secrets#349]
Now that we have armv7 and arm64 binaries built the next step would be to provide a multi-arch Container image. Since quay doesn't support fat manifests (yet) we'd either have to wait for their implementation or switch the container registry to dockerhub.

Related: https://github.com/bitnami-labs/sealed-secrets/issues/173

**Comment by mkmik** [comment]
Implemented in #367

The containers pushed by the next release v0.10.0 will be multi-arch (amd64, armv7 and arm64)

**Comment by alexellis** [comment]
Just landed here. That's awesome - thank you @mkmik
