### ISSUE TITLE
Automation strategy using kubeseal and managing original secrets files

### ISSUE THREAD

**Issue by iamvyom** [bitnami-labs/sealed-secrets#350]
Hi Marko,
 Thanks for your help in  []( https://github.com/bitnami-labs/sealed-secrets/issues/347)

In order to seal the secrets each time the file is which is to be modified, **we need to maintain a local copy (unsealed)
on which kubeseal will work and create sealedsecrets.**

Do you have any thoughts how can we cater this situation in a team with 15+ members and secrets files of multiple environments.?

**Comment by mkmik** [comment]
I'm not sure I understand your problem. Keeping a local decrypted secret defeats the purpose of sealed secrets in the first place. Can you please elaborate on your use-case? Can https://github.com/bitnami-labs/sealed-secrets/blob/master/docs/examples/config-template/README.md help you somehow?

**Comment by iamvyom** [comment]
I may have framed my question bad.

I want to know that since we need to add/delete/ modify the key or values in the secrets regularly,
we need a simple secret yaml/ JSON file in which we can do the same. 
And will use it further to seal it and apply in the cluster

How can we achieve it?
Does kubeseal provide regular unsealing of the sealed secrets too for it?

**Comment by mkmik** [comment]
Are you aware of https://github.com/bitnami-labs/sealed-secrets/blob/master/README.md#update-existing-secrets ? If that's not enough, can you please make a full example of your use case?
