### ISSUE TITLE
Build multiarch docker images for AMD64, ARM64 and ARMv7l architectures

### ISSUE THREAD

**Issue by xUnholy** [bitnami-labs/sealed-secrets#360]
Given my architecture type is armv7l, and Kubernetes is compatible with armv7l architecture I would like to be able to compile sealed secrets for this format.

Ideally, either `--build-args` could be used or alternatively `docker buildx` to compile across platform architecture. 

https://github.com/bitnami-labs/sealed-secrets/blob/b50dbfb5e5d1b844b68b9d593106c92de62d22b1/Makefile#L60

**Comment by mkmik** [comment]
IIRC we don't build the binary as part of the docker image but we only copy it inside the image. Anyway it's trivial to cross-conpile go

**Comment by xUnholy** [comment]
@mkmik correct, seeing that is is trivial, any foresight into when you might compile for the armv7l platform architecture?

**Comment by mkmik** [comment]
Yes.

**Comment by mkmik** [comment]
Duplicate of #349
