### ISSUE TITLE
getting: tty detected: expecting json/yaml k8s resource in stdin

### ISSUE THREAD

**Issue by vrathore18** [bitnami-labs/sealed-secrets#361]
Cloud: AWS(EKS)
How I installed sealed-secrets:

1. `kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.9.7/controller.yaml`
2. I got the key using
`kubeseal --fetch-cert > mycert.pem`
3. created secret
 `kubectl create secret generic mysecret --dry-run --from-literal=foo=bar -o json > mysecret.json`
4. creating sealedsecret
 `kubeseal --cert mycert.pem mysecret.json > mysealedsecret.json`

getting error:
(tty detected: expecting json/yaml k8s resource in stdin)

**Comment by mkmik** [comment]
```
kubeseal --cert mycert.pem <mysecret.json > mysealedsecret.json
```

:-)

**Comment by jotka** [comment]
you are missing -f switch, so it expects the input from the console.
