### ISSUE TITLE
namespace-wide scope does not work

### ISSUE THREAD

**Issue by medmedchiheb** [bitnami-labs/sealed-secrets#374]
After encrypting a secret i tried to apply it to different namespaces,
but seems not working, then i added `cluster-wide`. and it works 
but when i changed to `namespace-wide` it does not work.

  `sealedsecrets.bitnami.com/namespace-wide: "true"` > Not working.

`controller-version`: 0.9.7

`kubernetes: 1.15.7 `

**Comment by mkmik** [comment]
"cluster-wide" means "valid in all places inside the whole cluster".

"namespace-wide" means "valid in all places inside a given namespace".

The namespace-wide scope allows you to change the *name* of a secret *within* the namespace it has been sealed for.
