### ISSUE TITLE
offline decrypt raw string

### ISSUE THREAD

**Issue by vinhut** [bitnami-labs/sealed-secrets#390]
Raw encrypt operation should be reversible, eg :
```
echo "< encypted raw text>" | kubeseal --cert bundle.pem --recovery-unseal --recovery-private-key bundle.pem --raw  --from-file=/dev/stdin --scope cluster-wide
...
<plain output>
```

**Comment by volodyad** [comment]
Hello, 
any updates on this? would be great to have this feature

**Comment by juan131** [comment]
This is already supported, see https://github.com/bitnami-labs/sealed-secrets#can-i-decrypt-my-secrets-offline-with-a-backup-key

**Comment by david0** [comment]
Afaik this issue is about **raw** strings, while the FAQ is about YAML/JSON files.

`--raw` with `--recovery-unseal ` does not seem to work:
```
echo "aaa" |kubeseal --namespace my --controller-namespace my --raw --scope namespace-wide --recovery-unseal
error: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```

**Comment by PKatBK** [comment]
is there any update on this? also ran into the issue
