### ISSUE TITLE
"kubeseal --raw --scope cluster-wide" requires namespace

### ISSUE THREAD

**Issue by codecontemplator** [bitnami-labs/sealed-secrets#393]
I would expect the following to work

```bash
echo -n secretText| kubeseal --raw --from-file=/dev/stdin --scope cluster-wide --cert mycert.pem
```
but it responds with 

```bash
error: invalid configuration: no configuration has been provided
```

Adding a namespace fixes the problem.

```bash
echo -n secretText | kubeseal --raw --from-file=/dev/stdin --scope cluster-wide --cert mycert.pem --namespace something
```
I do not see why a namespace is required when scope is cluster-wide.

**Comment by abdennour** [comment]
we are providing an elegant wrapper for kubeseal CLI if you are using it with RAW option : https://github.com/ElmCompany/seal-cli
