### ISSUE TITLE
scope is not stored as annotation when set to default/strict

### ISSUE THREAD

**Issue by ghostsquad** [bitnami-labs/sealed-secrets#399]
I noticed that when the scope is set to the default (strict) the annotation isn't added to the sealed-secret. Though I understand that this isn't necessarily a bug, as far as usability/readability goes, I think it makes sense to explicitly call out the expectation instead of allow users to implicitly assume.

**Comment by ghostsquad** [comment]
I'd be happy to contribute to this, but I'd like confirmation that this change is desired. Thanks in advance.

**Comment by mkmik** [comment]
Adding the effective scope even if it's the default one would really help users learn about scopes!

However let's do this after #391

**Comment by juan131** [comment]
To be implemented at #391
