### ISSUE TITLE
Cant configure controller with environment variable

### ISSUE THREAD

**Issue by presidenten** [bitnami-labs/sealed-secrets#400]
I  set the SEALED_SECRETS_KEY_RENEW_PERIOD period to update every day to verify that it works. But no new keys have been generated for two days now.

This the `env` set on the deployment:

```
$ k -n kube-system get deployments.apps sealed-secrets-controller -o yaml | grep -A 2 -i 'env:'
        env:
        - name: SEALED_SECRETS_KEY_RENEW_PERIOD
          value: "1"
```

**Comment by mkmik** [comment]
> The value field can be given as golang duration flag (eg: 720h30m).

**Comment by mkmik** [comment]
E.g. set it to 30m of you want to test.

In production this should not be set too frequently. A 30 day period is a good tradeoff

**Comment by presidenten** [comment]
Ahhh ok! I missed that detail. Thanks!

But a `0` is till valid syntax to disable key renewal?

**Comment by presidenten** [comment]
Not a bug, it works with the correct syntax. So closing the issue.

**Comment by mkmik** [comment]
Yes. Also I think the controller logs the key renewal period and/or whether it is disabled. 

If not, let me know, as we should fix it in that case

**Comment by presidenten** [comment]
It dont seem to type it out (or Im missing it), but the config works, so Im a happy camper. Thanks!
