### ISSUE TITLE
kubeseal first time user: missing initial setup docs / misleading errors

### ISSUE THREAD

**Issue by FauxFaux** [bitnami-labs/sealed-secrets#402]
The docs suggest using:

```
% kubeseal --fetch-cert
error: invalid configuration: no configuration has been provided
```

or: `kubeseal --cert https://your.intranet.company.com/sealed-secrets/your-cluster.cert`, which I interpreted as `http://localhost:8001/sealed-secrets/${HOSTNAME}.cert`:

```
% kubeseal --cert http://localhost:8001/sealed-secrets/foo.cert
(tty detected: expecting json/yaml k8s resource in stdin)
error: cannot fetch "http://localhost:8001/sealed-secrets/foo.cert": 404 Not Found
```

I eventually guessed, after reading the entire `--help` output, that it wanted an explicit specification of `--server`, which makes the docs work?

```
% kubeseal --server http://localhost:8001/ --fetch-cert                  
-----BEGIN CERTIFICATE-----
MIIduckCAduckwIBduckALSTduck/WHpSduckXeofjduckYJKoduckcNAQduckAw
...
```

Please document where (`~/.kube/config`?) to set this url.
Please provide initial setup instructions that will work for anyone(?).
Please improve the error message to explain *what* config is missing and where one might set this config (I still don't know!).
Please consider defaulting `--server` to http://localhost:8001/

I do not have a `~/.kube/config`; I only use `kubectl` for microk8s locally, and must ssh to our main deployments.

 ---

```
% kubeseal --version # binary from github
kubeseal version: v0.12.1+dirty
```

ubuntu focal (amd64)

**Comment by mkmik** [comment]
> Please consider defaulting --server to http://localhost:8001/

I guess this would handle the microk8s case; which other cases would this handle?

**Comment by FauxFaux** [comment]
localhost:8001 is the `kubectl proxy` default (I believe), so it would cover anyone who accesses k8s via. the proxy, instead of having direct network access to the API? Which I believe is everyone?

**Comment by mkmik** [comment]
but if you run the `kubectl proxy`, wouldn't you have your config in the `KUBECONFIG` env or `~/.kube/config` files?

(I'm not against setting a reasonable default, in principle; just trying to better understand the scenario)

**Comment by FauxFaux** [comment]
To be honest, I have only used microk8s and GKE.

microk8s doesn't require `KUBECONFIG` or `~/.kube`, it (by some mechanism I do not know) apparently loads the server url from `/var/snap/microk8s/current/credentials/client.config`, and knows how to do that. It will tell you a server, but that's authenticated:
```
% microk8s.kubectl config view | fgrep server:
    server: https://127.0.0.1:16443
% curl -sk https://127.0.0.1:16443 | jq -c
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
```

`microk8s.kubectl proxy` presumably loads this config too.

GKE does actually have `~/.kube/config` on our ssh targets, which I've never set or fiddled with myself, it does it itself.

I'm starting to understand that most k8s users have `~/.kube/config` setup already, and/or they configured it themselves, and `kubeseal` just reads that? Okay!
