### ISSUE TITLE
--merge-into will set the file as read-only in Windows 10 platform

### ISSUE THREAD

**Issue by jfazzini** [bitnami-labs/sealed-secrets#407]
#### Problem
Hi,
I'm trying to run **kubeseal** in a windows host from the command line using a very simple script. When running the first **--merge-into** command it will set the output file as read-only. That will lead to an immediate _Access is Denied_ error from the following command.

#### Script
```
kubectl create secret generic secrets --dry-run -o json --namespace=dev --from-literal=KEY_1=VALUE_1 | kubeseal --format yaml > sealedsecrets.yaml
kubectl create secret generic secrets --dry-run -o json --namespace=dev --from-literal=KEY_2=VALUE_2 | kubeseal --format yaml --merge-into sealedsecrets.yaml
kubectl create secret generic secrets --dry-run -o json --namespace=dev --from-literal=KEY_3=VALUE_3 | kubeseal --format yaml --merge-into sealedsecrets.yaml
```

#### Kubeseal Versions Checked / File Permission
- v0.12.2 / 444
- v0.12.1 / 444
- v0.12.0 / 444
- v0.11.0 / 444
- The issue was not found in previous versions, like v0.10.0, file permission maintained as 644.

#### Windows Version
- Windows 10 Pro Version 1903 Build 18362.778

#### Notes
It seems that this is related to the GoLang function `ioutil.writefile` used at https://github.com/bitnami-labs/sealed-secrets/blob/3812eab5a65de5ef3c4963ac13a35e59e0f24a56/cmd/kubeseal/main.go#L438
Maybe a change in that language? 
Please let me know if I can help with anything else. ;)

**Comment by mkmik** [comment]
possibly related https://github.com/golang/go/issues/38225
