### ISSUE TITLE
Go lang bug causes controller to CrashLoopBackoff

### ISSUE THREAD

**Issue by cyrilcros** [bitnami-labs/sealed-secrets#411]
I updated to Ubuntu 20.04, and with SealedSecrets v0.12.3 / v0.12.1 I kept seeing CrashLoopBackOff errors from the controller.
The relevant part of the controller logs starts here:
```
runtime: mlock of signal stack failed: 12
runtime: increase the mlock limit (ulimit -l) or
runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
fatal error: mlock failed

runtime stack:
runtime.throw(0x139a45f, 0xc)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/panic.go:1112 +0x72
runtime.mlockGsignal(0xc00020b080)
```
My kernel is `5.4.0-29` - and by the way this what ubuntu currently ships - it seems to be related to this go-lang issue: https://github.com/golang/go/issues/37436

Please consider updating your docker image go version to 1.14.2 or above. Thanks!

PS: I will add the controller still kind of works, it fails after a seemingly random amount of time.

**Comment by mkmik** [comment]
Rebuilt with Go 1.14.3 and released in https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.12.4

Closing this issue optimistically, please reopen if it's still a problem.
