### ISSUE TITLE
Unable to retrieve signing certificate from path /sealed-secrets/v1/cert.pem

### ISSUE THREAD

**Issue by robincher** [bitnami-labs/sealed-secrets#418]
Hi !

Just wondering if anyone encountered the same issued when attempting to retrieve cert.pem ? I am hitting 404 error and it seems like the path is not found.

![Screenshot 2020-06-16 at 2 38 18 PM](https://user-images.githubusercontent.com/328109/84739935-126e2e80-afdf-11ea-9fc4-ae7fe2651793.png)

Trying to hit the service via internal Kubernetes route

```
* Connection #0 to host sealed-secrets-controller.secret-management.svc.cluster.local left intact
/usr/src/app # curl -s http://sealed-secrets-controller.secret-management.svc.cluster.local:8080/sealed-secrets/v1/cert.pem
404 page not found
```

Interestingly, the cert seems to be generated when the controller started..

<img width="1072" alt="Screenshot 2020-06-16 at 2 33 47 PM" src="https://user-images.githubusercontent.com/328109/84739534-64fb1b00-afde-11ea-85c6-4e556e34a7f3.png">

I understand that typically, the certificate is made available at: <cluster-endpoint>/sealed-secrets/v1/cert.pem

My environment/version
AWS EKS : 1.16
Sealed-secrets : v0.12.4
Installed via Deployment manifest

I did another test from my local machine minikube, i get the same  timeout 404 error when trying a curl from a testing pod to sealed-secrets

```
usr/src/app # curl -vs http://sealed-secrets-controller.kube-system.svc.cluster.local/sealed-secrets/v1/cert.pem
*   Trying 10.101.230.217:80...
* TCP_NODELAY set
* connect to 10.101.230.217 port 80 failed: Operation timed out
* Failed to connect to sealed-secrets-controller.kube-system.svc.cluster.local port 80: Operation timed out
* Closing connection 0
```

**Comment by mkmik** [comment]
somewhere.com is just an example domain. (Note to self: clarify that in the docs)

**Comment by robincher** [comment]
@mkmik yeah, that my own EKS hostnames, and i deliberately type in somewhere.com :)

I think we can close this issue, somehow i am now able to retrieve the certificate via the endpoints after nearly 1 hour.  All good right now.

**Comment by robincher** [comment]
<img width="885" alt="Screenshot 2020-06-16 at 3 49 36 PM" src="https://user-images.githubusercontent.com/328109/84746736-fe2f2f00-afe8-11ea-800e-952f1d3e4814.png">

Now its downloading internally too

**Comment by mkmik** [comment]
Sorry the screenshot confused me.

**Comment by mkmik** [comment]
This kind of issues with the proxy are sadly quite common. I never managed to reproduce them though. 

The current roadmap is to just move the cert into a configmap which is easier to deal with.

**Comment by robincher** [comment]
No worries, just showing you that the cert.pem is downloadable now

I guess sometimes there are constraints imposed by the environment that we never know of. I will proceed to close this issue thanks.

**Comment by mkmik** [comment]
thanks for reporting!
