### ISSUE TITLE
[helm chart] Chart uses the wrong Service name by default.

### ISSUE THREAD

**Issue by rally25rs** [bitnami-labs/sealed-secrets#424]
Sorry if this is the wrong place to post this issue; I didn't see another place to post issues against the helm chart itself...

The chart defaults the `Service` name to:

https://github.com/helm/charts/blob/master/stable/sealed-secrets/templates/service.yaml#L5
```
name: {{ template "sealed-secrets.fullname" . }}
```

Which is

```
{{- define "sealed-secrets.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}
```

Which by default will use the `.Chart.Name`, which is `sealed-secrets`, which is wrong. The client tool `kubeseal` looks for `sealed-secrets-controller`

-----

As a workaround you _should_ be able to use the `kubeseal --controller-name` parameter to target `sealed-secrets`, but I can't seem to find the right syntax for that to work 🤷‍♂️ 

```
$ kubeseal <secrets.yaml >sealedsecrets.yaml --controller-name sealed-secrets
error: yaml: line 28: could not find expected ':'

$ kubeseal <secrets.yaml >sealedsecrets.yaml --controller-name sealed-secrets:http
error: cannot fetch certificate: invalid service request "http:sealed-secrets:http:"

$ kubeseal <secrets.yaml >sealedsecrets.yaml --controller-name sealed-secrets:8080
error: cannot fetch certificate: invalid service request "http:sealed-secrets:8080:"
```

**Comment by mkmik** [comment]
> Sealed Secret helm charts can be found on this link. It's maintained independently and it might lag a bit behind the latest release. This badge should indicate the latest helm chart release:

https://github.com/helm/charts/tree/master/stable/sealed-secrets

could you please report this issue in the helm chart issue tracker?

**Comment by rally25rs** [comment]
Moved to https://github.com/helm/charts/issues/22996

**Comment by stove-panini** [comment]
Now that the helm/charts repo has been deprecated and the chart is being hosted by Bitnami, I think this should be reopened. The naming issue is still present as of chart version 1.13.2

Currently, you can get around it by passing `--set nameOverride=controller` to the helm install command.
