### ISSUE TITLE
How to use the Prometheus mixin and what is it

### ISSUE THREAD

**Issue by BertelBB** [bitnami-labs/sealed-secrets#426]
I noticed that as of v0.12.1 Prometheus support has been added as a mixin.
There is no documentation about this in the Readme and the mixin itself isn't exactly helpful.

From looking at the [Makefile](https://github.com/bitnami-labs/sealed-secrets/blob/master/contrib/prometheus-mixin/Makefile) I can see that it is generating `yaml` files, which I guess the user will have to apply to a cluster with whatever process they are using to do that.

Also I would like to point out that communicating things like
```
Here is this thing, to learn how to use it I refer you to this external documentation, figure it out.
```
is a terrible user experience. 

So my questions are
- What is it doing?
- How do I use it?
- Do I add prometheus annotations to the `sealed-secrets` deployment and if so what annotations?

**Comment by kskewes** [comment]
Thanks for opening this issue.
Agree the docs are light and appreciate suggestions here and on Slack.
Will take another pass at it. :)
