### ISSUE TITLE
[question] Support for hosted k8s offerings?

### ISSUE THREAD

**Issue by soukron** [bitnami-labs/sealed-secrets#431]
Not sure if I have missed something in the documentation, but is there any way to use sealed secrets in a given namespace without cluster-admin privileges? With the arise of the hosted k8s offerings it would be great to use sealed secrets in them where users normally lack of cluster-admin privileges.

**Comment by mkmik** [comment]
it's supported but sadly not very well documented.

Feature requested in #324 and implemented in #380 

Basically you have to pass `--all-namespaces=false` to the controller.

(https://github.com/bitnami-labs/sealed-secrets/blob/ad3e7ecbd03d8d345db202129e0081282b614ce5/cmd/controller/main.go#L49)

All flags can also be set with environment variables, so `SEALED_SECRETS_ALL_NAMESPACES=false`.

You can set this field using `kustomize`. Let me know if that works for you.

**Comment by mkmik** [comment]
(BTW, that's also why we release the `controller-norbac.yaml` file; as you might not have rights to create the cluster roles etc)

**Comment by soukron** [comment]
Oh, that's great but unfortunately I forgot that the CRD must be created by a cluster admin :( 

Thanks anyway, this project is awesome.

**Comment by mkmik** [comment]
damn crds...

**Comment by mkmik** [comment]
but still a cluster admin might be willing to install a crd but not to run some controller clusterwide

**Comment by soukron** [comment]
Hopefully" Thanks anyway. I'm closing the request.
