### ISSUE TITLE
Missing condition metrics on v0.12.5?

### ISSUE THREAD

**Issue by eyalzek** [bitnami-labs/sealed-secrets#441]
According to the changelog and commits on v0.12.5 (https://github.com/bitnami-labs/sealed-secrets/commit/db6db3eb474f17ae4a1fbe5ce7f8fb2e93ccbc79) I expected there to be metrics about condition of the sealed secrets, though I'm seeing none of them:

```bash
$ curl -s localhost:8080/metrics |grep sealed_secrets
# HELP sealed_secrets_controller_build_info Build information.
# TYPE sealed_secrets_controller_build_info gauge
sealed_secrets_controller_build_info{revision="v0.12.5+dirty"} 0
# HELP sealed_secrets_controller_unseal_errors_total Total number of sealed secret unseal errors by reason
# TYPE sealed_secrets_controller_unseal_errors_total counter
sealed_secrets_controller_unseal_errors_total{reason="fetch"} 0
sealed_secrets_controller_unseal_errors_total{reason="status"} 0
sealed_secrets_controller_unseal_errors_total{reason="unmanaged"} 0
sealed_secrets_controller_unseal_errors_total{reason="unseal"} 0
sealed_secrets_controller_unseal_errors_total{reason="update"} 0
# HELP sealed_secrets_controller_unseal_requests_total Total number of sealed secret unseal requests
# TYPE sealed_secrets_controller_unseal_requests_total counter
sealed_secrets_controller_unseal_requests_total 53
```

From my understanding of the code it should register a metrics for each unsealed secret.. Is this code actually included in `quay.io/bitnami/sealed-secrets-controller:v0.12.5` or did I misunderstand how that's supposed to work?

**Comment by mkmik** [comment]
the code should have been included in v0.12.5
I need to doublecheck why it's not working as intended

**Comment by eyalzek** [comment]
> You have to opt-in for status update by passing the `--update-status` flag to the controller, which is still in beta.

Awesome, it works. Should probably be documented somewhere... Are there any other side effects to enabling this? Or is this the only feature behind this flag at the moment?

**Comment by eyalzek** [comment]
I also might have noticed an issue now, where the condition is not updated on the first "loop" but only on the next one after a sealed secret is processed.
