### ISSUE TITLE
Restoring master key is not working

### ISSUE THREAD

**Issue by Jojoooo1** [bitnami-labs/sealed-secrets#442]
Version: v0.12.5
Provider: gke
Steps to reproduce:

- kubectl get secret -n kube-system -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml >master.key
- create new cluster
- kubectl apply -f master.key
- kubectl delete pod -n kube-system -l name=sealed-secrets-controller

`2020/08/04 22:06:56 Updating kube-system/gcr-json-key`
`2020/08/04 22:06:56 Error updating kube-system/gcr-json-key, giving up: no key could decrypt secret (.dockerconfigjson) E0804 22:06:56.498651 1 controller.go:200] no key could decrypt secret (.dockerconfigjson)`
`2020/08/04 22:06:56 Event(v1.ObjectReference{Kind:"SealedSecret", Namespace:"kube-system", Name:"gcr-json-key", UID:"a3062a58-29f5-4456-aa7a-8c17756a67b2", APIVersion:"bitnami.com/v1alpha1", ResourceVersion:"4629", FieldPath:""}): type: 'Warning' reason: 'ErrUnsealFailed' Failed to unseal: no key could decrypt secret (.dockerconfigjson)`

**Comment by mkmik** [comment]
Hi. Why did you close the issue?

**Comment by Jojoooo1** [comment]
It was actually something wrong on my part. A misconfigured namespace.
