### ISSUE TITLE
Unable to send logs to Humio

### ISSUE THREAD

**Issue by m477r1x** [bitnami-labs/sealed-secrets#452]
Hello, we are using cloud hosted humio for log agregation and the banzaicloud logging operator for transport of logs. we are trying to have logs sent from a kubernetes pod or pods to multiple humio repositories. We already have a working machanism and I have tried to copy this ClusterOutput and designate a different Humio repository and ingest token but it is not working. I was wondering if I am missing anything? Here is the configuration of the logging operator which is use kubernetes secrets as to store the ingest tokens for the Humio repositories. The first ClusterOutput works, but the second one does not seem to be sending any data to the Humio repo. 

```---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: k8s
  namespace: logging
spec:
  loggingRef: k8s
  outputRefs:
  - logging-k8s-humio
  match:
  - select: {}
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: logging-k8s-humio
  namespace: logging
spec:
  loggingRef: k8s
  elasticsearch:
    host: cloud.humio.com
    port: 9200
    scheme: https
    ssl_verify: true
    ssl_version: TLSv1_2
    user: humio-repository-1
    password:
      valueFrom:
        secretKeyRef:
          name: humio-token-1
          key: token
    logstash_format: true
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: logging-k8s-humio
  namespace: logging
spec:
  loggingRef: k8s
  elasticsearch:
    host: cloud.humio.com
    port: 9200
    scheme: https
    ssl_verify: true
    ssl_version: TLSv1_2
    user: humio-repository-2
    password:
      valueFrom:
        secretKeyRef:
          name: humio-token-2
          key: token
    logstash_format: true
```

**Comment by mkmik** [comment]
Did you intend to post this issue in the Sealed Secrets project issue tracker or was it meant for some other project?

**Comment by m477r1x** [comment]
My apologies, i was on multiple repos at the time and ive posted this in the wrong place. it can be closed.

**Comment by mkmik** [comment]
No problem
