### ISSUE TITLE
Annotations/Labels missing in sealed secrets resource metadata

### ISSUE THREAD

**Issue by BlauerPulli** [bitnami-labs/sealed-secrets#460]
Pipe a secret into kubeseal results in a sealed secrets resource without any annotations/labels at sealedsecrets.metadata.labels /sealedsecrets.metadata.labels.

Expected:

```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  annotations:
    app: my-app # used from secret.metadata.annotations
  labels:
    app: my-app # used from secret.metadata.labels
  name: my-token
  namespace: my-namespace
spec:
  ... # the rest is fine
```
The missing labels in particular prevents me from applying sealed secrets objects with kubectl + labelselector option (whats also needed for whitelist pruning).

**Comment by mkmik** [comment]
What version of kubeseal are you using?

This should work, see https://github.com/bitnami-labs/sealed-secrets#sealedsecrets-as-templates-for-secrets

**Comment by mkmik** [comment]
```
$ cat /tmp/mysecret.yaml
apiVersion: v1
data:
  foo: Zm9vCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: mysecret
  labels:
    foo: bar
  annotations:
    ann: nna
$ kubeseal </tmp/mysecret.yaml -o yaml

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: gsdemo
spec:
  encryptedData:
    foo: AgBNu2oMVNU/UU............
  template:
    metadata:
      annotations:
        ann: nna
      creationTimestamp: null
      labels:
        foo: bar
      name: mysecret
      namespace: gsdemo
```

**Comment by BlauerPulli** [comment]
hey @mkmik,
thx for the answer! I'm working with the v0.12.5 release and what you described works, indeed. Be so kind and read my question again.. i talked about to expect the labels/annotations at **sealedsecrets.metadata.labels/annotations**, too (not only at sealedsecrets.spec.template.metadata.labels/annotations)

**Comment by mkmik** [comment]
By design we don't automatically populate the labels from the secret into the sealed secrets

**Comment by mkmik** [comment]
Just edit the file and paste the metadata you want.

Subsequent encryption with --merge will preserve top level labels and annotations

**Comment by BlauerPulli** [comment]
yeah, i already fixed this for me before creating the issue- but with the assumtion that it's a temporarely workaround.
why is my expectation of kubeseal behaviour against the design? i not yet saw that it breaks any existing or planned pattern? 🤔

**Comment by mkmik** [comment]
`kubeseal` is used to "import" a Secret and create a SealedSecret out of it.
The sealed secrets controller performs the inverse and creates a Secret out of a SealedSecret.

That said, Secrets and SealedSecrets are different resource kinds. You can think of a SealedSecret as a "secret factory".
Thus, it's not technically correct for such an import tool to blindly inherit the labels and annotations that belong to the Secret resource. We tried to follow the same pattern as Deployment resources have w.r.t Pods: the `spec.template` subtree contains all you want to say about the "generated resource".

There are other workflows, for example a SealedSecrets resource can also be created manually by crafting the YAML and inserting values manually encrypted with `kubeseal --raw`. Once the SealedSecrets resource is checked in into your version control system, that should be your main resource that represent the secret; you shouldn't have to run kubeseal again unless you need to change or add an item. For example we deliberately didn't add a functionality to kubeseal to delete an item; k8s resources are just text and that should be the main "UI".

I'm saying all that because I had the impression that your want an automated workflow where you can run kubeseal to automatically encrypt the result of some template expansion, which contains some "app" labels, shared with all the other resources. If that's the case, I'd like to hear more about your workflow

**Comment by BlauerPulli** [comment]
Thank you very much for explanation! I understand your points and they are totally fair.

I also considered the approach with replacing the secret template with a sealedsecrets template in the helm-chart and inserting the result of `kubeseal --raw` there.. but this kubeseal feature is experimental so i decided to use kubeseal on the "conventional" way (and i also couldn't estimate if i will face problems because i not found any explanations/information why this is just experimental)

According to my workflow:
Your're right its many automated deployment pipelines that
-  collect some configuration
-  render a helm-chart
-  separate the resulting yaml stream, pipe every secret into kubeseal and merge them with the other (non-secret) resources again. (unfortunately kubeseal recognizes just a single secret on the very top of a k8s manifest). At this point i already working directly on the sealed secret resources and can easily add the labels i missed
-  push the whole thing into a vcs
-  deploy

**Comment by mkmik** [comment]
> unfortunately kubeseal recognizes just a single secret on the very top of a k8s manifest)

Luckily we have already a task for that: #114

**Comment by gimpiron** [comment]
This can be very usefully actually, especially for argocd solution;
`
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-secrets
  namespace: default
spec:
  encryptedData:
    mysql_password: AgBwo33P0cpDAM3qymxkQ6mz71kxo2SbWKthDHctl5dFB4jjhKMAoWfjep6aPg1BrREFL+RCRsYvHPE80DH4lWWmDQfLGz7ND/wS6e04O6DThP5EO22SCtYsFLlpyUtH4huERn/ou0Qv0h6FyotSBsZCt0UuW0giu2rXE3PP4icPbVzbgA+Rq1Im6IAvEZFXUH+5vePpNvmcl5eRnJdK3mXbcATt+ExdNVd2X3/qxenbE9K2cYx1qDXt8/OLtTSsuMdpMMWAwu6TAwVadgYvj4TwJHZmyvD7x9Qg24TctbRrqP+eTkGQVTLlPv5ABlLLXFD+/4crkmTF7JgofMdqg+1KFJfXMYO6DQ+iiPyKb7D6AJemzoWXvE/gvAkTHf74nSTGs3emUXsAjY1yHPRodYiKY2En/XvHnt5omoefiwalo5Hl8EzRixkzU19qwI71d9mYRJEOZC9BFN+6ZclQ5bHKUdkEH8erzJQUHKvwnPfqRkp7DVy8VjSzA4NZBkvKyHUEChMsNrAxIy6p2Ek6NbHMSyuwxxBMxZfepi86NDXlbV1l5yC23RIn/iVLdeuDMpzws7LRrpfg/xGzo1gu62dQ3P2Jn8Kv3TCAztItDql/4uyDpPDLZW/scC5+Z86dBdpl4ATbYEAU4T+Q6WGzwTPPzFHtx7B2V/c0OJ1bnPntMvgiPocgEkUysi0DfLn0MfwwRiNaz9rpE88lg6GgRxDQzAyDaF9dARo=
    mysql_username: AgCHKJt468nqsMsRjqQAhnVY6jnjpdiKf6haYYQSxpiGpIUQ3xhEMDhHxQckhAF6IKOdCQZtHrXIjPtIh1dFT3+rB6yd+ofj0Inugqd99z3/Jhgqz8bg8VrcneqrbihM4lp1jtaW6qYAZQm1V4dwo1R8up0WXJdQZN86pN57QdCeTlOhL9u07cdHjDlAdOR9dK8IDrgcLnbPaTj4u9B0ljqKCjWYN6yN+nmA0mz28JShGEIseZXDMGhppcE/xPzTHWnKGT+MigbLtB42678bKwNv1ZrVgiA18yYpRWKA5V//AiiSmw/wNDMW0vPaS7d9XCOQLOq8JEVevn4FScylEqtQx09SRTa00DGOOVC3U12kl+zXkM9LOYl7ZmqPHPujNEVzorjyL2NB2zsQrDeAeEaIBRqw7ozf/YGhITarYDZEGPC6DgHPx0cMxTcWfPYh9EDy3/6yQ/HohtkBQpwE/3TYl+E8n0Fm+zImkbVSrWmduO/TIwSFeQYCMUVJT9ISYE/Zqd+pAAGNCXEGzzIerpVWqU68f7zRSVUAeMBuoBp9p1sqAH+Vbka9oJf6rgL9UjYVTB3FSbNmo87vUS9aApn8VEico6pKw5gJX+j6HqScv0rN80q1SNd8vINsrAQC+GJObCkXBctbx/R7Cf84D45hudcATJrt9DltHlQcnDyv8u2HxSoqIs1mQKbuKpoiua2XZcVh7K1ryURX3Yw=
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/sync-wave: "-1"
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: test-secrets
      namespace: default
    type: Opaque
`

I really need the annotations to exist on the sealedsecret resource, allowing argocd to deploy it FIRST before migration jobs.

**Comment by juan131** [comment]
Duplicate of https://github.com/bitnami-labs/sealed-secrets/issues/403

**Comment by rufreakde** [comment]
@juan131  this is not a duplicate of #403 in this Issue here it is talked about adding labels/annotations that are on the secret automatically also to the sealedSecret.

As far as I see 403 it is a bug where the sealedSecret is missing to set some labels inside the secret? So the other way around.

It would even be nice to have a way to use `kubeseal` to directly annotate or label the sealed secrets `--annotate` or `--label` to the command allowing to directly to apply annotations and labels to the sealedSecret when generating them.

**Comment by ysong6** [comment]
> ```
> 
> ```
> 
> 
>     
>   
> 
> I really need the annotations ` argocd.argoproj.io/hook:` and  `argocd.argoproj.io/sync-wave` to exist on the sealedsecret resource, allowing argocd to deploy it FIRST before migration jobs.

the argocd annotations can work for this? i thought that's just for app-of-apps pattern?

**Comment by rufreakde** [comment]
> > ```
> > 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I really need the annotations ` argocd.argoproj.io/hook:` and  `argocd.argoproj.io/sync-wave` to exist on the sealedsecret resource, allowing argocd to deploy it FIRST before migration jobs.
> 
> 
> the argocd annotations can work for this? i thought that's just for app-of-apps pattern?

sync-wave would not have any impact but hook would wait for each step so it would work in theory. But I would need to retest this to be 100% sure.

https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/

**Comment by JanCizmar** [comment]
Hey! Adding the sync-wave annotation works for me. However adding the annotation manually every time I edit the secret is far from optimal. It would be nice to have an option to add annotation to the sealed-secret using some other property. Maybe something like this?
```
apiVersion: v1
kind: Secret
metadata:
  namespace: ...
  name: ...
propagateMetadata: <-- Here
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

stringData:
....
```

**Comment by rufreakde** [comment]
> Hey! Adding the sync-wave annotation works for me. However adding the annotation manually every time I edit the secret is far from optimal. It would be nice to have an option to add annotation to the sealed-secret using some other property. Maybe something like this?
> 
> ```
> apiVersion: v1
> kind: Secret
> metadata:
>   namespace: ...
>   name: ...
> propagateMetadata: <-- Here
>   annotations:
>     argocd.argoproj.io/sync-wave: "-2"
> 
> stringData:
> ....
> ```

If you are in full control of your deployments it might make sense to split the dependent deployment out into its own argo-app. That way it will recover as soon as the secret is there and fail as long as it is not there.

**Comment by JanCizmar** [comment]
Yeah, well, actually I am using this particular secret for pre-sync hook, which is doing some magic. Not sure if splitting it is the right way to do that, since it's all one app, right? Moving it out would result to handling 2 separate apps with different deployment cycle. Or do I get it wrong?

**Comment by shinebayar-g** [comment]
> Duplicate of #403

Hey @juan131 , please re-open this issue. Your linked issue doesn't seem to be related at all!
