### ISSUE TITLE
Question: Move sealed-secrets namespace

### ISSUE THREAD

**Issue by groodt** [bitnami-labs/sealed-secrets#462]
Question:

Is it possible to move sealed-secrets to a different namespace? What about existing sealed-secrets? If I export the key and reupload to new namespace will things continue to work?

**Comment by mkmik** [comment]
(I assume you mean moving the sealed secrets controller to another namespace)

Yes, you can move/copy the secrets that contain the private keys to the new namespace and then redeploy the controller in the new namespace. 

Keep in mind that the rbac resources also contain a reference to the namespace.

This is a common request so I guess we should provide an alternate manifest

**Comment by groodt** [comment]
Thanks. For my own sanity, how many secrets should I be looking for and what are their names?

**Comment by mkmik** [comment]
The backup documentation shows the label selector to use : https://github.com/bitnami-labs/sealed-secrets#how-can-i-do-a-backup-of-my-sealedsecrets
