### ISSUE TITLE
v0.13.0 manifest declares non existing image tag

### ISSUE THREAD

**Issue by lanmarti** [bitnami-labs/sealed-secrets#469]
I tried applying https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.13.0/controller.yaml but the image with tag v0.13.0 does not seem to exist yet on quay.io

**Comment by mkmik** [comment]
yeah the release process on travis got stuck

**Comment by mkmik** [comment]
bug in the release automation, fixing

**Comment by mkmik** [comment]
fixed in [v0.13.1](https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.13.1)

thanks!
