### ISSUE TITLE
"Bitnami Sealed Secrets" not working with Kustomize.

### ISSUE THREAD

**Issue by bbhagat4** [bitnami-labs/sealed-secrets#477]
$ kustomize version
{Version:kustomize/v3.8.7 GitCommit:ad092cc7a91c07fdf63a2e4b7f13fa588a39af4f BuildDate:2020-11-11T23:14:14Z GoOs:windows GoArch:amd64}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.4-2+a00aae1e6a4a69", GitCommit:"a00aae1e6a4a698595445ec86aab1502a495c1ce", GitTreeState:"clean", BuildDate:"2020-04-22T11:35:29Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

# --- BASE ---
$ cat base/sealedsecret.yaml
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: myapp-operative-secret
  namespace: myapp-test
spec:
  template:
    metadata:
      name: myapp-operative-secret
      namespace: myapp-test
  encryptedData:
    API_KEY_0: ""

$ cat base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp-test
resources:
  - sealedsecret.yaml

$ kustomize build base | kubectl apply -f - --dry-run
sealedsecret.bitnami.com/myapp-operative-secret created (dry run)

# --- OVERLAY ---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: myapp-operative-secret
  namespace: myapp-dev
spec:
  template:
    metadata:
      name: myapp-operative-secret
      namespace: myapp-dev
  encryptedData:
    API_KEY_0: "AgCvkySbppDk6kvnfPBuj+/..."

$ cat overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp-dev
bases:
  - ../../base
patches:
  - sealedsecret.yaml

$ kustomize build overlays/dev --stack-trace
Error: no matches for OriginalId bitnami.com_v1alpha1_SealedSecret|myapp-dev|myapp-operative-secret; no matches for CurrentId bitnami.com_v1alpha1_SealedSecret|myapp-dev|myapp-operative-secret; failed to find unique target for patch bitnami.com_v1alpha1_SealedSecret|myapp-operative-secret

$ k apply -f overlays/dev/sealedsecret.yaml --dry-run
sealedsecret.bitnami.com/myapp-operative-secret created (dry run)

**Comment by adrienbrault** [comment]
@bbhagat4 You should probably report this to https://github.com/kubernetes-sigs/kustomize instead

**Comment by juan131** [comment]
Duplicate of https://github.com/bitnami-labs/sealed-secrets/issues/167
