### ISSUE TITLE
no key could decrypt secret

### ISSUE THREAD

**Issue by pydo** [bitnami-labs/sealed-secrets#480]
**Summary**
My sealed-secret controller cannot decrypt any `SealedSecret` I create.

**Version**
Sealed-secrets: 1.13
Kubernetes: 1.19

**Repro steps**
1. Create `argocd-secret.yaml` <
```
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  server.secretkey: B64DATA
  githubSSOOAuthSecret: B64DATA
```
2. Create and apply sealed secret `kubeseal -o yaml < argocd-secret.yaml >argocd-sealed-secret.yaml`
```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
spec:
  encryptedData:
    githubSSOOAuthSecret: SECRETDATA
    server.secretkey: SECRETDATA
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
```
3. check controller logs: 

**Expected behavior**
Controller decrypt secret

**Actual behavior**
```
2020/11/30 01:35:18 Event(v1.ObjectReference{Kind:"SealedSecret", Namespace:"argocd", Name:"ssh-campion-ops", UID:"9603e86a-1831-4b7a-afaf-d2abca4dca40", APIVersion:"bitnami.com/v1alpha1", ResourceVersion:"45121", FieldPath:""}): type: 'Warning' reason: 'ErrUnsealFailed' Failed to unseal: no key could decrypt secret (ssh-privatekey)
2020/11/30 01:35:18 Updating argocd/argocd-secret
2020/11/30 01:35:18 Error updating argocd/argocd-secret, giving up: no key could decrypt secret (githubSSOOAuthSecret, server.secretkey)
E1130 01:35:18.284332       1 controller.go:200] no key could decrypt secret (githubSSOOAuthSecret, server.secretkey)
```

What can I do to debug this?
Thanks!

**Comment by mkmik** [comment]
Not sure if this is your case, but the most common cause for this error mode is using the default scope and sealing with a namespace A and applying the resource in namespace B.

Please make sure you've read the readme section about "Scopes".

**Comment by pydo** [comment]
> Please make sure you've read the readme section about "Scopes".

I did and am using the default `strict` scope.
The sealedsecret namespace and the target secret namespace are the same `argocd`I omitted the namespace from my original example because it's applied with `kustomize`.

Is there a way to increase the logging verbosity? I don't see any flags for that here https://github.com/bitnami-labs/sealed-secrets/blob/master/cmd/controller/main.go#L250 .

Thanks

**Comment by pydo** [comment]
You were correct about the mismatching namespaces. I based the sealedsecret off a regular secret that did not have an explicit namespace. I did that out of habit because kustomize freaks out if it sees a namespace on a resource when using the namespace transformer.

**Comment by mkmik** [comment]
Yeah, perhaps we should warn when the default namespace for the current context is implicitly used

**Comment by abdennour** [comment]
@pydo  could you explain before resolution and after resolution ? full command kubeseal ,, so on

**Comment by luk-sam** [comment]
I had same error message while installing helm chart and it was caused by underscores in keys in values.yaml
I hope this helps someone

**Comment by ozbillwang** [comment]
> underscores

How do you fix the issue?

rename the key?

I set the key name as `DB_USER`, will this be a problem in sealed secret?
