### ISSUE TITLE
Automated Lookup from KubeConfig based on API Server Address

### ISSUE THREAD

**Issue by ghostsquad** [bitnami-labs/sealed-secrets#482]
this is a followup from #481 

[Tanka](https://github.com/grafana/tanka) has a really nice feature, in that you provide the API server address statically (config checked in for each environment), and thus when running a command like `tk apply production` it doesn't matter what your currently selected kube context is, it can lookup the CA cert etc based on the API server you provide it from your kube config (or at least that's how I interpret this).

This is a request for similar functionality in `kubeseal`. Currently, you must provide the following to ensure you get access (or leave blank, and rely on current kube context):

```
$ kubeseal --help
...
      --server string                    The address and port of the Kubernetes API server
      --certificate-authority string     Path to a cert file for the certificate authority
```

A potential work around would be to do something like:

```shell
K8S_API_URL=https://<REDACTED>.yl4.us-west-2.eks.amazonaws.com

yq r ~/.kube/config 'clusters' -j | jq --arg server "${K8S_API_URL}" '.[] | select(.cluster.server==$server) | .cluster["certificate-authority-data"]' > ~/tmp/k8s-server-ca-data

kubeseal --certificate-authority ~/tmp/k8s-server-ca-data ...

rm ~/tmp/k8s-server-ca-data
```

As you can see though, this is complicated, and requires several other tools installed, and error handling to ensure that you cleanup the temporary CA data file on exit.

**Comment by ghostsquad** [comment]
I don't know what the process is for this, but I'd be happy to contribute a fix. I'd like to get confirmation before beginning a PR that this type of design decision is accepted.

**Comment by mkmik** [comment]
just file a PR; not much process; help appreciated!

a good way to make a PR merged quickly is to:

1. keep it short and easy to review
2. avoid performing unrelated edits (even if they are otherwise useful fixes)
3. adding relevant unit or integration tests

**Comment by ghostsquad** [comment]
it appears that `--certificate-authority` flag isn't the one for connecting to the kubernetes API server. So this won't work. But I suppose I could still contribute a new flag.

**Comment by ghostsquad** [comment]
I've moved away from SealedSecrets since picking up Pulumi, which supports "SOPS" style secrets encrypted in the code repository. So I'll close this issue, as it seems like there's not much other interest in this functionality.

**Comment by omidraha** [comment]
@ghostsquad Do you have an example for using `Pulumu` and `SOPS` ?

**Comment by ghostsquad** [comment]
> @ghostsquad Do you have an example for using `Pulumu` and `SOPS` ?

https://www.pulumi.com/docs/concepts/secrets/
