### ISSUE TITLE
Update chart to work on newer clusters

### ISSUE THREAD

**Issue by davidkarlsen** [bitnami-labs/sealed-secrets#486]
Related to #389.
Do a new version which avoids outdated api versions (rbac, deployment etc).
Right now sealed-secrets is not deployable onto a modern (1.19) cluster.
Will probably require an updated CRD as well (not just the api-version).

You can assign me it.

**Comment by mkmik** [comment]
thank you for your help!

**Comment by mkmik** [comment]
> Right now cert-manager

you mean `sealed-secrets` right?

**Comment by davidkarlsen** [comment]
Lol - yes - was working on cert manager earlier today 😂
