### ISSUE TITLE
Latest helm chart release uses a non-intuitive tag name

### ISSUE THREAD

**Issue by smoyer64** [bitnami-labs/sealed-secrets#493]
If this was intentional, it would be great if the release could also be tagged with the equivalent `v1.13.2` tag so that automated tools can more easily identify the download location.

**Comment by mkmik** [comment]
This is the release of the the helm chart, not of the sealed-secrets controller itself.

The automation should have prefixed the release with helm- 

CC @davidkarlsen

**Comment by davidkarlsen** [comment]
It can be configured with https://github.com/helm/chart-releaser --release-name-template via the config file

**Comment by smoyer64** [comment]
So in the future, a release of the helm chart and the controller will be synchronized?  That's a nice pattern!  I've changed the issue subject to reflect what you've described.

**Comment by mkmik** [comment]
Yes. Helm chart releases can happen more frequently if the changes only affect bug fixes in the helm chart itself. We'll come up with a suitable versioning scheme

**Comment by smoyer64** [comment]
Looks great ... I'll never mistake that for the controller!  I also love that the suffix is a conventional version tag.
