### ISSUE TITLE
[Information] Added Github Pages Helm Charts to artifacthub.io.

### ISSUE THREAD

**Issue by Cellebyte** [bitnami-labs/sealed-secrets#498]
[![Artifact HUB](https://img.shields.io/endpoint?url=https://artifacthub.io/badge/repository/bitnami-labs)](https://artifacthub.io/packages/search?repo=bitnami-labs)

Hey guys I added your helm chart repository to the artifacthub.io project.
You can claim ownership.
I needed it available to replicate sealed-secrets with harbor-registry.

**Comment by mkmik** [comment]
It's not clear to me what actions do I have to take to claim ownership and remove the deprecation notice

**Comment by mkmik** [comment]
Found https://github.com/artifacthub/hub/blob/master/docs/repositories.md#ownership-claim

Added `artifactoryhub-repo.yaml` to gh-pages branch:

```
$ curl -Lsf https://bitnami-labs.github.io/sealed-secrets/artifacthub-repo.yml
repositoryID: b66562a1-0484-4ddc-a8cf-54656f991a8
owners:
  - name: Marko Mikulicic
    email: mkm@bitnami.com
```

**Comment by mkmik** [comment]
ok the ID changes upon transfer so it should not be included during the claim process.

Now I own this repo but I still don't know what to do in order to remove the deprecation notice. Any help appreciated

**Comment by mkmik** [comment]
:facepalm: the deprecation notice is in the chart's own README ... will fix
