### ISSUE TITLE
kubeseal outputs spec.template.metadata.name{,space} but is ignored

### ISSUE THREAD

**Issue by snuggie12** [bitnami-labs/sealed-secrets#499]
kubeseal version `v0.12.6` and sealed-secrets-controller version `v0.12.5`

If I run the following you'll see the name and namespace for the `Secret` is printed under `spec.template.metadata`. However, this implies that the fields could be changed and if for some reason you wanted a different name it could work:

```
# Note my controller is not in the default namespace and so you might need to remove the option
$ kubectl create secret generic -n default -o yaml --dry-run=client test --from-literal foo=bar | kubeseal --controller-namespace sealed-secrets -o yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test
  namespace: default
spec:
  encryptedData:
    foo: AgCFHWVh+MeREwfLu9FZtRo+VcZya2zXiQD0p8+RsKHxsEgZKIB0HPhLorrc4eqD3gWFB/Nxjv6yjbNASkj+RAzDdookKUbrJPmNGRotwh6WS84+L8WbKacpC1utemCWgWjVm4bv//jfCPamP1p95Fq3jKaSiR0VhTAV/ZAKsI/HVXKl+apKApuqC+oSvtvKCZiKfKCTtWIZ9VKyUv2LjOHHKJqGHGK2Yj7aXX9hZaGlUjfvYu5NuON4Yu4vH+dXe5CZ06ymcyikCeCYQM6SKk7GdEWiOLJPmLRIq7HrV2WzGCFxRpp1d3SwEpzSDxxCyQ9JWnhsZaP/KdEIll0a0kn3MMbj4OILscSyclZS+CBoIq+mIe4dLo/xp3cCth6J+EX1iQlzFohxkPTno+5WIMEHekXBDYIDzkk2zRCRbr7j5/KvySSq/zuSbGFe/HjOSY3J1EOt8ne521u4AyTB7oonA73J7kHu+feHxNQbsZuuG7joLf16arO1ui6tcKfbLqcSPdSpQI0fa5jZwvW7Uqj0qYNSy6Q68LYM5Czd5Cs6mGaY5roQp3RsxiwVji2fPRkpf3U/VKPjJD6BcLl7wobS1aqdvytdSg+BO/fy2svXSyXxPe811urecZh7IdI2hOSkEZ1qFTpDO9KkGc8ZcRyMOizluj7xauSg1PQOWSsnLIP3Bw3f3t2/iFGn3B3nTTIsnBA=
  template:
    metadata:
      creationTimestamp: null
      name: test
      namespace: default
```

I'm actually fine with not enabling this feature but it's confusing. I'm wondering if this could be removed from the output of `kubeseal`??

Pretty sure the logic is here: https://github.com/bitnami-labs/sealed-secrets/blob/ce399099886139edbfcb7a16f3c693a62dbe9475/cmd/controller/controller.go#L72-L83

**Comment by juan131** [comment]
I'm sorry but I don't understand what's the issue here. What's the problem with `spec.template.metadata`? That's what the SealedController uses to create the associated secret's metadata.

**Comment by snuggie12** [comment]
The implication from "template" is that whatever you fill in will appear on the dependent secret resource. However it doesn't matter what is filled in for name or namespace. No matter what it keeps the same name as the owner reference. 

This could be useful with tickets like a kustomize plugin (sorry on mobile so can't link) where the sealed secret is named one thing but the actual secret is named with a hash.

**Comment by mkmik** [comment]
Yeah. It's confusing. It shouldn't be there. We need to be careful with backward compat when fixing this though
