### ISSUE TITLE
README tells to find "latest release" but latest release is broken.

### ISSUE THREAD

**Issue by EnigmaCurry** [bitnami-labs/sealed-secrets#500]
The README says : 
```
See https://github.com/bitnami-labs/sealed-secrets/releases for the latest release and detailed installation instructions.
```

The last release with instructions on installing the controller is v0.13.1:

https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.13.1

However, the "Latest release" (right now) on github is : https://github.com/bitnami-labs/sealed-secrets/releases/tag/helm-v1.13.2-r2

This newer version does not contain instructions, and does not contain the `controller.yaml` needed for install on cluster. (also note the different release name)

**Comment by EnigmaCurry** [comment]
I was trying to be clever and script a way to always download the latest release:

```
SEALED_SECRET_VERSION=$(curl --silent \
  "https://api.github.com/repos/bitnami-labs/sealed-secrets/releases/latest" | \
  grep -Po '"tag_name": "\K.*?(?=")')
```

which was working up until v0.13.1, but is now broken due to recent changes in the releases.

**Comment by mkmik** [comment]
Yes, we use a `helm-` tag for helm chart releases which are related but independent from the controller releases.

I'll try to figure out how to filter these out.

**Comment by IbraheemAlSaady** [comment]
I'm trying to find the helm chart repository, but I always end up in the stable repo. The chart README says that this chart is deprecated and no longer supported, so I'm a little bit confused. Is there a helm repo other than the deprecated stable on? if yes, can you please share it. Thank you

**Comment by mkmik** [comment]
The problem is that the README of the latest released chart still says it's deprecated; I have to cut a new release for the README to change

**Comment by mkmik** [comment]
(I'll do a new release soon; holidays are over and I can focus back on this)

**Comment by IbraheemAlSaady** [comment]
Great, thanks @mkmik, in the meantime, what is the URL of the helm repository?

**Comment by mkmik** [comment]
@IbraheemAlSaady  
https://github.com/bitnami-labs/sealed-secrets#helm-chart

```
$ helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
```

**Comment by IbraheemAlSaady** [comment]
Amazing, that's what I needed, thank you

**Comment by IbraheemAlSaady** [comment]
@mkmik I just tested the 1.13.2. helm install works fine, but when I do helm delete, I get an error.

```
manifest-1

release "sealed-secrets" uninstalled
```

It says the release is uninstalled, however, the CRD `sealedsecrets.bitnami.com` is still there. I'm also using the terraform helm release resource, on `terraform destroy`, I get an error on `manifest-1`, it's not really clear.

The above is tested with normal helm install command and terraform helm release resource

**Comment by mkmik** [comment]
IIRC the next chart release will use the new chart format that has an improved handling of the CRDs

**Comment by IbraheemAlSaady** [comment]
@mkmik any timeline for this change? If it still didn't start, maybe I can pick up the helm chart. I don't know what's required though

**Comment by IbraheemAlSaady** [comment]
@mkmik ^^

**Comment by mkmik** [comment]
sorry I was sick; I'll cut a new release soon

**Comment by IbraheemAlSaady** [comment]
@mkmik no worries, I hope you're feeling better. Let me know if I can help

**Comment by mkmik** [comment]
released new version of sealed-secrets controller and also a helm chart with the correct README

Now https://artifacthub.io/packages/helm/bitnami-labs/sealed-secrets doesn't show the scary message.

HOWEVER; I didn't test the helm chart (still have some work to do in the release automation to actually test the helm chart on all the k8s version etc), so it MAY be broken; I realized that the perfect is the enemy of the good and if the release is broken somebody will tell me

**Comment by IbraheemAlSaady** [comment]
@mkmik just tested it out on my cluster, seems to work just fine :D

**Comment by jbouter** [comment]
I'd just like to chime in and say that releasing sealed secrets and helm charts alongside on the same repository is breaking our CI  for re-building the containers based on latest release. I would like to request releases of sealed secrets and helm charts are separated from each other (in different repositories).

**Comment by mkmik** [comment]
@jbouter I currently mark them pre-release manually after the automation has released them. Would it work for you if we manage to make the automation never create final (i.e. non-prereleases) releases for helm tags?

**Comment by jbouter** [comment]
@mkmik If the "latest release" always shows the non-helm release, then that would definitely work :-)

**Comment by mkmik** [comment]
Yeah that was the idea. In the meantime can you filter by release tag name pattern?
