### ISSUE TITLE
Question: I always get different encrypted data, is that normal ?

### ISSUE THREAD

**Issue by esteban1983cl** [bitnami-labs/sealed-secrets#515]
Hi Team, congrats to create this very useful tool. I have a quick question, sealed secrets (kubeseal/controller) uses timestamp to encrypt data ? because when execute the kubeseal command I always get different encrypted data for the same secret name and namespace. If this is true, can I disable this at controller or client level ? Thanks in advance.

**Comment by mkmik** [comment]
It's normal. It uses a random nonce (not a timestamp), which is pretty standard in modern cryptography.
