### ISSUE TITLE
Controller fails to process sealed secret with empty encrypted data

### ISSUE THREAD

**Issue by squat** [bitnami-labs/sealed-secrets#516]
Sealed secrets without any data can be generated using `kubeseal` when passing the `--allow-empty-data` flag, however, the controller fails to process them. Instead, the controller produces logs along the lines of:

```
2021/02/02 15:31:56 Updating <namespace>/<name>
2021/02/02 15:31:56 Event(v1.ObjectReference{Kind:"SealedSecret", Namespace:"<namespace>", Name:"<name>", UID:"f79bceb7-8d10-40e1-908e-d312238ea479", APIVersion:"bitnami.com/v1alpha1", ResourceVersion:"25561867", FieldPath:""}): type: 'Warning' reason: 'ErrUnsealFailed' Failed to unseal: no key could decrypt secret
2021/02/02 15:31:56 Error updating <namespace>/<name>, will retry: no key could decrypt secret
```

Is this by design? If not, is it a known issue?

I think it would be easy to fix and would be happy to implement it. Optionally, this functionality could be guarded by an analogous flag in the controller.

Thanks :)

**Comment by picchipalarm** [comment]
Noticed this when upgrading from v0.12.4 to v1.14.1
Seems to be introduced in v0.13.1.
Had to use v0.12.6  with helm chart version 1.14.1-r1

**Comment by mihn** [comment]
Hello,
Is this a issue or non-issue?

**Comment by squat** [comment]
This is still an issue. Happy to make a PR, just want to know if Bitnami will welcome it :)

**Comment by picchipalarm** [comment]
I believe latest 0.17.3 now supports empty encrypted data again
https://github.com/bitnami-labs/sealed-secrets/blob/main/RELEASE-NOTES.md#changelog

**Comment by squat** [comment]
amazing, we can finally close this :tada:
we just narrowly avoided the anniversary :tada:

**Comment by squat** [comment]
fixed by https://github.com/bitnami-labs/sealed-secrets/pull/653
