### ISSUE TITLE
README references incorrect secret type

### ISSUE THREAD

**Issue by torinthiel** [bitnami-labs/sealed-secrets#524]
https://github.com/bitnami-labs/sealed-secrets#sealedsecrets-as-templates-for-secrets shows as an example a secret of type `kubernetes.io/dockercfg` which exists and has some validation on the k8s side, but does not work as expected.

The real image pull secrets are of type `kubernetes.io/dockerconfigjson`and have a different field, as can be seen on <https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials>. I've found a completely unrelated issue https://github.com/hashicorp/terraform-provider-kubernetes/issues/79 with the same problem and solution, so I guess `dockercfg` was a thing a while back.

**Comment by mkmik** [comment]
https://kubernetes.io/docs/concepts/configuration/secret/

```
kubernetes.io/dockercfg	serialized ~/.dockercfg file
kubernetes.io/dockerconfigjson	serialized ~/.docker/config.json file
```

Nowadays most people run a version of docker that uses the new file format `config.json` and we should indeed update our documentation example to reflect that.

**Comment by torinthiel** [comment]
Missed a pretty obvious reference ...

Are my changes in #528 sufficient or should I dig deeper?

**Comment by mkmik** [comment]
@torinthiel yes that was sufficient; thanks!
