### ISSUE TITLE
#529 crd in helm chart has empty properties set

### ISSUE THREAD

**Issue by KlavsKlavsen** [bitnami-labs/sealed-secrets#530]
which gets removed by k8s - and thus argo-cd sees that the crd helm chart wants to install is NOT the same as the one in kubernetes (as k8s one is lacking properties: {}
Fix is in #529

**Comment by svdubovik** [comment]
thanks, but looks like the [version.yaml](https://github.com/bitnami-labs/sealed-secrets/blob/master/version.yaml) should be updated to trigger build new version of the helm chart

**Comment by KlavsKlavsen** [comment]
https://github.com/bitnami-labs/sealed-secrets/pull/532 <- I opened new PR (as 529 was merged) - to up helm chart minor version. Hope thats correct :)
