### ISSUE TITLE
Add healing/reconciliation loop for secret generation

### ISSUE THREAD

**Issue by drewboswell** [bitnami-labs/sealed-secrets#542]
# Summary
Add reconciliation loop/check between controller internal "unsealed" state and cluster actual state.

# Motivation
There are two scenarios I have experienced that would be rectified by this additon:
* sealed secret occasionally missed by controller and never unsealed
* secret is deleted (accidental or malicious)

# Proposal
Add a cache expiry to the internal "unsealed" list that the controller has locally. (if I understood it's architecture, which I may not have)

# Context / Environment
kubernetes v. 1.18.15
kubeseal v. 0.12.16
Sealed secrets / instance: 500-4000

**Comment by mkmik** [comment]
could this possibly be a duplicate of #224?

**Comment by drewboswell** [comment]
Yes this seems to be the same, I'll continue by posting there
