### ISSUE TITLE
Add additional prometheus metrics

### ISSUE THREAD

**Issue by drewboswell** [bitnami-labs/sealed-secrets#545]
# Summary
Add additional prometheus metrics for better health/status tracking.

# Motivation
To be able to detect limitations/backlogs/problems and generally boost observability these metrics would help.

# Proposal
Add the following metrics:
* current work queue size
* total sealedsecrets in cache (aka total successfully processed/tracked)
* total subscribed sealedsecrets (aka total in cluster)

# Context / Environment
kubernetes v. 1.18.15
kubeseal v. 0.15.0
Sealed secrets / instance: 500-4000

**Comment by juan131** [comment]
Let's follow the conversation at https://github.com/bitnami-labs/sealed-secrets/issues/543
