### ISSUE TITLE
Missing pull secret

### ISSUE THREAD

**Issue by Lapeyus** [bitnami-labs/sealed-secrets#547]
Helm chart is missing a pull secret variable, needed to pull images from a private repository

**Comment by Lapeyus** [comment]
closed by PR #548

**Comment by Lapeyus** [comment]
Merged #548

**Comment by mkmik** [comment]
just curious: are you pulling sealed-secrets image from a private repo because you run in an air-gapped environment?

**Comment by Lapeyus** [comment]
yes exactly, we are setting it up inside an air-gapped cluster, we can pull all our charts and images from an in-cluster registry only, prod clusters will definitely not have access to the internet
