### ISSUE TITLE
v0.15.0/controller.yaml deployment out of order

### ISSUE THREAD

**Issue by jam01** [bitnami-labs/sealed-secrets#560]
Starting from v0.15 the Deployment is listed before some of its dependencies like a ServiceAccount. This results in the Ansible k8s module to fail because it waits for each resource to be ready before applying the next.

Took a quick look a the jsonnet file, but can't figure out the best way to push the Deployment to the bottom of even the inherited resources.

**Comment by jam01** [comment]
We've worked around this by using kustomize's re-ordering feature. So I suppose we could close this issue or perhaps mark it as very low priority.

**Comment by mkmik** [comment]
Uh thanks there must be a bug in `kubecfg show` which should order things.

Can you share your kustomize based workaround, perhaps I can just add it in the release pipeline

**Comment by jam01** [comment]
With kustomize v3.9.4 the following kustomization.yaml file is correctly ordered by default:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.15.0/controller.yaml
```

I specify the kustomize version, not because of any changes in the way it orders resources, but because we've seen some issues with newer versions and remote references sometimes.

**Comment by juan131** [comment]
Hi @jam01 

Can you also reproduce the issue with the current **0.17.3** version?
