### ISSUE TITLE
Error E0330 after upgrade of k8s cluster to 1.19

### ISSUE THREAD

**Issue by mhobotpplnet** [bitnami-labs/sealed-secrets#562]
Was wondering if you guys seen this error before

`sealed-secrets-controller-58f8dd9c5c-kxtwp sealed-secrets-controller E0330 06:37:11.997892       1 controller.go:156] v1.Secret: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"67|..., bigger context ...|},"f:metadata":{"f:ownerReferences":{".":{},"k:{\"uid\":\"555707350e2-42155-43a1-9649-2c75d339882a\"}":{|`

This started with 1.19 k8s cluster. 

Secret
```
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "Name",
    "namespace": "NameSpace",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "Name",
        "namespace": "Namespace",
        "creationTimestamp": null
      }
    },
```
Is it possible that issue is with apiVersion ? 

Our version of helmchart is bit old: 0.7.0 
To update to new version I assume secrets will need to be recreated?

**Comment by mkmik** [comment]
Please upgrade. We strive to guarantee backwards compatibility with existing SealedSecrets resources across all upgrades, even coming from ancient versions.

The controller however is tested only against a few recent versions of k8s and of course cannot be tested against future versions of k8s, so please upgrade the controller.

**Comment by mhobotpplnet** [comment]
Thank you, will update this thread after upgrade on a controller.
