### ISSUE TITLE
How can I recreate a k8s cluster without loosing my secrets?

### ISSUE THREAD

**Issue by tobias-neubert** [bitnami-labs/sealed-secrets#570]
Hi,

excuse me for posting a question here. Especially during the start of developing a complete system based on kubernetes, I have the problem, that I delete and recreate the whole cluster often. Have I understood it correctly, that I cannot set the private key used by the controller for decrypting manually? As far as I understand I need to be able to do so or otherwise all my encrypted secrets that are stored in the git repository of my application are useless then.

So: How can I set the private key for the controller to a known value that survives cluster rebuilds?

Thankful for any help,
Tobias

**Comment by verokarhu** [comment]
https://github.com/bitnami-labs/sealed-secrets#how-can-i-do-a-backup-of-my-sealedsecrets

**Comment by tobias-neubert** [comment]
Oops, that was simple. Stupid me, for not connecting both topics.
