### ISSUE TITLE
Cannot create immutable secrets

### ISSUE THREAD

**Issue by gabegorelick** [bitnami-labs/sealed-secrets#574]
Kubernetes 1.18+ (stable in 1.21) offers immutable secrets via the `immutable` attribute. See https://kubernetes.io/docs/concepts/configuration/secret/#secret-immutable.

However, this attribute is ignored by sealed-secrets.

The first issue is that `kubeseal` strips the `immutable` attribute from the generated SealedSecret resource:
```sh
kubeseal <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: test
immutable: true
data:
  foo: deadbeef
EOF
```

That generates the following SealedSecret (without any reference to `immutable`):
```json
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "test",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "test",
        "namespace": "default",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "foo": "..."
    }
  }
}
```

But it's not just an issue with `kubeseal`. The sealed-secrets controller itself doesn't seem to support the `immutable` attribute. If we add `spect.template.immutable: true` to the above manifest, the generated secret still doesn't have `immutable` set.

**Comment by rufreakde** [comment]
+bumb
is this still an issue? I think in use cases like ArgoCD where you want the unsealed secrets that should not be modified this might be a valid solution. I will test this out today as to how it works.

**Comment by pentago** [comment]
any progress on this issue?
It would be great to have immutable secrets created when unsealing the one to avoid getting secrets edited manually.

**Comment by gavinkflam** [comment]
This is added in #1395 
Please help to review the changes.
