### ISSUE TITLE
After fresh installation getting this error "ErrUnsealFailed' Failed to unseal: no key could decrypt secret"

### ISSUE THREAD

**Issue by haim-ari** [bitnami-labs/sealed-secrets#575]
Installed client
```
brew install kubeseal
```
Check version
```
kubeseal --version
kubeseal version: v0.15.0
```

Installed sealed-secrets with Helm chart in the `kube-system namespace`
```
chart: sealed-secrets
version: '1.13.2'
``` 

When running the client getting this error:

```
[~] kubeseal
(tty detected: expecting json/yaml k8s resource in stdin)
error: cannot fetch certificate: services "sealed-secrets-controller" not found
```

Which is expected since for some reason this is not the service name:

```
[~] kubectl get svc -n kube-system |grep sealed
sealed-secrets   ClusterIP   10.43.7.73     <none>        8080/TCP                 20h
```

Pod image
```
Controlled By:  ReplicaSet/sealed-secrets-d87969f4f
Containers:
  sealed-secrets:
    Container ID:  docker://92aa2b6c1acf9a9bbd39a1650aab307620e605a93dc2b9e1f6f66e43ca78790f
    Image:         quay.io/bitnami/sealed-secrets-controller:v0.13.1
    Image ID:      docker-pullable://quay.io/bitnami/sealed-secrets-controller@sha256:ed7aba5fb4f05f7d719f0142c8b5c8b4a5b165f7f9322bbb3eb6e6bd94404a80
    Port:          8080/TCP
    Host Port:     0/TCP
```

I tried creating secrets in both yaml and json format:
```
kubectl create secret docker-registry regcred \
  --docker-server=registry.our-registry.com \
  --docker-username=image_registry_ro \
  --docker-password=XXXXXXXXXXXXXXX \
  --docker-email=registry_ro@our-email.com \
  --output json --dry-run | kubeseal --controller-name sealed-secrets  > sealed.json
```

```json
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "regcred",
    "namespace": "production",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "regcred",
        "namespace": "production",
        "creationTimestamp": null
      },
      "type": "kubernetes.io/dockerconfigjson"
    },
    "encryptedData": {
      ".dockerconfigjson": "AgB1hMwu5k..."
    }
  }
}
```

This is what i see in the controller logs:

```
2021/04/21 17:46:48 Error updating production/regcred, giving up: no key could decrypt secret (.dockerconfigjson)
E0421 17:46:48.514768       1 controller.go:200] no key could decrypt secret (.dockerconfigjson)
2021/04/21 17:46:48 Event(v1.ObjectReference{Kind:"SealedSecret", Namespace:"production", Name:"regcred", UID:"8bcbcc52-fd87-4900-9f89-cf6d27a9f244", APIVersion:"bitnami.com/v1alpha1", ResourceVersion:"1072548", FieldPath:""}): type: 'Warning' reason: 'ErrUnsealFailed' Failed to unseal: no key could decrypt secret (.dockerconfigjson)
```

**Comment by itspngu** [comment]
I'm having the exact same issue and after a lot of digging I realized that the secrets I seal locally are mutating - every run of `kubeseal` produces different values in `spec.encryptedData`. The certificate of the sealed-secrets controller itself is not changing. Is that the same for you? I'm awfully confused - there's no way `kubeseal` should produce mutable data given a static input file and a static public key. I've exhausted pretty much every option I have to combine parameters and using a local pubkey or having `kubeseal` fetch it on the go, the gist of it stays as follows:

```shell
$ cat kustomize/base/http-basic-auth.seal | kubeseal --controller-namespace=system --controller-name=sealed-secrets --format=yaml --namespace=system -v 10
I0422 16:06:21.351912 1167323 loader.go:375] Config loaded from file:  /home/pngu/.kube/config
I0422 16:06:21.352227 1167323 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/x-pem-file, */*" -H "User-Agent: kubeseal/v0.0.0 (linux/amd64) kubernetes/$Format" 'https://123.123.123.123/api/v1/namespaces/system/services/http:sealed-secrets:/proxy/v1/cert.pem'
I0422 16:06:21.450997 1167323 round_trippers.go:443] GET https://123.123.123.123/api/v1/namespaces/system/services/http:sealed-secrets:/proxy/v1/cert.pem 200 OK in 98 milliseconds
I0422 16:06:21.451017 1167323 round_trippers.go:449] Response Headers:
I0422 16:06:21.451020 1167323 round_trippers.go:452]     Audit-Id: dbc974bd-6643-4499-8443-75c553b1e933
I0422 16:06:21.451023 1167323 round_trippers.go:452]     Cache-Control: no-cache, private
I0422 16:06:21.451025 1167323 round_trippers.go:452]     Content-Type: application/x-pem-file
I0422 16:06:21.451029 1167323 round_trippers.go:452]     Date: Thu, 22 Apr 2021 15:06:21 GMT
I0422 16:06:21.451032 1167323 round_trippers.go:452]     Content-Length: 1684
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: http-basic-auth
  namespace: system
spec:
  encryptedData:
    auth: AgCs6N [...] 0/hCJf
  template:
    metadata:
      creationTimestamp: null
      name: http-basic-auth
      namespace: system

$ cat sourceboat/kustomize/base/http-basic-auth.seal | kubeseal --controller-namespace=system --controller-name=sealed-secrets --format=yaml --namespace=system -v 10
I0422 16:09:16.386750 1205144 loader.go:375] Config loaded from file:  /home/pngu/.kube/config
I0422 16:09:16.387259 1205144 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/x-pem-file, */*" -H "User-Agent: kubeseal/v0.0.0 (linux/amd64) kubernetes/$Format" 'https://123.123.123.123/api/v1/namespaces/system/services/http:sealed-secrets:/proxy/v1/cert.pem'
I0422 16:09:16.503581 1205144 round_trippers.go:443] GET https://123.123.123.123/api/v1/namespaces/system/services/http:sealed-secrets:/proxy/v1/cert.pem 200 OK in 116 milliseconds
I0422 16:09:16.503601 1205144 round_trippers.go:449] Response Headers:
I0422 16:09:16.503609 1205144 round_trippers.go:452]     Cache-Control: no-cache, private
I0422 16:09:16.503615 1205144 round_trippers.go:452]     Content-Type: application/x-pem-file
I0422 16:09:16.503623 1205144 round_trippers.go:452]     Date: Thu, 22 Apr 2021 15:09:16 GMT
I0422 16:09:16.503629 1205144 round_trippers.go:452]     Content-Length: 1684
I0422 16:09:16.503637 1205144 round_trippers.go:452]     Audit-Id: 28e4fdf0-bef8-4cf7-9bef-6b73c8c30c6a
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: http-basic-auth
  namespace: system
spec:
  encryptedData:
    auth: AgA9Nb [...] M24wox
  template:
    metadata:
      creationTimestamp: null
      name: http-basic-auth
      namespace: system
```

**Comment by itspngu** [comment]
I'm having the exact same issue and after a lot of digging I realized that the secrets I seal locally are mutating - every run of `kubeseal` produces different values in `spec.encryptedData`. The certificate of the sealed-secrets controller itself is not changing. Is that the same for you? I'm awfully confused - there's no way `kubeseal` should produce mutable data given a static input file and a static public key. I've exhausted pretty much every option I have to combine parameters and using a local pubkey or having `kubeseal` fetch it on the go, the gist of it stays as follows:

```shell
$ cat kustomize/base/http-basic-auth.seal | kubeseal --controller-namespace=system --controller-name=sealed-secrets --format=yaml --namespace=system -v 10
I0422 16:06:21.351912 1167323 loader.go:375] Config loaded from file:  /home/pngu/.kube/config
I0422 16:06:21.352227 1167323 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/x-pem-file, */*" -H "User-Agent: kubeseal/v0.0.0 (linux/amd64) kubernetes/$Format" 'https://123.123.123.123/api/v1/namespaces/system/services/http:sealed-secrets:/proxy/v1/cert.pem'
I0422 16:06:21.450997 1167323 round_trippers.go:443] GET https://123.123.123.123/api/v1/namespaces/system/services/http:sealed-secrets:/proxy/v1/cert.pem 200 OK in 98 milliseconds
I0422 16:06:21.451017 1167323 round_trippers.go:449] Response Headers:
I0422 16:06:21.451020 1167323 round_trippers.go:452]     Audit-Id: dbc974bd-6643-4499-8443-75c553b1e933
I0422 16:06:21.451023 1167323 round_trippers.go:452]     Cache-Control: no-cache, private
I0422 16:06:21.451025 1167323 round_trippers.go:452]     Content-Type: application/x-pem-file
I0422 16:06:21.451029 1167323 round_trippers.go:452]     Date: Thu, 22 Apr 2021 15:06:21 GMT
I0422 16:06:21.451032 1167323 round_trippers.go:452]     Content-Length: 1684
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: http-basic-auth
  namespace: system
spec:
  encryptedData:
    auth: AgCs6N [...] 0/hCJf
  template:
    metadata:
      creationTimestamp: null
      name: http-basic-auth
      namespace: system

$ cat kustomize/base/http-basic-auth.seal | kubeseal --controller-namespace=system --controller-name=sealed-secrets --format=yaml --namespace=system -v 10
I0422 16:09:16.386750 1205144 loader.go:375] Config loaded from file:  /home/pngu/.kube/config
I0422 16:09:16.387259 1205144 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/x-pem-file, */*" -H "User-Agent: kubeseal/v0.0.0 (linux/amd64) kubernetes/$Format" 'https://123.123.123.123/api/v1/namespaces/system/services/http:sealed-secrets:/proxy/v1/cert.pem'
I0422 16:09:16.503581 1205144 round_trippers.go:443] GET https://123.123.123.123/api/v1/namespaces/system/services/http:sealed-secrets:/proxy/v1/cert.pem 200 OK in 116 milliseconds
I0422 16:09:16.503601 1205144 round_trippers.go:449] Response Headers:
I0422 16:09:16.503609 1205144 round_trippers.go:452]     Cache-Control: no-cache, private
I0422 16:09:16.503615 1205144 round_trippers.go:452]     Content-Type: application/x-pem-file
I0422 16:09:16.503623 1205144 round_trippers.go:452]     Date: Thu, 22 Apr 2021 15:09:16 GMT
I0422 16:09:16.503629 1205144 round_trippers.go:452]     Content-Length: 1684
I0422 16:09:16.503637 1205144 round_trippers.go:452]     Audit-Id: 28e4fdf0-bef8-4cf7-9bef-6b73c8c30c6a
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: http-basic-auth
  namespace: system
spec:
  encryptedData:
    auth: AgA9Nb [...] M24wox
  template:
    metadata:
      creationTimestamp: null
      name: http-basic-auth
      namespace: system
```

**Comment by haim-ari** [comment]
> I'm having the exact same issue and after a lot of digging I realized that the secrets I seal locally are mutating - every run of `kubeseal` produces different values in `spec.encryptedData`. The certificate of the sealed-secrets controller itself is not changing. Is that the same for you? I'm awfully confused - there's no way `kubeseal` should produce mutable data given a static input file and a static public key. I've exhausted pretty much every option I have to combine parameters and using a local pubkey or having `kubeseal` fetch it on the go, the gist of it stays as follows:
> 
> ```shell
> $ cat kustomize/base/http-basic-auth.seal | kubeseal --controller-namespace=system --controller-name=sealed-secrets --format=yaml --namespace=system -v 10
> I0422 16:06:21.351912 1167323 loader.go:375] Config loaded from file:  /home/pngu/.kube/config
> I0422 16:06:21.352227 1167323 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/x-pem-file, */*" -H "User-Agent: kubeseal/v0.0.0 (linux/amd64) kubernetes/$Format" 'https://123.123.123.123/api/v1/namespaces/system/services/http:sealed-secrets:/proxy/v1/cert.pem'
> I0422 16:06:21.450997 1167323 round_trippers.go:443] GET https://123.123.123.123/api/v1/namespaces/system/services/http:sealed-secrets:/proxy/v1/cert.pem 200 OK in 98 milliseconds
> I0422 16:06:21.451017 1167323 round_trippers.go:449] Response Headers:
> I0422 16:06:21.451020 1167323 round_trippers.go:452]     Audit-Id: dbc974bd-6643-4499-8443-75c553b1e933
> I0422 16:06:21.451023 1167323 round_trippers.go:452]     Cache-Control: no-cache, private
> I0422 16:06:21.451025 1167323 round_trippers.go:452]     Content-Type: application/x-pem-file
> I0422 16:06:21.451029 1167323 round_trippers.go:452]     Date: Thu, 22 Apr 2021 15:06:21 GMT
> I0422 16:06:21.451032 1167323 round_trippers.go:452]     Content-Length: 1684
> apiVersion: bitnami.com/v1alpha1
> kind: SealedSecret
> metadata:
>   creationTimestamp: null
>   name: http-basic-auth
>   namespace: system
> spec:
>   encryptedData:
>     auth: AgCs6N [...] 0/hCJf
>   template:
>     metadata:
>       creationTimestamp: null
>       name: http-basic-auth
>       namespace: system
> 
> $ cat kustomize/base/http-basic-auth.seal | kubeseal --controller-namespace=system --controller-name=sealed-secrets --format=yaml --namespace=system -v 10
> I0422 16:09:16.386750 1205144 loader.go:375] Config loaded from file:  /home/pngu/.kube/config
> I0422 16:09:16.387259 1205144 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/x-pem-file, */*" -H "User-Agent: kubeseal/v0.0.0 (linux/amd64) kubernetes/$Format" 'https://123.123.123.123/api/v1/namespaces/system/services/http:sealed-secrets:/proxy/v1/cert.pem'
> I0422 16:09:16.503581 1205144 round_trippers.go:443] GET https://123.123.123.123/api/v1/namespaces/system/services/http:sealed-secrets:/proxy/v1/cert.pem 200 OK in 116 milliseconds
> I0422 16:09:16.503601 1205144 round_trippers.go:449] Response Headers:
> I0422 16:09:16.503609 1205144 round_trippers.go:452]     Cache-Control: no-cache, private
> I0422 16:09:16.503615 1205144 round_trippers.go:452]     Content-Type: application/x-pem-file
> I0422 16:09:16.503623 1205144 round_trippers.go:452]     Date: Thu, 22 Apr 2021 15:09:16 GMT
> I0422 16:09:16.503629 1205144 round_trippers.go:452]     Content-Length: 1684
> I0422 16:09:16.503637 1205144 round_trippers.go:452]     Audit-Id: 28e4fdf0-bef8-4cf7-9bef-6b73c8c30c6a
> apiVersion: bitnami.com/v1alpha1
> kind: SealedSecret
> metadata:
>   creationTimestamp: null
>   name: http-basic-auth
>   namespace: system
> spec:
>   encryptedData:
>     auth: AgA9Nb [...] M24wox
>   template:
>     metadata:
>       creationTimestamp: null
>       name: http-basic-auth
>       namespace: system
> ```
> 
> I just realized it might make sense to leave my version info here aswell.
> 
> ```shell
> $ kubeseal --version
> kubeseal version: v0.15.0
> 
> $ flux get helmreleases -A
> NAMESPACE	NAME          	READY	MESSAGE                         	REVISION 	SUSPENDED
> [...]
> system   	sealed-secrets	True 	Release reconciliation succeeded	1.15.0-r3	False 
> ```
> 
> Controller logs look about as follows:
> 
> ```shell
> 2021/04/22 13:32:55 Event(v1.ObjectReference{Kind:"SealedSecret", Namespace:"stage", Name:"s3-creds", UID:"b92194fc-b57e-4d04-b5d5-33615f1de85e", APIVersion:"bitnami.com/v1alpha1", ResourceVersion:"961353", FieldPath:""}): type: 'Warning' reason: 'ErrUnsealFailed' Failed to unseal: no key could decrypt secret (port, region, scheme, secret, asset_host, bucket, host, key)
> ```

I see that my helm version is different:

```
kube-system  	sealed-secrets	True 	Release reconciliation succeeded	1.13.2  	False
```

I used:
```
helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
```

and all i have is:

```
helm search repo sealed-secrets/sealed-secrets --versions
NAME                         	CHART VERSION	APP VERSION	DESCRIPTION
sealed-secrets/sealed-secrets	1.13.2       	0.13.1     	A Helm chart for Sealed Secrets
```

**Comment by itspngu** [comment]
Yes, that's why I added to this issue - I seem to be running into the same troubles you have, but with a more recent controller version, and the same client version. I'm not sure how likely some weird regression in `kubeseal` is, but I was able to create secrets yesterday just fine.

Not relevant to the issue, but Helm does not show any releases past 1.13.2 due to incompatibilities between this chart's naming scheme and Helm's own conventions - they consider anything that has a suffix a development or unstable version. You can append `-l --devel` to your command to get the entire list.

**Comment by haim-ari** [comment]
@itspngu   Thanks for the info.
I'm not sure how to proceed from her... 
Is there a specific stable release which I can try for both client and controller ?
(will probably have to brew uninstall and install the client manually...) 

Could it be that something else is causing this ? some other dependence ? K8s version, OS version ?

probably does not matter but here it is 
I'm using 
```
RKE 2.5.7
Ubuntu 20.04
Kubernetes 1.20.5
Docker 20.0.6
```

**Comment by itspngu** [comment]
@haim-ari after even more digging I realized that it's expected for the secret contents to change because a nonse is appended to them - I've been chasing ghosts. #376

I have since gotten it to work again by

- finding the first occurance of the error
- realizing it (well, I) somehow managed to create a SealedSecret in a namespace that doesn't exist
- deleted the non-existing SealedSecret with `$ kubectl delete sealedsecret/wat -n doesntexist`
- yes, that actually happened
- afterwards i fixed up the helm chart following #571 - though probably irrelevant
- re-deployed everything, it works :)

I'm suspecting you might have a similar situation of it having gotten stuck on an invalid CRD. See also #505. Try running `$ kubectl get sealedsecret -A` and `$ kubectl describe`ing them to see if anything feels off - good luck!

**Comment by haim-ari** [comment]
@itspngu not sure what i'm missing here, there must be some resources which needs to be removed but I can't find them

```
kubectl get sealedsecret -A
No resources found
```

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: '0.15.0-r3'
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      interval: 1m
  values:
    sealed-secrets:
      fullnameOverride: "sealed-secrets-controller"
```

```
flux get helmreleases -n kube-system
NAME            READY   MESSAGE                                                         REVISION        SUSPENDED 
sealed-secrets  False   HelmChart 'flux-system/kube-system-sealed-secrets' is not ready                 False  
```

```
2021-04-23T05:16:30.470Z error HelmRelease/sealed-secrets.kube-system - Reconciler error Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io &#34;sealed-secrets&#34;: the object has been modified; please apply your changes to the latest version and try again
```

```
flux delete helmrelease sealed-secrets -n kube-system
► deleting helmreleases sealed-secrets in kube-system namespace
✔ helmreleases deleted
```

```
kubectl delete crd/sealedsecrets.bitnami.com
customresourcedefinition.apiextensions.k8s.io "sealedsecrets.bitnami.com" deleted
```

```
flux reconcile kustomization infrastructure  --with-source  
```

```
flux get helmreleases -n kube-system   
NAME            READY   MESSAGE                                                         REVISION        SUSPENDED 
sealed-secrets  False   HelmChart 'flux-system/kube-system-sealed-secrets' is not ready                 False  
```

```
flux logs --level error --kind helmrelease --name sealed-secrets -n kube-system 
```

```
2021-04-23T05:31:52.535Z error HelmRelease/sealed-secrets.kube-system - Reconciler error Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io &#34;sealed-secrets&#34;: the object has been modified; please apply your changes to the latest version and try again
```

**Comment by itspngu** [comment]
@haim-ari hmm, that's weird. My HelmRelease CRD is a little different:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: system
spec:
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      # TODO: ugh https://github.com/bitnami-labs/sealed-secrets/issues/523#issuecomment-804913116
      version: "1.15.0-r3"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: system
  interval: 10m
  values:
    #networkPolicy: true
    # https://github.com/bitnami-labs/sealed-secrets/issues/571#issue-863495808
    fullnameOverride: sealed-secrets-controller
```

fillnameOverride needs to be a property of `values`, not of a `sealed-secrets` sub-key.

I'm running cluster-wide stuff that's not core k8s components in the `system` namespace rather than following the advice given here to install it in `kube-system`, because I managed to have Flux delete itself before, and while that was not fun, I can't imagine how much fun it would be if Flux deleted calico and kubedns :joy:

I'm not sure what's stuck in your setup, but if I were you I'd try to remove sealed-secrets from git aswell, make sure all resources related to it are gone from the cluster, and then install it once more following the regular gitops workflow. Hope that helps.

**Comment by haim-ari** [comment]
@itspngu 

I cleaned up crd, redployed and it seems to work correctly now.

```
kubectl get sealedsecret -A 
```

```                                                                                master 
NAMESPACE    NAME      AGE
production   regcred   2m29s
```

```
kubectl get secret/regcred -n production
```

```
NAME      TYPE                             DATA   AGE
regcred   kubernetes.io/dockerconfigjson   1      4m56s
```

Thanks for your help

**Comment by abdennour** [comment]
@haim-ari are you sure you clean up CRD not CR ?
