### ISSUE TITLE
Installation using chocolatey

### ISSUE THREAD

**Issue by fcaraujo** [bitnami-labs/sealed-secrets#595]
Hey, I just had to install it on windows and I realized it's available to be installed via Homebrew and MacPorts.
So I wondered if there's an intention to add it as a `choco` package - I haven't done any of this before, but perhaps it's not that difficult and I can help with it?

**Comment by juan131** [comment]
Duplicate of https://github.com/bitnami-labs/sealed-secrets/issues/105
