### ISSUE TITLE
Few minor issues in v0.16.0 release

### ISSUE THREAD

**Issue by stevo-f3** [bitnami-labs/sealed-secrets#597]
- [ ] GitHub release https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.16.0 has link to 0.15.0 release notes
i.e. https://github.com/bitnami-labs/sealed-secrets/blob/master/RELEASE-NOTES.md#v0150 should be changed to https://github.com/bitnami-labs/sealed-secrets/blob/main/RELEASE-NOTES.md#v0160
- [ ] v0.16.0 release notes changelog has broken links to issues - e.g. instead of https://github.com/bitnami-labs/sealed-secrets/issues/#445 should point to https://github.com/bitnami-labs/sealed-secrets/issues/445 and similar for the second item in the changelog

cc @mkmik

**Comment by juan131** [comment]
Hi @stevo-f3 

I just edited the [v0.16.0 release](https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.16.0) to point to the right release notes. Thanks for reporting it.

The second issue was also fixed some time ago when refactoring the RELEASE-NOTES.md.
