### ISSUE TITLE
Kubeseal go-importable API (alternative to cli)

### ISSUE THREAD

**Issue by ghostsquad** [bitnami-labs/sealed-secrets#598]
I'm working on a Terraform Provider to create sealed secrets (just the manifest), and I'd like to avoid a dependency on the `kubeseal` binary. It seems to make this pure go, I'd have to grab quite a bit from `cmd/kubeseal/main.go`.

Thoughts on abstracting the meat in `main.go` into a pkg that can be used by other go clients?

**Comment by juan131** [comment]
Duplicate of https://github.com/bitnami-labs/sealed-secrets/issues/348
