### ISSUE TITLE
Backup of Keys went wrong  

### ISSUE THREAD

**Issue by h3rakl1t** [bitnami-labs/sealed-secrets#599]
Hello, we have a problem updating Secrets from version 0.13.1 to 0.16.0. After the update in our incubator cluster was finished and we had the keys restored, we got the error message: 
"Failed to unseal: no key could decrypt secret"
For every application 

We had a key in the old format and a second with a new format.

Backup was done exactly as it is in the instructions.

`$ kubectl get secret -n kube-system -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml >master.key`
`$ kubectl get secret -n kube-system sealed-secrets-key -o yaml >>master.key`

After several hours we decided to write the yaml file ourselves because we actually have the right keys.
We wrote the yaml file in the new format 

apiVersion: v1 
data:
  tls.crt: xxx
  tls.key: xxx
kind: Secret
metadata:
  annotations:
  creationTimestamp: "2021-06-09T17:40:49Z"
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
  name: sealed-secrets-key...
  namespace: kube-system
  resourceVersion: "17144361"
  selfLink: /api/v1/namespaces/kube-system/secrets/sealed-secrets-key...
type: kubernetes.io/tls

After that it worked, but what we also set is the label on active 

It works but we are not sure whether the yaml file is in the right format, we don't want to run into problems later in the production cluster

So the question would actually be, is the yaml file formatted correctly. We assume that the problem was also because of the label, which I mentioned above. 

What we would do is not to backup it according to the instructions, but we would write the yamls files ourselves that we would import after the update. We don't want the problems that we had in one cluster to have in another.

Is this the right thing to do as there seem to be problems when putting two keys that are in two different formats into one yaml file. 

Thanks!

**Comment by kevinyangI** [comment]
any update else？
