### ISSUE TITLE
Add custom labels to generated sealing key secrets

### ISSUE THREAD

**Issue by lanmarti** [bitnami-labs/sealed-secrets#616]
I'd like to add custom labels to the sealing key secrets generated by the controller, so one can easily retrieve all resources belonging to a specific application. Normally I use Kustomize to add common labels to existing manifests, however, as the secrets are generated by the controller at runtime, this is not an option here. Tools like ArgoCD also add labels to keep track of which resources belong to a given application, and if resource monitoring is activated, resources lacking matching labels are considered orphaned, meaning sealed key secrets would be considered orphaned.
I looked through existing issues and the general readme, but didn't find anything relevant.
Is there an option to add custom labels to the sealing key secrets, or would it be possible to provide such an option?

**Comment by mkmik** [comment]
In https://github.com/bitnami-labs/sealed-secrets#sealedsecrets-as-templates-for-secrets
you can see how to add labels and annotations to the secrets that will be generated from the sealed secret.

(please close the issue if this answered your question)

**Comment by lanmarti** [comment]
Perhaps I'm misunderstanding the documentation, but this seems to be on how to add annotations and labels to the secrets that are unwrapped from SealedSecrets.
I would like to add labels to the secrets that the controller generates for its signing keys (the ones that rotate every 30 days by default), i.e. the keys that are actually used to en/decrypt sealed secrets. The keys that can be found in same namespace as the controller, with naming scheme `sealed-secrets-key[5 character hash]`.

**Comment by mkmik** [comment]
ah sorry I misunderstood you.

indeed we currently cannot add a custom label/annotation for those secrets.

Usually, not being able to delete these secrets automatically as the controller gets uninstalled is actually a **useful feature**.
One of the common problems with sealed secrets is that if you accidentally uninstall the CRD all the sealed-secrets resources also get deleted. This is annoying but it's usually trivial to restore the sealed-secrets resources (since by design you'd have them in your git repos), but, if by uninstalling the sealed-secrets controller you also happened to delete the seal**ing** secrets, then you couldn't recover them.

This consideration puts this feature quite low in my priority queue, but I can be persuaded with a good argument or a with a good PR :-)

**Comment by lanmarti** [comment]
Retaining the keys after deleting the controller is indeed a useful feature and having thought about it some more, I'd say that for my use case as well, retaining the keys on accidental deletion probably outweighs the benefits of having a unified label and slightly easier resource management.

Considering I lack the time and golang knowledge to work on this feature, and the lack of customizable labels is not a roadblock for me, I will shelve my request.

I'll add my attempt at a good argument purely for the sake of discussion:
A label different than the ones used by the other Sealed Secret resources might provide the best of both worlds:
- deleting resources by specifying the common Sealed Secret label leaves the secrets with the signing keys intact
- signing keys secrets can sill be retrieved as a group through their custom label

With such a setup, tools that group resources by label would still be able to keep track of all resources of the controller, though it would be through 2 entries rather than one.
I'm playing with the idea of only giving my developers access to tools like ArgoCD, and no longer direct access to the Kubernetes clusters. Without a common label, the signing key secrets would either be invisible to those developers, or only appear as an orphaned resource. However, even I must admit that the number of use cases where a developer would need direct access to the signing key secrets would be very limited indeed.
