### ISSUE TITLE
Create a website to increase discoverability

### ISSUE THREAD

**Issue by kostis-codefresh** [bitnami-labs/sealed-secrets#623]
This project is great and many thanks for creating it :-)

Despite the engineering quality, it is very hard to find this project (and what it does) just by the Github presence. The blog post (at https://engineering.bitnami.com/articles/sealed-secrets.html) helps but it is not enough.

Are there any plans to create a proper website (e.g. sealed-secrets.dev, bitnami.com/secrets or something similar)? This website should contain at the very least a high level overview of the project, use cases, architecture diagram and so on.

I think this would increase adoption among engineers and developers.

**Comment by kostis-codefresh** [comment]
I still think this is needed. Especially for new users of Bitnami Sealed Secrets.

**Comment by juan131** [comment]
@agarcia-oss what do you think about this?

**Comment by agarcia-oss** [comment]
The issue was addressed by the static site PR https://github.com/bitnami-labs/sealed-secrets/pull/877
The static site can be found here: https://sealed-secrets.netlify.app/
