### ISSUE TITLE
GKE Autopilot support?

### ISSUE THREAD

**Issue by slavafomin** [bitnami-labs/sealed-secrets#624]
Hello!

Thank you for this great tool!

However, I was trying to deploy it to the GKE Autopilot cluster just to find out that it can't be done due to the [Autopilot limitations](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#limits).

Namely, the namespace `kube-system` is read-only and resources can't be created there. This produces the following error for multiple sealed secrets resources:

```
serviceaccounts is forbidden: User "system:serviceaccount:..." cannot create resource "serviceaccounts"
in API group "" in the namespace "kube-system": GKEAutopilot authz: the namespace "kube-system"
is managed and the request's verb "create" is denied
```

Is it possible to somehow work around this issue?

Thanks!

**Comment by mkmik** [comment]
yeah you can install it in other namespaces too.

The bundled yaml manifests come with kube-system by default and the `kubeseal` tool looks there by default to fetch the public key.

But many people install it on another namespace, either by using kustomize to override the namespace, or using the helm chart (which by default puts it in its own namespace IIRC).

Also read https://github.com/bitnami-labs/sealed-secrets#how-to-use-kubeseal-if-the-controller-is-not-running-within-the-kube-system-namespace to see how to use sealed secrets if it's installed outside of kube-system.

**Comment by jsoref** [comment]
Ideally this would be discussed here: https://github.com/bitnami-labs/sealed-secrets/blob/main/docs/GKE.md
