### ISSUE TITLE
[Helm] Ingress apiVersion to support "networking.k8s.io/v1"

### ISSUE THREAD

**Issue by AaronLuo3296** [bitnami-labs/sealed-secrets#639]
The Ingress API has graduated from beta to a stable API since Kubernetes 1.19. The ingress apiVersion in helm charts needs to support "networking.k8s.io/v1".

**Comment by alvneiayu** [comment]
hi @AaronLuo3296 

With our last chart release, this problem has been solved. Let us know if you can have any problem.

Thanks a lot

Álvaro

**Comment by juan131** [comment]
I proceed to close this since it's fixed at https://github.com/bitnami-labs/sealed-secrets/pull/687 and nobody complained about it using the chart version `2.x.x`. Feel free to reopen it if you require further assistance.
