### ISSUE TITLE
--scope namespace-wide automatically inserts uneditable namespace

### ISSUE THREAD

**Issue by brentspector** [bitnami-labs/sealed-secrets#643]
Issue: When attempting to use the --scope namespace-wide option with kubeseal, the resulting SealedSecret manifest automatically includes `namespace: default` in both the metadata and template. Attempting to remove or delete this field to apply the secret to a different namespace results in a failure to unseal. Attempting to override via `kubectl` fails as the namespace must be the one defined in the manifest.

Steps to Reproduce:
1. Create a generic secret. 
```
echo -n bar | kubectl create secret generic mysecret --dry-run=client --from-file=foo=/dev/stdin -o json >mysecret.json
```
2. Seal the secret using a certificate downloaded locally that matches the sealing key in the cluster (and has already been proven to work with both strict and cluster-wide scopes)
```
kubeseal --cert mycert.crt --scope namespace-wide <mysecret.json >mysealedsecret.json
```
3. Examine the output and note that `namespace: default` has been added to both metadata and template
```
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mysecret",
    "namespace": "default",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/namespace-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mysecret",
        "namespace": "default",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/namespace-wide": "true"
        }
      },
      "data": null
    },
    "encryptedData": {
      "foo": "AgAwGws5vbLCOLzht9r+biIJt+fDlAtFqAjriBmvoPchYoE1Kag0ijvK06o32z7/i3sG4C5yBAnKmS45x2GqvWIfSfh6r6kPuRZQPK3xPA7fQN1SiBRUXj165VT+WzDIb7wXJgr2atOd6k1h6qzRDfn8gKk88C9ddJ1vEfZIe1+hJgq8raKPhvbk+JTVdjpU95okI8Io/jgK+UB8fMr2OGw1PFYg04tFin5rY+AQ+ZpY1CLVT0D7YZCluRVilmkY2kvmF6AGTxJeOPX5r/lvSw8OTxX2OIayNUs74hA+bU5YVRi8/ElvB0+DWWqSwgOCKplVDx9Q36M3ikpXSCp1lItTpdopVoY2jtLCUBboqBkAX21xnAvfU0Xdv6A7UIUR9tExHq5qZV6vB3F+ek1bUqPWzgj9KrLht39gPrhwW0ixMCCC2h0fKWy5X/s4BEBoKRh2etUyuMygqGQL47g1YJhfAMRaxvkPPfTpiJ0vNrVQW8/3qbcXNNkt7wbGwV9QFN2pW6SPtfJ7oSwQ4LN6Z17EsPYG9OW6zRfzKvO90MgLE/hR5/4bcX2BjWUQdzGK+fdbwsQ8G4fI8Td1wP1I8vpuFei3209rR2Hw5eOzXzbYe+RxVn9kcYpma2f1Gzc5ZObmXDHk+n1rlfjzLif2irnCpV7gW9OkZx6sy0G4y75uFMUIqEvZ1HjfZDwVOuoxB6P64NQ="
    }
  }
}
```
4. Attempt to apply the secret via kubectl
```
kubectl apply -f mysealedsecret.json -n kube-system
```
which results in
```
error: the namespace from the provided object "default" does not match the namespace "kube-system". You must pass '--namespace=default' to perform this operation.
```
5. Attempt to edit `mysealedsecret.json` to remove the namespace, or edit it. Then deploy via `kubectl`.
6. Get the logs from `sealed-secrets-controller`
```
kubectl logs -n kube-system sealedsecrets-helm-sealed-secrets-54b7bcf9f5-w5ghg
```
which results in
```
2021/09/22 18:28:43 Updating kube-system/mysecret
2021/09/22 18:28:43 Error updating kube-system/mysecret, giving up: no key could decrypt secret (foo)
E0922 18:28:43.822850       1 controller.go:201] no key could decrypt secret (foo)
2021/09/22 18:28:43 Event(v1.ObjectReference{Kind:"SealedSecret", Namespace:"kube-system", Name:"mysecret", UID:"d2e6c833-8a5f-4190-ac89-18f27789adeb", APIVersion:"bitnami.com/v1alpha1", ResourceVersion:"404676", FieldPath:""}): type: 'Warning' reason: 'ErrUnsealFailed' Failed to unseal: no key could decrypt secret (foo)
```

Expected Result:
Using `--scope namespace-wide` would not insert a namespace and/or would let the secret get deployed to something declared during cluster application.

**Comment by juan131** [comment]
As @tewfik-ghariani mentioned, you must use the flag `--namespace` to set namespace in the the SealedSecret's manifest (and associated Secret)

> but I would prefer if kubeseal prompted for a namespace or was loud about the lack of one

The [Usage section](https://github.com/bitnami-labs/sealed-secrets#usage) documents the CLI behavior regarding this topic, see:

> `kubeseal` reads the namespace from the input secret, accepts an explicit `--namespace` arg, and uses the `kubectl` default namespace (in that order). Any labels, annotations, etc on the original Secret are preserved, but not automatically reflected in the `SealedSecret`.

Feel free to send a PR improving the README.md if you think it's not clear enough.
