### ISSUE TITLE
Existed Secret is deleted.

### ISSUE THREAD

**Issue by Mohab-Elhawawshy** [bitnami-labs/sealed-secrets#644]
I faced an issue with an already decrypted secret.I needed to update the secret but pushed wrongfully encrypted sealedsecret so it couldn't update the secret with the new values but the original secret was already there and it is got deleted and don't know how.

Error logs from the controller

`E0910 13:46:49.972231       1 streamwatcher.go:109] Unable to decode an event from the watch stream: read tcp 100.118.177.11:49494->100.64.0.1:443: read: connection timed out
W0910 13:46:50.096902       1 reflector.go:334] github.com/bitnami-labs/sealed-secrets/cmd/controller/controller.go:120: watch of *v1alpha1.SealedSecret ended with: too old resource version: 1522189480 (1522198630)`

`W0910 13:37:07.609454       1 reflector.go:334] github.com/bitnami-labs/sealed-secrets/cmd/controller/controller.go:120: watch of *v1alpha1.SealedSecret ended with: very short watch: github.com/bitnami-labs/sealed-secrets/cmd/controller/controller.go:120: Unexpected watch close - watch lasted less than a second and no items received`

`E0910 13:37:54.668165       1 reflector.go:205] github.com/bitnami-labs/sealed-secrets/cmd/controller/controller.go:120: Failed to list *v1alpha1.SealedSecret: Get https://100.64.0.1:443/apis/bitnami.com/v1alpha1/sealedsecrets?resourceVersion=0: dial tcp 100.64.0.1:443: getsockopt: connection refused`

Sealed Secret controller version: `0.7.0` 
Kubernetes version: `1.10.3`

Is upgrading sealed secret version will solve the issue ? also is this related to kubernetes version ?

**Comment by juan131** [comment]
To be addressed at https://github.com/bitnami-labs/sealed-secrets/issues/224
