### ISSUE TITLE
Usage of sealed secret to encrypt gitlab runner token

### ISSUE THREAD

**Issue by anauecuri** [bitnami-labs/sealed-secrets#646]
Hi all,

I am trying to use sealed secret to encrypt my gitlab runner token, but I am receiving the following message:

`The SealedSecret "runnerToken" is invalid: metadata.name: Invalid value: "runnerToken": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

Does anybody know what might be?

Thank you.

**Comment by mkmik** [comment]
The error message clearly states that the capital letter "T" in the name is not a valid name for a k8s resource. 

Closing because this is not a SealedSecret specific issue: all k8s resources must follow that naming rule
