### ISSUE TITLE
avoid ingress version incompatible with 1.22

### ISSUE THREAD

**Issue by davidkarlsen** [bitnami-labs/sealed-secrets#654]
ingresses.v1beta1.networking.k8s.io is dropped in k8s 1.22
can maybe use https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_capabilities.tpl#L73 to make the version dynamic?

**Comment by jpetazzo** [comment]
This seems to be a duplicated of #639 and addressed in #641.

**Comment by alvneiayu** [comment]
hi @davidkarlsen and @jpetazzo 

With our last chart release, this problem has been solved. Let us know if you have any problem.

Thanks a lot

**Comment by juan131** [comment]
Closing as duplicate of #639

**Comment by davidkarlsen** [comment]
> hi @davidkarlsen and @jpetazzo
> 
> With our last chart release, this problem has been solved. Could you give a try, please? Let us know if you have any problem.

Thanks, the ingress problem got solved, however this new on appeared:
https://github.com/bitnami-labs/sealed-secrets/issues/694

**Comment by jpetazzo** [comment]
Same here, will follow up on #694 !
