### ISSUE TITLE
Offline workflow not working

### ISSUE THREAD

**Issue by adluste** [bitnami-labs/sealed-secrets#658]
Hi all,

regarding to the docs in README, it should be possible to download the public certificate and use it offline:

"_An alternative workflow is to store the certificate somewhere (e.g. local disk) with kubeseal --fetch-cert >mycert.pem, and use it offline with kubeseal --cert mycert.pem. The certificate is also printed to the controller log on startup._"

I was able to download the public certificate, but the second part of this statement does not work for me.
When I use `kubeseal --cert mycert.pem`, it says `tty detected: expecting json/yaml k8s resource in stdin`

Can someone please give advice?

**Comment by knweiss** [comment]
I think you just need to supply a full command line e.g. `kubeseal --cert mycert.pem <mysecret.json >mysealedsecret.json` i.e. provide a secret to seal on stdin (and an SealedSecret output file on stdout).
