### ISSUE TITLE
Release v0.17.0 automation is broken

### ISSUE THREAD

**Issue by mkmik** [bitnami-labs/sealed-secrets#661]
The normal day to day PR CI has been migrated to GitHub Actions long time ago.
However, the release automation is still on travis (because it needed the tokens for quay and for gh I can no longer generate).

Today I cut release v0.17.0 but the travis automation apparently failed. 
I no longer have access to travis (now that it has migrated to travis-ci.com) so I don't know why it fails.

The GH CI integration tests are also broken (we cannot reproduce it locally); so it could be that the release CI also fails in the same way, or perhaps it fails because of a different reason.

CC: @beltran-rubo

**Comment by bakito** [comment]
the kubeseal binary was not released with v0.17.0

The release notes point to a binary file that is not available.
```
wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.0/kubeseal-linux-amd64 -O kubeseal
sudo install -m 755 kubeseal /usr/local/bin/kubeseal

```
This might be related with the broken release automation.

**Comment by PerArneng** [comment]
> 
> 
> the kubeseal binary was not released with v0.17.0
> 
> The release notes point to a binary file that is not available.
> 
> ```
> wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.0/kubeseal-linux-amd64 -O kubeseal
> sudo install -m 755 kubeseal /usr/local/bin/kubeseal
> ```
> 
> This might be related with the broken release automation.

This is also what i got. Can't download the binary 

```
$ wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.0/kubeseal-linux-amd64
--2021-11-16 15:58:01--  https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.0/kubeseal-linux-amd64
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-11-16 15:58:01 ERROR 404: Not Found.

```

**Comment by r0bj** [comment]
The same with cluster yaml manifest:
```
$ wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.0/controller.yaml
--2021-11-17 13:04:29--  https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.0/controller.yaml
Resolving github.com (github.com)... 192.30.255.112
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-11-17 13:04:30 ERROR 404: Not Found.
```

**Comment by 44int** [comment]
Hi guys.
When will it fix?

**Comment by beltran-rubo** [comment]
Sorry for the delay, the team is working on fixing the CI/CD issues to complete this release, there is not any ETA yet.

**Comment by armenr** [comment]
...Ouch. :-(

This has our own pipelines backed up too :*(

**Comment by mkmik** [comment]
@armenr I'm curious now; how does this stuck release affect your pipeline? (other than not being able to use this release?)

@beltran-rubo, @juan131  should we mark the release as `This is a pre-release` until we get to build the artifacts? IIRC setting this flag will remove the release from the results of a release list call in the GitHub API,

**Comment by armenr** [comment]
@mkmik - k8s newb here. I was fiddling with a platform implementation on ArgoCD & thought that the reason my sync was failing was due to releases being broken...then realized I can use 1.16.1 perfectly fine...

**Comment by wenerme** [comment]
@mkmik This blocked my auto sync pipeline, 

https://github.com/wenerme/container-mirror/blob/92745e29a38fbb02623c6eb0c92f6616979b6a24/scripts/sync.sh#L43-L44 

cause the deploy fail https://github.com/wenerme/kube-stub-cluster/blob/main/sealed-secrets/kustomization.yaml have to disable sync sealed-secrets

**Comment by juan131** [comment]
Hi everyone!

I'm very glad to announce that we could finally fix the automations to publish new image release after migration the process to GH actions, and the version `v0.17.0` was just released in Quay. See:

- https://github.com/bitnami-labs/sealed-secrets/runs/4520737849

```console
$ docker pull quay.io/bitnami/sealed-secrets-controller:v0.17.0
$ docker manifest inspect quay.io/bitnami/sealed-secrets-controller:v0.17.0
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 738,
         "digest": "sha256:477e72b1ce4bdc09916ebda76055d06bccdc92944b2e7e87eab438d11857eea3",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 738,
         "digest": "sha256:8124056d3b407d1a95c303a14e3530f5f31e26dd8fc4415caca04013807df963",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

**Comment by mkmik** [comment]
Thanks @alvneiayu and @juan131 !
