### ISSUE TITLE
Is it possible for the operator to unseal a sealed secret and merge it into an existing secret?

### ISSUE THREAD

**Issue by SimonGurney** [bitnami-labs/sealed-secrets#663]
I have a use case where I want to provide a key to a secret, but this secret is also used by the application for internal cert/key storage and is therefore is a little dynamic.

I do not want sealed-secrets to overwrite it completely (which I think the manage annotation will do) but instead just merge my key in.

Is this possible?

**Comment by mkmik** [comment]
Not currently, but it is an interesting feature!

It could be modeled as a generalization of the "managed" secrets annotation, which allows sealed secrets controller to overwrite an existing secret. We could extend that annotation to describe whether (and how) to merge instead of overwriting.

**Comment by Velociraptor85** [comment]
Is this closed with https://github.com/bitnami-labs/sealed-secrets/pull/1259 ?

**Comment by alemorcuq** [comment]
Yes! Thanks for noticing, @Velociraptor85
