### ISSUE TITLE
Multiple Controllers in one Cluster

### ISSUE THREAD

**Issue by tillbier** [bitnami-labs/sealed-secrets#673]
**Which component**:
Controller: v0.16.0

**Is your feature request related to a problem? Please describe.**
Two separate groups of devops shall be able to encrypt/decrypt with different keys. As of my understanding, two separate controllers would be needed for that. When i try to deploy a second controller i receive the following error: 
`Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "secrets-unsealer" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata`

**Describe the solution you'd like**
A controller should be deployable either for only its namespace or for the entire cluster. There can be one namespace specific controller per namespace and one cluster controller per cluster.

**Comment by juan131** [comment]
Duplicate of https://github.com/bitnami-labs/sealed-secrets/issues/622
