### ISSUE TITLE
Helm Chart 0.17.0

### ISSUE THREAD

**Issue by fculpo** [bitnami-labs/sealed-secrets#679]
Hi,

Could you publish a new helm chart with version 0.17.0 ?

Thanks

**Comment by gabegorelick** [comment]
Also reported in https://github.com/bitnami-labs/sealed-secrets/issues/678#issuecomment-994210493.

**Comment by juan131** [comment]
Hi everyone! Thanks for reporting, this is a consequence of moving the release process to GH actions. I'll work on fixing this ASAP.

**Comment by fculpo** [comment]
thanks !

**Comment by juan131** [comment]
Hi everyone, a new chart major version for Sealed Secrets was just released. Please note this major version includes an important chart refactorization. Find more info in the links below:

- https://github.com/bitnami-labs/sealed-secrets/tree/main/helm/sealed-secrets#to-200
- https://github.com/bitnami-labs/sealed-secrets/pull/687
- https://github.com/bitnami-labs/sealed-secrets/releases/tag/helm-v2.0.0

```console
$ helm repo update sealed-secrets
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "sealed-secrets" chart repository
Update Complete. ⎈Happy Helming!⎈
$  helm search repo sealed-secrets/sealed-secrets
NAME                         	CHART VERSION	APP VERSION	DESCRIPTION
sealed-secrets/sealed-secrets	2.0.0        	v0.17.1    	Helm chart for the sealed-secrets controller.
```
