### ISSUE TITLE
linux/arm image missing since 0.17

### ISSUE THREAD

**Issue by ViBiOh** [bitnami-labs/sealed-secrets#691]
**Which component**:

Docker image controller

**Describe the bug**

The `0.16` Docker image was available for `linux/arm` but the new `0.17` is only available for `linux/arm64`. I don't see any informations related to this in the RELEASES_NOTES.md. Did you drop the support for it or a problem in the continuous integration?

**To Reproduce**

1. Go to [quay.io](https://quay.io/repository/bitnami/sealed-secrets-controller?tag=latest&tab=tags)
4. See error `linux/arm` image for `0.16` and not for `0.17`

**Expected behavior**

A `0.17` linux/arm Docker image

**Comment by alvneiayu** [comment]
hi @ViBiOh 

We have changed the CI/CD and this is a bug, thanks a lot for reporting it. I already created the PR to include it in our new release support.

Again, thanks a lot

Álvaro
