### ISSUE TITLE
enhance sealed-secrets workflow with integrating cosign into it

### ISSUE THREAD

**Issue by developer-guy** [bitnami-labs/sealed-secrets#696]
**Which component**:
The name (and version) of the affected component (controller or kubeseal)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

[cosign](https://github.com/sigstore/cosign) is a tool for signing and verifying container images, blobs, etc. So, we'd enhance the main workflow of sealed secrets by adding these two new steps: signing/verifying. This means that we can store the content of the secret manifest files in OCI registries.

> https://github.com/sigstore/k8s-manifest-sigstore

The main workflow will look like this: encrypt/sign --> decrypt/verify. So, people will sign the secret manifest file right after they encrypt. Then, sealed secrets will verify it right after it decrypts.

**Describe alternatives you've considered**

**Additional context**

cc: @dentrax

**Comment by agarcia-oss** [comment]
Closing the issue since we already support [cosign verification](https://github.com/bitnami-labs/sealed-secrets#how-to-verify-the-images) for both the `controller` and `kubeseal` components
