### ISSUE TITLE
Helm chart 2.0.2 seems to lacks list verb for secrets in cluster role

### ISSUE THREAD

**Issue by cmeury** [bitnami-labs/sealed-secrets#708]
**Which component**: Helm Chart

**Describe the bug**
The helm chart version 2.0.2 contains a cluster role with the following rule, among others:
```yaml
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - update
      - delete
```

On a Kubernetes cluster with version `v1.21.5`, this is seemingly not enough, as the controller states upon start:

```
panic: secrets is forbidden: User "system:serviceaccount:kube-system:sealed-secrets" cannot list resource "secrets" in API group "" in the namespace "kube-system"

goroutine 1 [running]:
main.main()
	/home/runner/work/sealed-secrets/sealed-secrets/cmd/controller/main.go:271 +0x225
```
 
Adding `list` to the verbs resolves the issue.

**Additional context**
Curiously enough, it looks like this popped before: https://github.com/helm/charts/issues/15837

**Comment by juan131** [comment]
Thanks for reporting it @cmeury ! I'll send a PR to address a couple of RBAC issues we recently discovered.
