### ISSUE TITLE
Applying/Creating sealed secrets failure

### ISSUE THREAD

**Issue by ssro** [bitnami-labs/sealed-secrets#71]
Hi everyone,

Just ran into this issue on k8s v1.9.0. This is a fresh kops instalation of k8s with RBAC enabled. I'm creating sealed secrets from an yaml file. While trying to apply the json sealed secrets file i get:

```
validation failure list:
spec.data in body should match '^[^A-Za-z0-9+/=]*$'
```
Tried with `--validate=false`, but i get the same result as above.
If I apply the yaml file only, it goes through (of course it's not a sealed secret anymore)

As a reference, the yaml file contents below:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test
type: Opaque
data:
  SECRET: U0VDUkVU
```

Kubectl version

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

Any ideas?

**Comment by anguslees** [comment]
Oh wow, it seems the CRD validation feature actually reached beta for 1.9 (and hence has been enabled on your cluster by default).  This is great.

What is less great, is that it seems the regex in the schema is completely wrong, and whatever testing I had done when implementing this was utterly inadequate :(

`'^[^A-Za-z0-9+/=]*$'`  should of course be `'^[A-Za-z0-9+/=]*$'`  (remove the `^` character class negation)

I'd be grateful if you could make the above change manually in your cluster and confirm that this is all that is wrong.  Something like the following should do:
```sh
kubectl patch crd sealedsecrets.bitnami.com --type merge -p '
spec:
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            data:
              pattern: ^[A-Za-z0-9+/=]*$
'
```

**Comment by ssro** [comment]
Hi @anguslees,

Patched as per your suggestion:

```
$ kubectl patch crd sealedsecrets.bitnami.com --type merge -p '
> spec:
>   validation:
>     openAPIV3Schema:
>       properties:
>         spec:
>           properties:
>             data:
>               pattern: ^[A-Za-z0-9+/=]*$
> '
customresourcedefinition "sealedsecrets.bitnami.com" patched
```

All went fine here. Then I've applied the sealed secret. It's the same as in my example above.

```bash
$ kubectl apply -f secret.json
sealedsecret "test" created
```

Trying to get the secret...

```bash
$ kubectl get secrets -n default
NAME                  TYPE                                  DATA      AGE
default-token-s7mwg   kubernetes.io/service-account-token   3         1h
```
Hmm, there is no sealed secret. But If I apply the secret using the namespace argument, the sealed secret gets created:

```bash
$ kubectl apply -f secret.json -n default
sealedsecret "test" configured

$ kubectl get secrets -n default
NAME                  TYPE                                  DATA      AGE
default-token-s7mwg   kubernetes.io/service-account-token   3         1h
test             Opaque                                1         57s

$ kubectl describe secret test
Name:         test
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
SECRET:  6 bytes
```

So in conclusion your patch worked. On the other hand, even if the `namespace` is declared in the yaml file, before converting it into a json sealed secret, it won't apply/create the sealed secret into that namespace unless the namespace argument is passed to kubectl.

The yaml secret file:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: default
type: Opaque
data:
  SECRET: U0VDUkVU
```

The json sealed secret:

```json
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "test",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "data": "AgCdPGiTrIEUU0g4t/VdS0xh+uL2ba7sTGKSbB1u7Jd/02KbSDQCndBRMI/fTdDt7IZjiU0N7ya7zfIkQTCnI1ZaWIXqL8WZxNLLXpVsN8kBjkJOHVxPdAD3InA4mfcTNQ2H7S6RLt8jxjtTxfBXCpcBkoQs+/iVBm7w+LfX6eLTa3pQ48hk9vvITpqRsW0rq3eTGoNEqke8gJ4ZRQyjLEvE5TETZywrsmNS2BFPDmFeJWRb3xnM3e2s2XEWzDHDTN9bt1/ev1fCpDNDKB1Ygjq07teIPyMWutXOWkVL6sXvuhN03kqgGL1eU3U+HIi11e8nj60OB47jdgYOyLJEZiQOrFC0KH3IQXdREgz1Jv1anEUxdwFeiqz+95QizTW4gPKZAM2BA7IFtnpOOoe5dUbctxVNBKC+4bYljfawqUhMeXRc/GzfYliM3GOeExQ6mWCSUw+73EutX6JCdU8VD/scs4f9no4GyoVMb2A3Ymig6pQ9r+GnMFwJ5TANyUS3Km1pqBBh0/Btcm3h8ZNuuo94TmtepNM39il7UF5nTxUmtfCFCEZUVfvqKSP5AwvX4/3eCcEeWmvmq25Y9cdwRlcmKF4+V4f/f6FV6IcgrsutfI6yeQwH7kpM6LPeEWpTXK2UJbs5scO1HOCOboj/nZPkxaJguQ1xKqqeZSIaCWWuO2iIXbRRy2+JSdb1VbxNy1Wstnea5itwqcp5SxukjQdMcV1DfRp6wxDC0o2kf/EKQnyOQXApRbJEydvumAlkVKp1e9gMr1i7tJ/QH3zn5Fs/BPXSZppLHGP610c/CJZoic3SKC1aCWRo+R/Jf1HlRUD/8EUrdMkoymhOZxqoggakDC6gknlHsOc3nmTCLaq+A6TM9oikhvm+laXLzal9/ikkA+YUdej9K46PocuyU7Us"
  }
}
```

Also i get a warning from the sealed secrets controller while creating the sealed secrets:

```
2017/12/19 05:24:45 HTTP server serving on :8080
W1219 05:32:46.515662       1 reflector.go:323] github.com/bitnami/sealed-secrets/cmd/controller/controller.go:126: watch of *v1alpha1.SealedSecret ended with: too old resource version: 6114 (6399)
2017/12/19 05:32:47 Updating default/test
```

**Comment by anguslees** [comment]
Thanks for the detailed report - I'll need to try to reproduce this locally to see what's going wrong with the namespace.  There's been some issues in the past with how client-go and kubectl handle the priority of the namespace flag vs namespaces in input, and we might have some variation of that again :(

Fwiw I'm working on adding some integration tests which should cover your use case above, and then I can use this to exercise sealed-secrets across multiple k8s versions rather than just my usual development cluster.  Hopefully that will mean we catch things like your original v1.9.0 validation bug earlier.

----

The "watch .. ended with: too old resource version" warning is just k8s api noise - it means the "watch" operation aborted because the SealedSecret resource was updated while the controller was trying to reconnect.  This is a normal thing to happen, and the listwatcher has code to deal with resyncing in this situation - it just prints this log message as it does so.

If you get this warning *frequently* (several times per second), then it is always falling into this out-of-sync situation, and that's an issue.  Seeing this _occasionally_ is normal.

**Comment by ssro** [comment]
Hi @anguslees ,

The warning got printed once when applying the sealed secret the first time. On updating the warning doesn't show up. I will be doing some more tests, since I would like to migrate to 1.9.0 from 1.8.5, but the sealed secrets are working properly (to me it doesn't matter too much that i have to specify the namespace to apply the secret) and thus this issue can be closed whenever convenient.

Thanks!

**Comment by burnettk** [comment]
@sebgoa @anguslees this issue appears to be preventing us from upgrading to kubernetes 1.9. i'm curious about the status, thanks!

**Comment by anguslees** [comment]
@burnettk My apologies for the delay.  The fix got merged into some other changes, and then those changes turned out to be larger and longer than expected.

The direct fix for this issue was just merged in #78 and I'll cut a release containing this shortly..

**Comment by anguslees** [comment]
@burnettk v0.6.0 released a few hours ago.

**Comment by burnettk** [comment]
that's great news, thanks, @anguslees !
