### ISSUE TITLE
Allow a user to know whether the controller actually unsealed a secret

### ISSUE THREAD

**Issue by mkmik** [bitnami-labs/sealed-secrets#72]
Some users can create/read the sealedsecrets resource kind but they cannot list the secrets on the api server nor tail the logs of the sealed secrets controller (e.g. because of RBAC); it's currently impossible to know whether the secret has been successfully unsealed.

Possible ideas: events and/or a "status" section (like pods, deployments etc)

```
status:
  secret:
    created: True
```

(I was also wondering about the `condition` objects but it seems they might be going away https://github.com/kubernetes/kubernetes/issues/7856)

**Comment by anguslees** [comment]
Big +1, I just haven't got around to this yet :(

We should definitely report Events on success/errors to allow debugging.  A status field in the object is good for automation, but not well supported by CRDs.  I think we should add some sort of "Ready" status, but there _will_ be races in how this is updated vs the Spec - so some idempotent statement ("last unsealed version" or similar) would also be good..
