### ISSUE TITLE
Unable to re-encrypt secrets with error: 'cannot re-encrypt secret: no endpoints available for service "http:sealed-secrets:"'

### ISSUE THREAD

**Issue by koneill94** [bitnami-labs/sealed-secrets#722]
**Which component**:
Sealed secrets controller v0.17.2 and kubeseal version 0.17.2

**Describe the bug**
I'm attempting some DR testing and when I run the following command:  
` kubeseal --controller-namespace sealed-secrets --controller-name sealed-secrets --re-encrypt < sealed-secret2.yaml > tmp.yaml`

It returns error: cannot re-encrypt secret: no endpoints available for service "http:sealed-secrets:"

I had originally had the problem described here: https://github.com/bitnami-labs/sealed-secrets/issues/694 but upgrading kubeseal to 0.17.2 fixed this however when I attempt re-encryption of a sealed secret it occurrs.

**To Reproduce**

1. Deploy sealed-secrets app to sealed secrets namespace using helm chart version 2.1.0
2. Create a test sealed secret with original key
3. Force the controller to generate a new key
4. Disable original key
5. Attempt to re-encrypt secret using `kubeseal --controller-namespace sealed-secrets --controller-name sealed-secrets --re-encrypt < sealed-secret2.yaml > tmp.yaml`

**Expected behavior**
I expect the tmp.yaml to include a re-encrypted secret.

**Version of Kubernetes**:

```
Client Version: 4.8.18
Server Version: 4.8.24
Kubernetes Version: v1.21.6+c180a7c
```

**Comment by juan131** [comment]
Thanks so much for reporting this @koneill94 !! I just send a PR to address it
