### ISSUE TITLE
kubeseal and role "sealed-secrets-service-proxier" does not allow to retrieve services

### ISSUE THREAD

**Issue by avthart** [bitnami-labs/sealed-secrets#744]
**Which component**:
kubeseal and sealed-secrets helm-chart

**Describe the bug**

```
error: cannot get sealed secret service: services "sealed-secrets" is forbidden: User "xyz" cannot get resource "services" in API group "" in the namespace "sealed-secrets"
```

Kubeseal 0.17.3 will list all services within the sealed-secrets namespace before it will create a proxy. The role "sealed-secrets-service-proxier" created by the helm-chart does not allow that.

See

* https://github.com/bitnami-labs/sealed-secrets/blob/a509b7054df8410d0581f8086fc02098a442c154/cmd/kubeseal/main.go#L181
* https://github.com/bitnami-labs/sealed-secrets/blob/v0.17.3/helm/sealed-secrets/templates/role.yaml#L50

**To Reproduce**

* Install sealed-secrets and kubeseal using version 0.17.3
* Use kubeseal as non cluster-admin to create a `SealedSecret`

**Expected behavior**

There a two options to fix this:

* kubeseal must only create proxy without listing services
* add list/get to role "sealed-secrets-service-proxier"

**Version of Kubernetes**:

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:14:17Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:46:22Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @avthart 

Shouldn't this be solved with the changes introduced at https://github.com/bitnami-labs/sealed-secrets/pull/715?

**Comment by avthart** [comment]
@juan131 You are right. I was looking at the git tag 0.17.3 for the helm chart templates. I had to switch to helm-v2.1.3
