### ISSUE TITLE
Container arguments list can no longer be extended in helm chart

### ISSUE THREAD

**Issue by tewfik-ghariani** [bitnami-labs/sealed-secrets#753]
**Which component**:

Helm Chart

**Describe the bug**

The list of container arguments used to be defined via `commandArgs` that extends the list of other pre-defined arguments ( like `updateStatus`, `keyrenewperiod ` .. ) 

However, due to the recent change per https://github.com/bitnami-labs/sealed-secrets/pull/734/files#diff-aac94a436c20224e24f87b8c85f3a453aad85bc68e40d93068e04f578449a847R52 , the new `args` property overrides the full list

**To Reproduce**

I am using the `--my-cn` argument that has been introduced per : https://github.com/bitnami-labs/sealed-secrets/pull/564

_common.yml_

```
args:
  - --my-cn
  - "Custom Controller"
```

The diff with the current state :
```
     spec:
       containers:
       - args:
-        - --update-status
-        - --key-renew-period
-        - "0"
-        - --key-prefix
-        - sealed-secrets-pub-key
+        - --my-cn
+        - Custom Controller
```

**Expected behavior**

I would expect to either revert the change and make it possible to extend the list of arguments via `args` or have a new argument for that specific _my-cn_ property

**Comment by mkmik** [comment]
I don't know much about the helm chart, but perhaps you can use the flag to env var mapping. E.g. `--update-status` -> `SEALED_SECRETS_UPDATE_STATUS=1`

**Comment by tewfik-ghariani** [comment]
That will not be enough since there is no specific argument for the `--my-cn` parameter

The issue described is mainly caused by the PR : https://github.com/bitnami-labs/sealed-secrets/pull/734 so maybe @juan131 might have an idea

**Comment by armingerten** [comment]
> I don't know much about the helm chart, but perhaps you can use the flag to env var mapping. E.g. `--update-status` -> `SEALED_SECRETS_UPDATE_STATUS=1`

Unfortunately, the helm chart (currently) does not provide any possibility to pass extra environment variables to the controller container. That would be an easy enhancement to the chart though ...

see also: https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/templates/deployment.yaml#L44

**Comment by juan131** [comment]
Hi @armingerten 

Have you tried using a **common.yml** such as this one?

```yaml
args:
  - --update-status
  - --key-renew-period
  - "0" 
  - --key-prefix
  - sealed-secrets-pub-key
  - --my-cn
  - "Custom Controller"
```

I mean, you can overwrite all the command args, but it doesn't prevent you to add the default ones.

**Comment by tewfik-ghariani** [comment]
@juan131 yes that is the method I opted for eventually

The issue was created to highlight the fact that the behavior changed from extending the arguments list to overriding it

If that is done by design and is the expected behavior that this issue can be closed

Thanks for the follow-up

**Comment by juan131** [comment]
Yes @tewfik-ghariani ! It's an intended decision. The current approach allows both to extend & overwrite the args, while the previous one only allowed to extend the args but it wasn't possible to remove the default ones.

**Comment by stevo-f3** [comment]
@juan131 please consider (reopening this ticket and) covering [this breaking change](https://github.com/bitnami-labs/sealed-secrets/pull/734/) in the https://github.com/bitnami-labs/sealed-secrets/tree/main/helm/sealed-secrets#upgrading section

**Comment by stevo-f3** [comment]
Created release process improvement request https://github.com/bitnami-labs/sealed-secrets/issues/1001
