### ISSUE TITLE
Panic on sealing when built with Go 1.18

### ISSUE THREAD

**Issue by Hades32** [bitnami-labs/sealed-secrets#757]
**Which component**:
kubeseal

**Describe the bug**
panic with Go 1.18 RC1. Tested working with Go 1.17.3

**Version of Kubernetes**:

```
$ kubectl --context do-nyc1-ua-utility-cluster version                                   
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:45:53Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Repro:**

Input file:
```
apiVersion: v1
data:
  dsn: aGVsbG8K
kind: Secret
metadata:
  name: crdb-dsn
  namespace: default
type: Opaque
```

Run this command and get the crash

```
$ cat secrets.yml | kubeseal --context do-nyc1-ua-utility-cluster --format yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4113bc]

goroutine 1 [running]:
reflect.mapiternext(0xc00020cbd0?)
        /home/h32/.gvm/gos/go1.18rc1/src/runtime/map.go:1378 +0x19
github.com/modern-go/reflect2.(*UnsafeMapIterator).UnsafeNext(0x7f91b0fcd108?)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:136 +0x32
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc0003f5d40, 0xc000348338, 0xc00016a360)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_map.go:297 +0x31a
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x10a7680?, 0xc000362d01?, 0xc00016a378?)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:332 +0x22
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc000319950, 0x10849d4?, 0xc00016a360)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x56
github.com/json-iterator/go.(*structEncoder).Encode(0xc00035a030, 0x415501?, 0xc00016a360)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x765
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc00035bf50, 0xff8b5c?, 0xc00016a360)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x56
github.com/json-iterator/go.(*structEncoder).Encode(0xc00037c090, 0x0?, 0xc00016a360)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x765
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc0001da960?, 0x0?, 0x0?)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_optional.go:70 +0xa4
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc0004c1410, 0xc000348280, 0xc0003f5590?)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:219 +0x82
github.com/json-iterator/go.(*Stream).WriteVal(0xc00016a360, {0x11b36a0, 0xc000348280})
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x158
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc0001da960, {0x11b36a0, 0xc000348280})
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/config.go:299 +0xc9
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0xfde437?, {0x1393d68?, 0xc000348280?}, {0x1390e60, 0xc0003f5530})
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/runtime/serializer/json/json.go:306 +0x6d
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc00003caa0, {0x1393d68, 0xc000348280}, {0x1390e60, 0xc0003f5530})
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/runtime/serializer/json/json.go:301 +0xfc
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0xc0001501e0, {0x1393d68?, 0xc000348280}, {0x1390e60, 0xc0003f5530})
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/runtime/serializer/versioning/versioning.go:244 +0x8fa
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc0001501e0, {0x1393d68, 0xc000348280}, {0x1390e60, 0xc0003f5530})
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/runtime/serializer/versioning/versioning.go:184 +0x106
k8s.io/apimachinery/pkg/runtime.Encode({0x7f91882c7f38, 0xc0001501e0}, {0x1393d68, 0xc000348280})
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/runtime/codec.go:50 +0x64
main.resourceOutput({0x1392460, 0xc000010018}, {0xc0001ea0e0, {0x1391d60, 0xc00000eb70}, {0xc0001ce600, 0x3, 0x4}, {0x13a2108, 0xc00003ca00}}, ...)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/bitnami-labs/sealed-secrets@v0.17.3/cmd/kubeseal/main.go:411 +0x125
main.sealedSecretOutput(...)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/bitnami-labs/sealed-secrets@v0.17.3/cmd/kubeseal/main.go:421
main.seal({0x1392440, 0xc000010010}, {0x1392460, 0xc000010018}, {0xc0001ea0e0, {0x1391d60, 0xc00000eb70}, {0xc0001ce600, 0x3, 0x4}, ...}, ...)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/bitnami-labs/sealed-secrets@v0.17.3/cmd/kubeseal/main.go:302 +0x674
main.run({0x13a2b00, 0xc000040098}, {0x1392460?, 0xc000010018}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/bitnami-labs/sealed-secrets@v0.17.3/cmd/kubeseal/main.go:741 +0xc4e
main.main()
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/bitnami-labs/sealed-secrets@v0.17.3/cmd/kubeseal/main.go:748 +0x33b
```

Ran on linux/amd64

**Comment by agarcia-oss** [comment]
Thanks for the heads up, @Hades32! We don't have any short term plan to upgrade our build dependency to go 1.18.x, but we surely will review this issue when the time comes. I'll close the issue for the time being.

**Comment by Hades32** [comment]
Well, I guess you don't officially endorse this, but I find installing `kubeseal` via `go install github.com/bitnami-labs/sealed-secrets/cmd/kubeseal@v0.17.3` far easier than manually downloading, extracting, and installing the binaries from the releases.

That's why I even found this, and I guess once 1.18 is released more people might hit this. (Assuming of course this is not a bug in RC1)

**Comment by mkmik** [comment]
This dep seem to have a relevant release https://github.com/modern-go/reflect2/releases/tag/v1.0.2:

> fix go 1.18 compatibility

**Comment by Hades32** [comment]
Yep, already created a PR for the dep upgrade

**Comment by phuongatemc** [comment]
We hit similar panic stack with when we tried to Encode an Object.  We only hit problem when use go 1.18.3  If we switched back to 1.17.10, we didn't see the panic.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x41189c]

goroutine 1 [running]:
reflect.mapiternext(0xc0002db050?)
	/home/phuong/.mvnGoLang/go1.18.3.linux-amd64/src/runtime/map.go:1378 +0x19
github.com/modern-go/reflect2.(*UnsafeMapIterator).UnsafeNext(0x7f3bbe8fe108?)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:136 +0x32
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc0001e17d0, 0xc000176ec8, 0xc00044b920)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/reflect_map.go:297 +0x31a
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x16f2b20?, 0xc0004a2401?, 0xc00044b938?)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/reflect.go:332 +0x22
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0001e1c80, 0x14f8606?, 0xc00044b920)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x56
github.com/json-iterator/go.(*structEncoder).Encode(0xc0001e1d10, 0x415a01?, 0xc00044b920)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x765
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0001eb260, 0x14c127e?, 0xc00044b920)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x56
github.com/json-iterator/go.(*structEncoder).Encode(0xc0001eb320, 0x0?, 0xc00044b920)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x765
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc0002c8dc0?, 0x0?, 0x0?)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/reflect_optional.go:70 +0xa4
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc0001e6b10, 0xc000176d80, 0xc0004ab740?)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/reflect.go:219 +0x82
github.com/json-iterator/go.(*Stream).WriteVal(0xc00044b920, {0x19d2ba0, 0xc000176d80})
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x158
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc0002c8dc0, {0x19d2ba0, 0xc000176d80})
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/config.go:299 +0xc9
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0x14f81c6?, {0x1c6d440?, 0xc000176d80?}, {0x1c69860, 0xc0001cdb30})
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/k8s.io/apimachinery@v0.22.2/pkg/runtime/serializer/json/json.go:306 +0x6d
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc000140c30, {0x1c6d440, 0xc000176d80}, {0x1c69860, 0xc0001cdb30})
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/k8s.io/apimachinery@v0.22.2/pkg/runtime/serializer/json/json.go:301 +0xfc
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0xc00015bea0, {0x1c6d440?, 0xc000176d80}, {0x1c69860, 0xc0001cdb30})
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/k8s.io/apimachinery@v0.22.2/pkg/runtime/serializer/versioning/versioning.go:244 +0x8fa
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc00015bea0, {0x1c6d440, 0xc000176d80}, {0x1c69860, 0xc0001cdb30})
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/k8s.io/apimachinery@v0.22.2/pkg/runtime/serializer/versioning/versioning.go:184 +0x106
dellemc.com/ppdm/kubernetes/ppdmctl/cmd/common.Encode({0x7ffe2b7a631c, 0x4}, {0x1c6d440, 0xc000176d80})
	/home/phuong/work/vproxy-kubernetes/golang/controller/src/ppdmctl/cmd/common/common.go:83 +0xd3
dellemc.com/ppdm/kubernetes/ppdmctl/cmd/applicationtemplate.GetApplicationTemplate({0x1c7cb88, 0xc00013e000}, {0x1c6d418?, 0xc0004b71e0?}, {0x7ffe2b7a6305, 0x5}, {0x7ffe2b7a630b, 0xd}, {0x7ffe2b7a631c, 0x4})
	/home/phuong/work/vproxy-kubernetes/golang/controller/src/ppdmctl/cmd/applicationtemplate/get.go:138 +0x105
dellemc.com/ppdm/kubernetes/ppdmctl/cmd/applicationtemplate.runGet(0xc0000b6300?, {0xc0003df5e0, 0x1, 0xc0000b6300?}, 0xc00016a140, {0x7ffe2b7a6305, 0x5}, {0x7ffe2b7a631c, 0x4})
	/home/phuong/work/vproxy-kubernetes/golang/controller/src/ppdmctl/cmd/applicationtemplate/get.go:73 +0x229
dellemc.com/ppdm/kubernetes/ppdmctl/cmd/applicationtemplate.NewGetCommand.func1(0xc0003fb900?, {0xc0003df5e0?, 0x5?, 0x5?})
	/home/phuong/work/vproxy-kubernetes/golang/controller/src/ppdmctl/cmd/applicationtemplate/get.go:35 +0x3b
github.com/spf13/cobra.(*Command).execute(0xc0003fb900, {0xc0003df0e0, 0x5, 0x5})
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/spf13/cobra@v1.2.1/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003fb400)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/home/phuong/work/vproxy-kubernetes/golang/controller/src/ppdmctl/main.go:28 +0x37
phuong@irv-vm-90-22 ~/work/vproxy-kubernetes/golang/controller (PPDM-186162) # target/ppdmctl applicationtemplate get -n mysql mysqltemplate -o yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x41189c]

goroutine 1 [running]:
reflect.mapiternext(0xc0002bb050?)
	/home/phuong/.mvnGoLang/go1.18.3.linux-amd64/src/runtime/map.go:1378 +0x19
github.com/modern-go/reflect2.(*UnsafeMapIterator).UnsafeNext(0x7f71d77e05b8?)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:136 +0x32
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc0005d5170, 0xc000620808, 0xc0000959e0)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/reflect_map.go:297 +0x31a
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x16f2b20?, 0xc00048a401?, 0xc0000959f8?)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/reflect.go:332 +0x22
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0005d5620, 0x14f8606?, 0xc0000959e0)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x56
github.com/json-iterator/go.(*structEncoder).Encode(0xc0005d56b0, 0x415a01?, 0xc0000959e0)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x765
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0005d8c00, 0x14c127e?, 0xc0000959e0)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x56
github.com/json-iterator/go.(*structEncoder).Encode(0xc0005d8cc0, 0x0?, 0xc0000959e0)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x765
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc0002aae60?, 0x0?, 0x0?)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/reflect_optional.go:70 +0xa4
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc0005d13d0, 0xc0006206c0, 0xc0002bb4a0?)
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/reflect.go:219 +0x82
github.com/json-iterator/go.(*Stream).WriteVal(0xc0000959e0, {0x19d2ba0, 0xc0006206c0})
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x158
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc0002aae60, {0x19d2ba0, 0xc0006206c0})
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/github.com/json-iterator/go@v1.1.11/config.go:299 +0xc9
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0x14f81c6?, {0x1c6d440?, 0xc0006206c0?}, {0x1c69860, 0xc000495470})
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/k8s.io/apimachinery@v0.22.2/pkg/runtime/serializer/json/json.go:306 +0x6d
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc00009ec80, {0x1c6d440, 0xc0006206c0}, {0x1c69860, 0xc000495470})
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/k8s.io/apimachinery@v0.22.2/pkg/runtime/serializer/json/json.go:301 +0xfc
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0xc00061a320, {0x1c6d440?, 0xc0006206c0}, {0x1c69860, 0xc000495470})
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/k8s.io/apimachinery@v0.22.2/pkg/runtime/serializer/versioning/versioning.go:244 +0x8fa
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc00061a320, {0x1c6d440, 0xc0006206c0}, {0x1c69860, 0xc000495470})
	/home/phuong/work/vproxy-kubernetes/golang/controller/.external-resources/goModCache/k8s.io/apimachinery@v0.22.2/pkg/runtime/serializer/versioning/versioning.go:184 +0x106
dellemc.com/ppdm/kubernetes/ppdmctl/cmd/common.Encode({0x7ffe4826c31c, 0x4}, {0x1c6d440, 0xc0006206c0})
