### ISSUE TITLE
Verify and update our GitHub Actions dependencies

### ISSUE THREAD

**Issue by agarcia-oss** [bitnami-labs/sealed-secrets#762]
**Which component**:
None. This is a GH actions pipelines improvement.

**Describe the bug**
GitHub Actions are part of our Build and Release pipelines, and we must ensure that we use up to date versions of the Actions and that we always use Actions from verified sources (Actions provided by GitHub or from verified provider of the GH actions Marketplace).

**To Reproduce**
N/A

**Expected behaviour**
Project GH actions only use verified Actions. 
Actions to replace from equivalent of verified providers:

- opsgang/ga-setup-minikube@v0.1.1
- andymckay/labeler@1.0.4

**Comment by RishiKumarRay** [comment]
I would like to work on this

**Comment by agarcia-oss** [comment]
Hi @RishiKumarRay! Very much appreciated 🙇  

You can start by reviewing the project current [GitHub Actions ](https://github.com/bitnami-labs/sealed-secrets/tree/main/.github/workflows) and look for [GitHub and Marketplace verified](https://github.com/marketplace?type=actions&verification=verified_creator) alternatives for the `labeler` and `ga-setup-minikube` actions
