### ISSUE TITLE
Discrepancy of defaults for controller name between Helm chart and CLI needs resolved

### ISSUE THREAD

**Issue by ngbrown** [bitnami-labs/sealed-secrets#767]
This has been brought up several times, such as #424, #571, #626, #630, and #758. Instead of only commenting on those closed issues, it seemed that the best course of action is to open a new issue and propose a possible path.

The Helm chart, by default, installs the controller with the name `sealed-secrets`, while the command line interface (CLI) tries to access the controller with the name `sealed-secrets-controller`.

The helm chart could be updated with a `fullnameOverride` value, or the CLI user could always pass `--controller-name sealed-secrets`. But this is just adding friction to enjoying this project. Right off the bat, someone new has to start troubleshooting something that could be resolved by the project ahead of time.

Pick a preferred path and then output a warning in either the Helm chart or the CLI based on whichever one is wrong. Or the value could be made as required in either area or both areas, breaking, but with a clear error, those upgrading and not currently setting the value.

The CLI has the option of falling back and trying both names, while continuing to work for all users. It should print out a warning if it has to fall back to the non-preferred name (whatever is in the default Helm chart).

Also, this doesn't seem to be clearly addressed in the FAQ or really anywhere besides issues in this repo. The option, `--controller-name`, isn't even mentioned in the [readme](https://github.com/bitnami-labs/sealed-secrets/blob/main/README.md).

**Comment by juan131** [comment]
Hi @ngbrown 

Thank you for your feedback!!

> The Helm chart, by default, installs the controller with the name sealed-secrets, while the command line interface (CLI) tries to access the controller with the name sealed-secrets-controller.

That's not 100% accurate, it depends on the release name you choose when installing the chart. For instance, if you install the chart with the release name `my-release`, the service name is `my-release-sealed-secrets`:

```console
$ helm install my-release sealed-secrets/sealed-secrets
...
$ kubectl get service
NAME                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
my-release-sealed-secrets   ClusterIP   10.227.244.138   <none>        8080/TCP   21s
```

> The helm chart could be updated with a `fullnameOverride` value, or the CLI user could always pass `--controller-name sealed-secrets`.

Correct! These are the mechanisms we offer to adapt the service name using the chart or the CLI.

> Pick a preferred path and then output a warning in either the Helm chart or the CLI based on whichever one is wrong.

There's not a valid name and a wrong name. The Sealed Secrets controller is exposed through a service and users are free to choose any desired name for that service.

> But this is just adding friction to enjoying this project. Right off the bat, someone new has to start troubleshooting something that could be resolved by the project ahead of time.

I don't fully agree with that, the Helm installation notes clearly specify the flags to use in the CLI depending on the release name you chose. Following the previous example:

```console
$ helm install my-release sealed-secrets/sealed-secrets
...
** Please be patient while the chart is being deployed **

You should now be able to create sealed secrets.

1. Install the client-side tool (kubeseal) as explained in the docs below:

    https://github.com/bitnami-labs/sealed-secrets#installation-from-source

2. Create a sealed secret file running the command below:

    kubectl create secret generic secret-name --dry-run=client --from-literal=foo=bar -o [json|yaml] | \
    kubeseal \
      --controller-name=my-release-sealed-secrets \
      --controller-namespace=default \
      --format yaml > mysealedsecret.[json|yaml]

The file mysealedsecret.[json|yaml] is a commitable file.
...
```

It shouldn't be necessary to troubleshoot but simply read the installation notes.

> Also, this doesn't seem to be clearly addressed in the FAQ or really anywhere besides issues in this repo. The option, `--controller-name`, isn't even mentioned in the [readme](https://github.com/bitnami-labs/sealed-secrets/blob/main/README.md).

Good point! We should definitely mention this flag in the README.md, would you like to contribute with a PR explaining how to use it?

**Comment by brsolomon-deloitte** [comment]
I opened #774 to add bare-minimum documentation, but I strongly agree with @ngbrown and all of the other issues that have been raised -- why needlessly create this confusing obstacle to initial usage?

When installing with tools such as ArgoCD and using "sealed-secrets" as the application name, the resulting controller name is simply `sealed-secrets`. This is not an edge case; it is a common case.

There seem to be multiple options with varying degrees of backwards compatibility, such as (1) a "fallback" search for `sealed-secrets` or (2) appending `-controller` to the default Deployment name.

**Comment by lindhe** [comment]
I'd like to bring this up again. I agree fully with @ngbrown that this is very unexpected behavior that introduces friction, especially for new users.

I see that you, @juan131 , have given an explanation to this, but I don't quite follow. Can you please help me understand why it does not make sense to change the Helm chart's default naming of the service? Unless I'm mistaken, that's all that's needed.

Is it to avoid resource collision when deploying multiple releases of the Helm chart in the same namespace? That sounds like a fairly unusual scenario compared to the scenario of "running `kubeseal` without special flags to make it work"…

@josvaz and @alemorcuq what are your input to this? I saw that you introduced this helpful addition to the README: https://github.com/bitnami-labs/sealed-secrets/commit/7d06e8140522651cd87def4698231b56ee123597
