### ISSUE TITLE
operator not listed on OpenShift 4.9 operator catalog

### ISSUE THREAD

**Issue by itewk** [bitnami-labs/sealed-secrets#768]
**Which component**:
The operator.

**Is your feature request related to a problem? Please describe.**
The operator is not listed in the OpenShift 4.9 operator catalog.

**Describe the solution you'd like**

Due to the kube api changes between 4.8 and 4.9 all operators in the OLM catalog were set to a max support version of 4.8 then relying on the communiteis to vet their operators against 4.9 and put in a request to remove the restruction.

See: https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/sealed-secrets-operator-helm/0.0.1/sealed-secrets-operator-helm.v0.0.1.clusterserviceversion.yaml#L5-L12

Assuming the operator does indeed work on 4.9, then request that someone put in the request to remove the 4.8 max version restruction.

**Describe alternatives you've considered**
none.

**Additional context**
See https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/sealed-secrets-operator-helm/0.0.1/sealed-secrets-operator-helm.v0.0.1.clusterserviceversion.yaml#L5-L12

**Comment by alvneiayu** [comment]
hi @itewk 

Unfortunately, we are not maintaining this operator. So we can not help you on this.

https://github.com/bitnami-labs/sealed-secrets#operator-framework

 I suggest you to contact directly with the maintainer of the operator.

Thanks a lot and sorry again

Álvaro

**Comment by itewk** [comment]
bummer. It looks like that maintainer has stopped maintaining the operator. I would then suggest maybe you all update your docs to not include the operator as an option.
