### ISSUE TITLE
tls-secret generated with helm template while running on Openshift 

### ISSUE THREAD

**Issue by sravankumar777** [bitnami-labs/sealed-secrets#769]
**Which component**:
Controller

**Describe the bug**
While executing helm template --debug <releasename> <sealed secrets helm template>, output does not show the generation of [tls-secret](https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/templates/tls-secret.yaml) object. 
Configured both values of tls & selfSigned as true to respect the if condition [here](https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/templates/tls-secret.yaml#L17)

**To Reproduce**
1. Generate helm charts using helm template --debug against the sealed secret charts on Openshift Kubernetes Cluster. 
```
helm template --debug sealed-secrets SealedSecrets/
```
Note: In my case, I have copied all files from [here](https://github.com/bitnami-labs/sealed-secrets/tree/main/helm/sealed-secrets) into a separate folder and executed the above command. 

**Expected behavior**
While using helm template against the provided SealedSecrets helm templates and with necessary configuration tls and selfSigned, tls-secret object information should be provided. 

**Version of Openshift Kubernetes**:
Openshift 4.4 with Kubernetes v1.21.6. 
- Output of `kubectl version`:
N/A

**Comment by sravankumar777** [comment]
Added sealed-secrets-template output here. 
[SealedSecrets-Template.txt](https://github.com/bitnami-labs/sealed-secrets/files/8220049/SealedSecrets-Template.txt)

**Comment by alvneiayu** [comment]
hi @sravankumar777 

Try enabling these keys:
- ingress.enabled: true
- ingress.tls: true
- ingress.selfSigned: true

Command example:

helm template temp . --set ingress.enabled=true --set ingress.tls=true --set ingress.selfSigned=true

I can generate the template for the ingress and tls-secret without problem with those keys.

Thanks a lot

Álvaro

**Comment by sravankumar777** [comment]
@alvneiayu , thanks your response. 
With this change, I am able to see the Secret object being created using helm. 

With respect to ingress, I have another query. 
Does this mean, SealedSecrets does only work with ingress being enabled. 
Currently on OpenShift platform which is being used for testing, Ingress controller is not being used. 

In these case, helm chart template for tls-secret.yaml is required to be updated as **or** condition instead **and**. 
https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/templates/tls-secret.yaml#L1

**Comment by alvneiayu** [comment]
hi @sravankumar777 

Sorry but I am missing something here. Those are the tls secret generated to use it in the ingress. Just to have secure communication using the ingress. 

Sealed Secret is not going to use it at all. Sealed Secret has the own way to generate the certificate. So you can use Sealed Secret without ingress. tls secret files is going to be used only for the TLS communications in the Ingress.

Thanks

Álvaro
