### ISSUE TITLE
Release for darwin/arm64

### ISSUE THREAD

**Issue by brandonSc** [bitnami-labs/sealed-secrets#780]
Hi folks, would it be possible to have a `darwin/arm64` release of sealed-secrets for M1 Mac users?

Install via Homebrew works, however, my use case involves downloading the prebuilt binary inside a Docker image.

Thanks!

**Comment by mkmik** [comment]
just to clarify: you'd like a darwin/arm64 binary in the GH release page, something like `https://github.com/bitnami-labs/sealed-secrets/releases/download/${version}/kubeseal-${version}-darwin-arm64.tar.gz` ?

**Comment by brandonSc** [comment]
Yes, exactly!

**Comment by mkmik** [comment]
I think we already added it in https://github.com/bitnami-labs/sealed-secrets/pull/752
I guess it will be there when we cut the next release

**Comment by mkmik** [comment]
FWIW, the `v0.17.4` is very close, see https://github.com/bitnami-labs/sealed-secrets/pull/777

**Comment by brandonSc** [comment]
Perfect, I guess I missed that 🙂 thanks
