### ISSUE TITLE
helm RBAC should be more restrictive

### ISSUE THREAD

**Issue by TheKangaroo** [bitnami-labs/sealed-secrets#827]
**Which component**:
controller

**Describe the bug**
This PR https://github.com/bitnami-labs/sealed-secrets/pull/715 added the `get service` permission to `system:authenticated` which is needed to lookup the named port of the service.
While this works as expected I think the helm chart is missing the restriction to the resource name of the service. This in turn will allow every authenticated user to `get` any service in the same namespace as sealed-secrets is deployed.

**Expected behavior**
I think this should be limited to just "sealed-secrets-controller" like in the `controller.jsonnet` file in the same PR.

**Additional context**
I'll happily provide a PR fix for this :)

**Comment by alemorcuq** [comment]
Thanks for creating a PR! Let's continue there.
