### ISSUE TITLE
"Bitnami Sealed-secrets controller" version for OCP 4.9.x (Kubernetes 1.22).

### ISSUE THREAD

**Issue by umeshcloud** [bitnami-labs/sealed-secrets#840]
Dear team 
     I'm trying to find supported "bitnami Sealed-secrets controller" version for OCP 4.9 (Kubernetes 1.22). 

Current version using - 0.15.x

Thank you for your help.

**Comment by agarcia-oss** [comment]
Hi @umeshcloud,

We're running our [Integration tests](https://github.com/bitnami-labs/sealed-secrets/blob/main/.github/workflows/ci.yml#L142) for the controller using Kubernetes 1.22 as one of our target platforms. So, OCP 4.9 should be fully supported. 

(Please notice that the latest controller version is [0.17.5](https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.17.5))

**Comment by umeshcloud** [comment]
Thank you agarcia-oss.
Do we have any online link where I can go and refer Sealed-secret-controller & kubernetes  supported version mapping. 
In Bitnami doc page , Getting list for all available versions however each sealed-secrets version compatible to which Kubernetes version could not find details there.

Thanks again for helping on this.
