### ISSUE TITLE
Retire link to Sealed Secrets Operator (Helm) in README?

### ISSUE THREAD

**Issue by yrro** [bitnami-labs/sealed-secrets#843]
**Which component**:
README

**Describe the bug**
The Sealed Secrets Operator (Helm) project has not been maintained since [April 2020](https://github.com/disposab1e/sealed-secrets-operator-helm/commit/99644bc274015231160b91da668e08fec756eda8). The operator is not compatible with k8s >= 1.22. Maybe it's time to remove the link to this project from the installation instructions? Or maybe it would be less confusing to say that it's been retired and shouldn't be used?

**Comment by davecore82** [comment]
What should users who have installed Sealed Secrets with the operator do to move to a new official installation method?

**Comment by yrro** [comment]
> What should users who have installed Sealed Secrets with the operator do to move to a new official installation method?

I'd try backing up all the seal secrets controller's secrets (see the FAQ in the README), remove the operator (and any bits it might leave behind), re-install it using the new method & then store the secrets.
