### ISSUE TITLE
Windows build of kubeseal CLI

### ISSUE THREAD

**Issue by brantb** [bitnami-labs/sealed-secrets#85]
I use Windows, and have been using the `kubeseal` tool by using the Linux build with [WSL](https://docs.microsoft.com/en-us/windows/wsl/about), but it would be nice if a native Windows binary was available.

**Comment by Hades32** [comment]
v0.7 win build
[kubeseal.zip](https://github.com/bitnami-labs/sealed-secrets/files/2098562/kubeseal.zip)

**Comment by shahiddev** [comment]
Does this mean there is a windows build already?

**Comment by anguslees** [comment]
> Does this mean there is a windows build already?

There is no official windows build (yet), but I imagine you can build it from source easily (once you have the [windows go toolchain](https://golang.org/dl/)).

If there is some reason a windows build doesn't Just Work, please report it - since fixing the source is obviously a precursor to shipping useful binaries.  And I don't have access to windows platforms for testing personally.

**Comment by Hades32** [comment]
The build I attached above was built on Linux with GOOS=windows set and it works just fine. So it should be no problem to include windows binaries as part of your (next) release

**Comment by kskewes** [comment]
Indeed, see #134 and related PR #140 .

**Comment by spencerolsen** [comment]
Any update on how to install with Windows? I downloaded the installer from above and it didn't work for me. I'm not familiar with go, so I'd prefer to not have to dive into it if possible.

**Comment by mkmik** [comment]
https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.8.0-rc.1 release contains an official windows binary

**Comment by brantb** [comment]
@mkmik This is wonderful, thank you! It looks like [the v0.8.0 release](https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.8.0) is missing the Windows binary, though. :)

**Comment by mkmik** [comment]
@brantb I marked it pre-release until I upload the windows binary manually

**Comment by jordan-owen** [comment]
For anyone that needs to automate this, I made a PowerShell [script](https://github.com/jordan-owen/kubeseal-windows-installer) for automating the installation on Windows for users. It gets the latest Windows release, unpacks and adds to PATH.
