### ISSUE TITLE
no key could decrypt secret

### ISSUE THREAD

**Issue by de-slalonde** [bitnami-labs/sealed-secrets#850]
**Which component**:
SealedSecrets / kubeseal 0.17.4

**Describe the bug**
Very rarely, when I update a secret (just one of several), in the logs I see `Error updating <namespace>/<secrets>, will retry: no key could decrypt secret (<secret>)`

I've read the other issues and I couldn't find anything that applies to me.

**To Reproduce**

I have a script that is updating the secret with the following command:

```
echo -n <actualsecretvalue> | kubectl -n <namespace> create secret generic \
<secret> --dry-run=client --from-file=<secret>=/dev/stdin \
-o yaml | kubeseal --format yaml \
--controller-name=<my-controller> \
--merge-into ./<existing_ss_yaml_file>;
```

This has worked fine, completely unchanged in about 58/60 times we've done it. But twice we've crashed into the error updating.

**Expected behavior**
Secret is able to be updated

**Version of Kubernetes**:

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10-gke.2000", GitCommit:"0823380786b063c3f71d5e7c76826a972e30550d", GitTreeState:"clean", BuildDate:"2022-03-17T09:22:22Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by de-slalonde** [comment]
The best option I can come up with right now to maybe avoid this is to recreate all my secrets completely instead of trying to just update one and merge it in. But I'd love a better idea.

**Comment by alvneiayu** [comment]
hi @de-slalonde 

I can not reproduce your problem with the script shared. Are you doing something else? I mean, applying the sealed secret or something else?

Please, share with me the steps that you are following to reproduce (one by one).

Thanks a lot

Álvaro

**Comment by de-slalonde** [comment]
Yes, after running the command I mentioned, I am applying it with `kubectl apply -f <existing_ss_yaml_file>`. It happens so rarely, I'm not able to reproduce it. 

I updated my code slightly, using `--from-literal` instead of echo/pipe/--from-file. I haven't seen a repeat since then.  It's very strange.

```
kubectl -n <namespace> create secret generic \
<secret> --dry-run=client --from-literal=<secret>=<actualsecretvalue> \
-o yaml | kubeseal --format yaml \
--controller-name=<my-controller> \
--merge-into ./<existing_ss_yaml_file>;
```

**Comment by alvneiayu** [comment]
hi @de-slalonde 

Thanks a lot for the info. Well, I still can't reproduce it but I am going to investigate a little bit (and try to reproduce it).

Álvaro

**Comment by alvneiayu** [comment]
hi @de-slalonde 

Sorry, I was testing this week and I can not reproduce the problem, sorry. Maybe, it was a connectivity problem or a temporally problem in the pod?

Thanks

Álvaro
