### ISSUE TITLE
Status shows `no key could decrypt secret` for successful created secret

### ISSUE THREAD

**Issue by yildizbilal** [bitnami-labs/sealed-secrets#853]
**Which component**:
kubeseal: v0.17.4
sealed-secret-controller: v0.17.5
kubernetes: 1.22.6

**Describe the bug**
The `status` feature, where you can see if the creation of a secret through the controller was successful or not is partly not correct. In this case the status says `message: no key could decrypt secret (<key>)` but the `logs` and `events` of the controller says `SealedSecret unsealed successfully`.

<img width="560" alt="Screen Shot 2022-06-01 at 18 38 26" src="https://user-images.githubusercontent.com/106691526/171456492-53bfa110-abbc-4586-bd6a-386463ec34a8.png">

**To Reproduce**
- upgrade the controller from v0.12.4 to v0.17.5
- Restart the pod
- compare `status` and `controller log` or `events` entries

**Expected behavior**
When the creation was successful the `status` should show `SealedSecret unsealed successfully` like the logs and the `events`.

**Version of Kubernetes**:

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"07959215dd83b4ae6317b33c824f845abd578642", GitTreeState:"clean", BuildDate:"2022-03-30T18:28:25Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1
```

**Additional context**
I am not sure if i misunderstood the `status` feature 🤔.

**Comment by RobMokkink** [comment]
I have the exact same issue. We tested it many times, the scope for the secrets is set correctly.

**Comment by alvneiayu** [comment]
hi @RobMokkink and @yildizbilal 

Let me investigate a little bit about it. I will come back as soon as possible.

Thanks

Álvaro

**Comment by alvneiayu** [comment]
hi, I am trying to reproduce the issue but I can not. Could you provide me more information or steps to reproduce it?

Are you upgrading the pod and then apply the new sealed secret?

Thanks a lot and sorry for the inconveniences.

Álvaro

**Comment by yildizbilal** [comment]
@alvneiayu We are using the helm-controller by flux so we updated the helm chart and the controller updated helm chart and deployed through the helm release the new application version. Because of api changes the helm release was not able to deploy properly so I deleted it and a new helm release was triggered and the new application version could be deployed correctly.

**Comment by alvneiayu** [comment]
perfect @yildizbilal, let me try to reproduce it. I will try to come back with some info as soon as possible. Thanks again

**Comment by kgtkr** [comment]
I forgot to add sealedsecrets.bitnami.com/cluster-wide: "true" and unsealed failed
After that, when I modified it, it succeeded in unsealed, the secret was created, but the status remains false.

**Comment by tyb-dev** [comment]
Same issue here with helm-v2.6.7/sealed-secrets-2.6.7. I did not do an upgrade. Using sealed secrets the first time. Also using flux. 

kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:51:36Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by forexpiphunter** [comment]
Any update on this? We are facing the same issue.

**Comment by alvneiayu** [comment]
hi all

We can reproduce the bug. We will work on this as soon as possible. Anyway, we are open to receive PRs to solve the problem from the community, so I invite you to do it.

Thanks a lot

Álvaro

**Comment by forexpiphunter** [comment]
Hi All,

Do you have any updates on this? This is a serious issue we are running into on our clusters.  

Thanks!
