### ISSUE TITLE
/v1/verify endpoint throttling

### ISSUE THREAD

**Issue by revolunet** [bitnami-labs/sealed-secrets#870]
Hi there, 

We're trying to take advantage of [the `/v1/verify` endpoint](https://github.com/bitnami-labs/sealed-secrets/blob/b023eafcf510521dc950d959a7eab8e1d5869d29/cmd/controller/server.go#L50) by integrating the sealed-secrets validation during the CI/CD process. this way developers are informed before hitting deployment if something is uncorrectly sealed.

At the moment, there is [a built-in rate limiter](https://github.com/bitnami-labs/sealed-secrets/blob/b023eafcf510521dc950d959a7eab8e1d5869d29/cmd/controller/server.go#L128) with low hardcoded limits which makes it hard to use at scale.

Before trying any PR i have some questions :

 - do you think sealed-secret validation in CI makes sense or have other ideas ?
 - what about adding an `SEALED_SECRETS_VERIFY_RPS_LIMIT` env var (default 2) which allow to increase this ? with 0 it could disable the built-in rate-limiter and let the ingress take care of that?

Thanks !

**Comment by mkmik** [comment]
Sound good

**Comment by devthejo** [comment]
fixed by #873
