### ISSUE TITLE
Ability to append values to the secret name within a namespace

### ISSUE THREAD

**Issue by c-knowles** [bitnami-labs/sealed-secrets#89]
We have a use case where we want to be able to append variables to the name of a secret and not sure what might be the best way to deal with it. Looking for ideas first and then can think about whether it's PR appropriate.

When we used plain secrets, we appended the name of the secret with a version because we deploy a lot of feature branches and there's potential for changes or conflicts in the secrets. That gets done automatically by our deploy mechanism, so no need to manually update branches etc and our users never get conflicts with existing secrets. In the places we used sealed-secrets, we turned that versioning off because the name is encrypted into the data values - it needs that to ensure that one cannot just copy/paste the secret data from another sealed secret into your own one in the same cluster. So now we have two slightly different systems, we'd like to start using sealed-secrets everywhere but without a way to append variables to the name we'd need to rely on users to always keep backwards compatibility in secrets across all branches of an app.

I was wondering if/how it could be possible to deal with this situation. My idea was define the name as a pattern with substitutions and allow the substitutions to be passed in with the sealed-secret, maybe as separate labels. That idea might be quite powerful but also puts more of the burden of knowing if it's really secure on the shoulders of the user, so perhaps not a great way to go.

@anguslees any thoughts on this one?

**Comment by anguslees** [comment]
Brainstorming:

- we have "exact namespace/name" (default) and "cluster-wide=true" (with annotation) at present.  I think it would make sense to add "namespace-wide=true", and that such an option would be reasonably easy to understand the tradeoffs.
- we could add a pattern match/substitute for name and/or namespace, that effectively encompasses everything between "exact match" and "don't care".  I like the generality, but in practice I don't know of any common RBAC policies/mechanisms that allow creating namespace/resources within specified name prefixes (or patterns) like this.  Afaik, the available k8s mechanisms are either "can't create $resource", "can create $resource called $this", or "can create $resource with any name", so I share your concern that adding a pattern match adds complexity and false security.
- we could add an annotation that enumerated specific allowed namespaces/names.  This is kind of like the pattern match, but I think is closer to the capabilities of what RBAC policy can also describe.  Not sure if that usefully covers your use-case though.

**Comment by c-knowles** [comment]
Out of those ideas, I think the first option about namespace wide secrets makes the most sense. That's generally how permissions are modelled anyway and the context switching to that option seems relatively straight forward from an analysis point of view. So we'd end up with 3 different permission models. Perhaps even the annotation could be something like `sealedsecrets.bitnami.com/permission-model` or similar with allowed values of cluster, namespace, secret (default)?

Even though it was my initial idea, I've gone off the pattern thing. I think it's too complex. I agree with your assessment about other RBAC mechanisms. Kubernetes RBAC supports exact match `resourceNames` and probably won't support such expressions. See https://github.com/kubernetes/kubernetes/issues/56582 and https://github.com/kubernetes/kubernetes/pull/56603.

The last idea sounds interesting but would not work for our particular case since the version changes frequently, for some repos on every commit. So it'd be pretty much the same in terms of how many times we need to re-seal a secret.

**Comment by c-knowles** [comment]
I've updated to title to clarify that our case the differently named secrets are always required in the same namespace. I believe some other companies deploy feature branches to new namespaces so this would not deal with that problem but it's a start.

**Comment by c-knowles** [comment]
Will look to submit a PR for this soon to allow setting different access control modes.
