### ISSUE TITLE
Move out of kube-system namespace

### ISSUE THREAD

**Issue by BrianChristie** [bitnami-labs/sealed-secrets#90]
When running on GKE, nothing other than core Kubernetes components can run in the `kube-system` namespace (GKE throws errors).

Most likely it should be possible to run in any namespace. It looks like kubeseal has a --namespace argument, but from brief testing it looks like this is used for the namespace of the secret, rather than for finding the sealed-secrets-controller?

**Comment by anguslees** [comment]
Oh, I didn't realise GKE enforced this - good to know.

The controller should work in another namespace just fine, but you will need to modify `controller.yaml` to change the `metadata.namespace` values.

You are correct that `kubeseal --namespace` arg governs the namespace of the Secret/SealedSecret.  **The arg you want is `kubeseal --controller-namespace`** to find the controller and fetch the pubkey at runtime.

Note the recommended workflow is to run `kubeseal --fetch-cert` once, store the public key somewhere offline (trusted, but not necessarily hidden - I put it in git alongside my sealedsecrets, for example), and then use `kubeseal --cert` when encrypting.  This means you don't need access to the cluster (or RBAC privs, etc) when sealing, and also won't be affected by changes to the namespace and other operational details of the sealed-secrets controller.

Given what you say about GKE, we should a) document more clearly how to run in another namespace and b) consider just moving to another namespace by default, as you suggest.  Leaving this bug open to track those things.

**Comment by vitorarins** [comment]
Hey @BrianChristie, is this still true for GKE?
I just ran `kubectl -n kube-system run --image=busybox` and it worked. My cluster is at version `1.12.6-gke.10` for master and nodes.

**Comment by mkmik** [comment]
I also tried on GKE and it seems to work just fine (1.13+).

Are there other K8s distributions that would not allow admins to install stuff in `kube-system`?
Are there other good reasons for us to change the default ns (e.g. `sealed-secrets`)?

I intuitively feel that installing random stuff in `kube-system` makes me feel a bit dirty inside,
but on the other hand it's the most fool-proof way of ensuring that only admins can get Sealed Secrets private key (assuming that unprivileged users would be prevented from accessing kube-system).

Would it be trivial to craft some RBAC rules that we can bake in our YAML manifest for the `sealed-secret` namespace and which would work on any possible cluster out there? (or at least not silently leak private keys)

CC: @jjo

**Comment by mkmik** [comment]
There is _some_ overlap with #233 (not quite the same problem as the main topic here, but I can see that some people might land on this issue while they really are after #233)

**Comment by juan131** [comment]
I'll proceed to close this issue.

Both the SealedSecrets controller and kubeseal (using the `--controller-namespace` flag) have support for using any custom namespaces (regardless it's true that by default we set `kube-system` in the `controller.yaml` we publish in the releases pages).
