### ISSUE TITLE
--recovery-unseal without --recovery-private-key broken

### ISSUE THREAD

**Issue by david0** [bitnami-labs/sealed-secrets#912]
**Which component**:
kubeseal

**Describe the bug**
Its not possible to decrypt a key using `--recovery-unseal` online, without specifying `--recovery-private-key`

**To Reproduce**
1. create secret
2. seal
3. try `--recovery-unseal` without `--recovery-private-key`
4. see error

```
$ kubectl create secret generic secret-name --dry-run=client --from-literal=foo=bar -o yaml > mysecret.yaml
$ cat mysealedsecret.yaml | kubeseal \
                    --controller-name=my-release-sealed-secrets \
                    --controller-namespace=default \
                    --format yaml --recovery-unseal
error: no key could decrypt secret (foo)
```
**Expected behavior**
Unsealed secret yaml should be shown

**Version of Kubernetes**:

- Output of `kubectl version`:

```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:14:10Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:15:38Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by alemorcuq** [comment]
From the `--recovery-unseal` documentation:

```
--recovery-unseal                  
    Decrypt a sealed secrets file obtained from stdin, using the private key passed with --recovery-private-key. Intended to be used in disaster recovery mode.
```

You need to pass a private key in order to use the `--recovery-unseal` flag.

**Comment by david0** [comment]
Well, maybe its more of a feature wish than a bug. But my expectation would be that `--recovery-unseal` would work without  `--recovery-private-key` too, by quering the key from the cluster automatically.

The way it is implemented now is really not intuitive since its not doing what would be expected (at least by some) **and not complaining that its an invalid combination of arguments**.
