### ISSUE TITLE
panic: attempted to parse unknown event: none

### ISSUE THREAD

**Issue by gabrielpulga-grafeno** [bitnami-labs/sealed-secrets#915]
**Which component**:
kubeseal

**Describe the bug**
When running `kubeseal --cert mycert.pem <secrets.patch.yml > sealedsecrets.patch.yml
`, I get an error that I do not know how to debug.

My cert file was generated through `kubeseal --controller-namespace kube-security --controller-name sealed-secrets --fetch-cert > mycert.pem`

**To Reproduce**

1. Go to 'mycert.pem and sealedsecrets.patch.yml folder'
2. Run the command 'kubeseal --cert mycert.pem <secrets.patch.yml > sealedsecrets.patch.yml'
3. Wait for 'exit'
```
panic: attempted to parse unknown event: none [recovered]
        panic: attempted to parse unknown event: none

goroutine 1 [running]:
gopkg.in/yaml%2ev2.handleErr(0xc0000df998)
        /github/home/.cache/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v2@v2.4.0/yaml.go:249 +0x6d


```

**Expected behavior**
I expect to turn my secrets.patch.yml to a sealedsecrets.patch.yml file. With encrypted values in place of normal key values.

**Version of Kubernetes**:

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.11-eks-18ef993", GitCommit:"b9628d6d3867ffd84c704af0befd31c7451cdc37", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alemorcuq** [comment]
Can you share the structure of the secret you are trying to encrypt?

**Comment by aki-s** [comment]
FJYI:
I encountered exactly the same error, but if I looked into the file contents,
yaml format was broken in fact.

**Comment by philip-nicholls** [comment]
I had broken yaml too.  

It would have saved me time if kubeseal caught and handled a yaml parse error so that it shows a more user friendly message?

I'm not familiar with go stack traces and that error message on the top line is really strange.
