### ISSUE TITLE
Publish kubeseal binary in a Docker image

### ISSUE THREAD

**Issue by tewfik-ghariani** [bitnami-labs/sealed-secrets#916]
**Which component**:
`kubeseal`

**Is your feature request related to a problem? Please describe.**
We have an internal docker image that is built and published automatically via Gitlab CI and that it containing the `kubeseal` binary.
The Gitlab CI runners by default do not have internet access so we have added a static version of the kubeseal file and we have to update it manually every time there is a new release

Instead of that, we would like to have the possibility to dynamically fetch the latest version or take advantage of Renovate to upgrade the version used as soon as a new one is released  (Docker images are synched to a private registry )

**Describe the solution you'd like**
Ideally, I would like to be able to grab an official docker image that contains the `kubeseal` self-contained binary and just copy it to my image

```
COPY --from=bitnami/kubeseal:0.18.1 /usr/bin/kubeseal-linux-amd64 /usr/bin/
```

**Describe alternatives you've considered**
I would not specifically request one docker image per dist/arch. It can be one image that contains all different combinations and we can choose which binary to grab

**Comment by agarcia-oss** [comment]
Hi @tewfik-ghariani Thanks for the suggestion.

We believe it makes sense to publish an official docker image of kubeseal. Would you like to contribute with a PR to create the release?  
Regards

**Comment by tewfik-ghariani** [comment]
@agarcia-oss Thanks for the feedback! 😃  
Sure, PR created: https://github.com/bitnami-labs/sealed-secrets/pull/921
