### ISSUE TITLE
imagePullPolicy is Always in release controller.yaml

### ISSUE THREAD

**Issue by anguslees** [bitnami-labs/sealed-secrets#958]
**Which component**:

controller.yaml v0.18 (and older)

**Describe the bug**

The release `controller.yaml` includes

```yaml
image: "docker.io/bitnami/sealed-secrets-controller:v0.18.0"
imagePullPolicy: "Always"
```

"Always" here is surprising, and I think, incorrect.  In particular, this means that an in-place pod restart requires that the docker registry is available, even though the correct image is already available locally.

**Expected behavior**

```yaml
imagePullPolicy: "IfNotPresent"
```

(or absent, which would have the same default value)

**Additional context**

I believe the helm chart handles this correctly, and the issue is just the value set in `Makefile` and used when generating a release manifest.

**Comment by mkmik** [comment]
I _think_ the reason we set it to `Always` was to make sure the image used in the integration tests is up-to date.
The image name used in the tests is `docker.io/bitnami/sealed-secrets-controller:latest`; however, we always docker save and docker load the image, so that shouldn't be a problem.

**Comment by mkmik** [comment]
helm chart says: `## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'`

**Comment by josvazg** [comment]
I believe `Always` is only ever wanted when running the integration tests, just as @mkmik points out. We could instead use a random tag only for testing. That way we ensure to be testing the expected image. This also avoids passing make specific a `IMAGE_PULL_POLICY`.

This way we can make sure release defaults to `IfNotPresent` but our test behavior is as expected.

**Comment by mkmik** [comment]
CI integration tests actually use the "Never" policy; to make sure we use the image that has been docker loaded

**Comment by mkmik** [comment]
@josvazg see https://github.com/bitnami-labs/sealed-secrets/pull/959

**Comment by josvazg** [comment]
Thanks @mkmik !

I was working in parallel in a way to ensure the image under integration tests had a tag computed from the compiled binary. That was getting to complex too quickly, this is simpler and better.
