### ISSUE TITLE
Manage sealedsecret custom resource across clusters

### ISSUE THREAD

**Issue by Wilt-James** [bitnami-labs/sealed-secrets#969]
**Which component**:
controller

**Is your feature request related to a problem? Please describe.**
Currently the sealedsecret controller does not support monitoring the sealedsecret custom resource of other clusters. Do you have any plan to add a kubeconfig flag option to allow the controller to manage sealedsecret across clusters? Will this cause any problems?

The relevant code is as follows

https://github.com/bitnami-labs/sealed-secrets/blob/0e3ca3f4b8d10299e24cf4dd932eea2afb2ee11c/pkg/controller/main.go#L139

**Describe the solution you'd like**
Add a flag to set the cluster managed by the controller

https://github.com/bitnami-labs/sealed-secrets/blob/0e3ca3f4b8d10299e24cf4dd932eea2afb2ee11c/cmd/controller/main.go#L31-L31

**Comment by agarcia-oss** [comment]
Thanks for the feedback @Wilt-James. We do not plan to include that multi-cluster feature in the Sealed Secrets controller; that will include a great deal of complexity in the controller codebase and that's a feature that probably will not be relevant for a good part of our community.
