### ISSUE TITLE
Controller.yaml manifest doesn't contain image name

### ISSUE THREAD

**Issue by ViBiOh** [bitnami-labs/sealed-secrets#976]
**Which component**:

`controller.yaml` file in the release of 0.18.4

**Describe the bug**

There is no image name in the `controller.yaml` asset in [the release](https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.18.4)

**To Reproduce**

Download the file and find that the yaml contains `image: :v0.18.4`

**Expected behavior**

Download the file and find that the yaml contains `image: somewhere/bitnami/sealed-secrets-controller:v0.18.4`

**Comment by agarcia-oss** [comment]
Hi @ViBiOh you're absolutely right; there's an issue affecting the current `controller.yaml` file. We'll generate a new patch release shortly.

**Comment by alemorcuq** [comment]
`v0.18.5` was released with a valid [controller.yaml](https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.18.5/controller.yaml)

**Comment by ViBiOh** [comment]
Thank you for quick feedback ;)
